### ISSUE TITLE
Slack integration: crash report is not sent to Slack channel

### ISSUE THREAD

**Issue by professorbk** [firebase/firebase-android-sdk#1003]
### [REQUIRED] Step 1: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component:
```
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation 'com.google.firebase:firebase-inappmessaging-display:19.0.1'
    implementation 'com.google.firebase:firebase-dynamic-links:19.0.0'
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'
```

### [REQUIRED] Step 2: Describe the problem
I tried to integrate Firebase to Slack follows this guide, but crash reports are not sent to Slack channel
<https://support.google.com/firebase/answer/9005934?authuser=1>
#### Steps to reproduce:

- Integrated Firebase to Slack (create Slack webhook, add costumed Slack app,...)
- Inside Project overview -> Project settings -> General -> Slack integration: click "Send test message", then message "This is a test message for your Firebase project Test." is sent to Slack channel. Inside this screen, config Crashlytics "**All triggers on**"
- Force a crash on Android app, crash log is uploaded to Crashlytics, but no message is sent to Slack channel

The same issue also occurs on iOS app.

**Comment by samtstern** [comment]
@professorbk it does not sound like this is an issue with the Android SDK, since the crash is making it to the Crashlytics backend from the Android device it's just not triggering the Slack message.  Also you're having the same issue on iOS, so it's not platform specific.

If you haven't already, please file an issue with Firebase support so they can look into what's going wrong on the backend:
https://firebase.google.com/support
