### ISSUE TITLE
Question About Firebase Authentication

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-android-sdk#1063]
This is not a bug report just a question about Firebase Authentication which I cannot really see anywehere in the document and SO.

We have an app that has users that logged in with email/password and connect with gmail, now we decided to add phone auth on the app. We now want users to provide their phone number first before using the app using of course FirebaseUI library. Everything works except when we try to link the phone provider with the existing email/password or gmail provider and yes phone and gmail will become separate user with different uid and calling link with credential function will fail. So my question is there anything we can do so we can just merge the phone number on their previous account with email/password and gmail.

Example.

User is logged in with email or gmail provider thus getting phone number by this `FirebaseAuth.getInstance().getCurrentUser().getPhoneNumber()` will become empty then we will prompt the user to provide phone number by utilizing FirebaseAuthUI. Once it was verified then hoping to update the FirebaseUser like `FirebaseAuth.getInstance().getCurrentUser().setPhoneNumber('09*******')`

Merge the phone to current logged in Gmail something like that?
![image](https://user-images.githubusercontent.com/38008900/70985567-4da6a800-20f7-11ea-8d3f-915d239e953e.png)

**Comment by samtstern** [comment]
@ArcherEmiya05 that's a good question.  @malcolmdeck or @lsirac can you explain a little here?  I am actually not sure if it's possible to link a Phone and Email account credentials.

I definitely don't think it's possible with FirebaseUI, but that's a separate issue.

**Comment by ArcherEmiya05** [comment]
> @ArcherEmiya05 that's a good question. @malcolmdeck or @lsirac can you explain a little here? I am actually not sure if it's possible to link a Phone and Email account credentials.
> 
> I definitely don't think it's possible with FirebaseUI, but that's a separate issue.

Firebase automatically merge two provider like emai/password + gmail or facebook + gmail when it detects that the email on both provider is the same. But in phone auth can we also do this?

**Comment by ArcherEmiya05** [comment]
I also tried to export the firebase account using CLI with firebase auth:export account_file --format=csv but no phone number at all included while in document it does not exist.

**Comment by ArcherEmiya05** [comment]
Is the phone and email/password account can be possibly merge so we can utilize the OTP offered by the Firebase?

**Comment by yuchenshi** [comment]
To add a phone number to an existing user, please use [`linkWithCredential`](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser#public-taskauthresult-linkwithcredential-authcredential-credential) with the current user signed in. Please do not use `signInWithCredential` since that will create a new account if the phone number is not already linked to an existing account.

FirebaseUI's sign-in with phone number flow creates a new account. It does not support linking and unfortunately cannot be leveraged in this case. Feel free to file a feature request on FirebaseUI-Android or even send a PR our way. Until then, you'd need to implement the UI yourself to prompt the user for a phone number, and later the code for use with `linkWithCredential`.
