### ISSUE TITLE
Native symbols are not uploaded (missing)

### ISSUE THREAD

**Issue by bensadiku** [firebase/firebase-android-sdk#1066]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5.2
  * Firebase Component: Crashlytics + Crashlytics NDK
  * Component version: 
crashlytics-ndk:2.1.1
crashlytics:2.10.1

### [REQUIRED] Step 3: Describe the problem

Firebase crashlytics NDK reports the crashes but does not display the stack traces properly, it only shows as (missing).
The crashes from the Java layer are reported and working properly, issue is only with the native crashes.
Manual uploads of the symbols from the terminal did not solve it either.
I should say, there are no errors or no outputs when uploading the reports or during the initialization of the sdk's.

#### Steps to reproduce:

I have created a small repo for repro purposes.
[Link](https://github.com/bensadiku/crashlyicndkbug)

Clone the repo, link the firebase console and tap the crash button.

#### Relevant Code:
Some of the things i've tried to upload the native symbols that did not work.
```
./gradlew crashlyticsUploadSymbolsRelease // builds successfully
./gradlew crashlyticsUploadSymbolsDebug // builds successfully
```
Uploading the symbols automatically for all variants, did not upload the symbols.
```
android.applicationVariants.all { variant ->
    def variantName = variant.name.capitalize()
    def task = task("ndkbuild${variantName}")
    task.finalizedBy("crashlyticsUploadSymbols${variantName}")
}
```
Another way to upload the symbols automatically, did not upload the symbols.
```
tasks.whenTaskAdded { task ->
    def taskName = task.name
    if (taskName.startsWith('assemble')) {
        task.finalizedBy ("crashlyticsUploadSymbols" + task.name.substring('assemble'.length()))
    }
}
```

From the previous issues i'm reading here, downgrading the dependencies does nothing.

**Comment by aguatno** [comment]
Hi @bensadiku to help me investigate, could you send me a sample screenshot of the actual and expected result? Thanks

**Comment by bensadiku** [comment]
![Screenshot from 2019-12-24 10-34-49](https://user-images.githubusercontent.com/43443348/71406619-0eb5ac80-2639-11ea-8d32-5407de1784b0.png)
Anything that displays more info than this i'm okay with.

**Comment by aguatno** [comment]
Can you confirm that you have configured [NDK](https://docs.fabric.io/android/crashlytics/ndk.html#using-gradle) as expected? Thanks

**Comment by bensadiku** [comment]
Yes. As per the original post, i have configured everything from the documentation. ![I've also asked a stack overflow question, if that's any help to you. ](https://stackoverflow.com/questions/59305818/crashlytics-doesnt-display-native-crashes)

**Comment by aguatno** [comment]
Hi @bensadiku sorry for the late in response. Our team is looking for more information, these will help us to come up with the best possible solution:

-Link to your Crashlytics dashboard of the exact crash
-App's crashlytics.log - The file could be found on:

Linux / Windows: ~/.crashlytics/com.crashlytics.tools/crashlytics.log
Mac: ~/Library/Caches/com.crashlytics/com.crashlytics.tools/crashlytics.log

1.Delete crashlytics.log file 
2.Run symbol upload gradle task
3.Build and run app, run into test crash
4.Send crashlytics.log file + link to your Crashlytics dashboard of the exact crash that was just cause

**Comment by lucbloom** [comment]
It would be a great help if the Crashlytics Symbol upload process would output a response about what it did. I.E. "added", "overwritten", "sku not found", "version not found", "binaries don't match", "missing architecture: x86_64" or something, idk. And also which version it thinks it uploaded the symbols to.

**Comment by kevinkokomani** [comment]
One way to check up on some logs and see for yourself what the Crashlytics build tools are doing in terms of generating and uploading symbol files is by finding your crashlytics.log file, as aguatno mentioned (deleting the file first isn't strictly necessary, but following those steps will clear any past log data and give us only the data from the most recent build attempt):

On Linux / Windows:~/.crashlytics/com.crashlytics.tools/crashlytics.log
On Mac:~/Library/Caches/com.crashlytics/com.crashlytics.tools/crashlytics.log

If symbols are getting generated and uploaded, you should be able to find entries in there like:

```
Generating cSYM for <arch>/<libnativelib.so>
Crashlytics caching 1 code mapping for upload
Crashlytics attempting to upload cSYM files.
```
If you're able to see successful upload of symbol files, but can't seem to get symbolicated stacktraces, feel free to raise a support ticket with [Firebase support](https://firebase.google.com/support) as it will probably take some deeper diving to diagnose the issue. If you don't see successful upload, check out your project structure and try to find where to point the androidNdkOut and androidNdkLibsOut flags in your build.gradle. We need your stripped and unstripped binaries in order to generate mappings. You might find more helpful context here in the legacy Fabric docs: https://docs.fabric.io/android/crashlytics/ndk.html.

Finally, I wouldn't expect upgrading to the new beta SDK to help, as the currently implemented behavior for the NDK components are similar between beta and legacy. Definitely hear you @lucbloom on the lack of useful logging messages, though -- we're going to be trying to make improvements specifically to our NDK integration for the new beta SDK in the coming months to enable easier integration and usage and more robust debugging info, so stay tuned for any updates there. Hope this helps move some of these blocked projects forward.

**Comment by saurabhtomar91** [comment]
tasks.whenTaskAdded { task ->
    if (task.name.startsWith('assemble')) {
        task.finalizedBy "crashlyticsUploadSymbols" + task.name.substring('assemble'.length())
    }
}

When i am adding the above line of code for NDK uploadsymbols it will show me error like this

### Crashlytics could not find NDK output directory '/Users/saurabhtomar/Bobble-Android/ComicBook/app/obj'. Is the -androidNdkOut setting configured correctly?

Please Help me out what is the issue and how we will resolve it.

**Comment by kevinkokomani** [comment]
What is the directory structure at that location? The build tools are expecting to see something like this, although it can differ slightly from project to project:

```
-androidNdkLibsOut /Users/project/app/obj
obj/
  — armeabi
    — lib1.so
    — lib2.so
  — x86
    — lib1.so
    — lib2.so

-androidNdkLibsOut /Users/project/app/libs
libs/
  — armeabi
    — lib1.so
    — lib2.so
  — x86
    — lib1.so
    — lib2.so
```

So running the upload task in this example should generate 4 mapping files, called "cSYMs" in Crashlytics:

```
armeabi/lib1/<mapping file ID>.cSYM
armeabi/lib2/<mapping file ID>.cSYM
x86/lib1/<mapping file ID>.cSYM
x86/lib2/<mapping file ID>.cSYM
```
