### ISSUE TITLE
Firebase BOM doesnt' include com.google.firebase:firebase-iid

### ISSUE THREAD

**Issue by yogurtearl** [firebase/firebase-android-sdk#1077]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: any
  * Firebase Component: firebase-bom
  * Component version: 24.4.0

### [REQUIRED] Step 3: Describe the problem

firebase-bom doesn't include a version for com.google.firebase:firebase-iid

I have a library module that only needs `firebase-iid`, would like it to be able to pick up a version from firebase-bom

**Comment by ashwinraghav** [comment]
We intend to only codify top level product versions in the Bill Of Materials. This should transitively bring in IID. Can you speak more to the use case that forces you to use IID by itself?

**Comment by mikehardy** [comment]
@ashwinraghav it is a shame the original poster did not chime in, but react-native-firebase for instance directly references IID in order to expose it's API to firebase-android-sdk consumers that are accessing the SDK via react-native

The lack of IID in the BOM means that it is possible to have build errors when referencing the IID package using the BOM style, as evidenced in issues like this: https://github.com/invertase/react-native-firebase/issues/3918

**Comment by mikehardy** [comment]
:rofl: bad bot! we just started discussing it again :smile:

**Comment by yogurtearl** [comment]
Reopened, see this comment for use case: https://github.com/firebase/firebase-android-sdk/issues/1077#issuecomment-657011199

**Comment by ashwinraghav** [comment]
@mikehardy  Thanks for explaining the use case. Our general thought process with the BoM has been to only codify what we consider Firebase **products** that we ask customers to codify into their builds. We let gradle do its thing to resolve transitive dependencies like IID using the pom files that accompany these products.

We did not want one more vector that affects the versions to which these dependencies resolve.
 
What I'm gathering from your explanation is that this policy may be overly strict. We could possibly have all artifacts that have a public API in the BoM. Fair?

While this may work for IID itself, the broader policy may be challenging to enforce on all libraries, particularly those that are not part of Firebase and used across the Google library ecosystem. We'll need to think about this a bit more before making a decision, since these choices are hard to roll back.

**Comment by mikehardy** [comment]
It is difficult to make a really affirmative statement about large policy decisions, I understand.
It does seem that the general stance of putting anything with a public API in the BOM is most correct though, as it allows for cases like ours (react-native-firebase) where we try to depend on the versions provided to then basically re-export with our own versioning. I'm not sure how we can easily (the point of the BoM) handle things where any public API may be wrapped and re-exported without each API provider also being present.

Either way, thanks for your attention and thinking on it, I appreciate it

**Comment by mikehardy** [comment]
Any progress here? Just curious as I'm sweeping through issues and I own the related one in react-native-firebase. Cheers

**Comment by ashwinraghav** [comment]
Hey Mike,
Sry we've not paid much attention here. In your current build, how do you deal with what version of (say) the Tasks library resolves to? Seems like you would have to export that version in some form? 

I'm trying to determine the breadth of of libraries that need to be considered here.

**Comment by mikehardy** [comment]
Hi @ashwinraghav, thanks for the reply. I had not considered the tasks library, as we don't export that.

Our use case is that we wrap the native APIs from firebase-ios-sdk and firebase-android-sdk with native Obj-C and Java code then expose those (inside our module, which we control and do not expose) as Javascript APIs that mirror the firebase web sdk (where they exist, or just reasonable APIs where the web does not have an analog) for use inside react-native apps.

Because instance id is a firebase module and has public APIs and the goal of react-native-firebase is to expose the full firebase API surface area (but in JS-friendly way) we need IID but Tasks is not important to us.

Hopefully that makes sense?

**Comment by mikehardy** [comment]
The 25.13.0 BoM appears to contain IID again, I no longer need to specify a version to compile against it. Thanks!
