### ISSUE TITLE
Firestore's writes does not notify persistence offline

### ISSUE THREAD

**Issue by lshens** [firebase/firebase-android-sdk#1097]
**Dependencies**

```
implementation 'com.google.firebase:firebase-common:19.3.0'
implementation 'com.google.firebase:firebase-firestore:21.3.1'
implementation 'com.google.firebase:firebase-auth-interop:19.0.0'
```

**Problem**

The problem is related only for **write** operations in the **Firestore**, while there is no internet connection (**offline**). The **Firestore** does not sent any notification in the listener `addOnSuccessListener` or `addOnFailureListener` telling that the **document** was cached or persisted it in disk.

**Example to reproduce**

```
void save(CarPark carPark) {
    firebaseFirestore
              .collection("carparks")
              .document("f24ac44c-6958-4dac-bcbb-53ba44065481")
              .set(carPark)
              .addOnSuccessListener(
                      new OnSuccessListener<Void>() {
                        @Override
                        public void onSuccess(Void aVoid) {
                          Log.d("TEST", "Success");
                        }
                      })
              .addOnFailureListener(
                      new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception e) {
                          Log.d("TEST", "Failed");
                        }
                      });
}
```

**Expected Behavior**

I believe that the *Firestore* should send an event telling that the cache was made, some listener like  `addOnCachedListener` or `addOnOfflineModeListener`

**Comment by wu-hui** [comment]
Hi Ishens,

Thanks for raising this up. You are right that the `Task` returned by `set` will not tell you if the data is written to local disk or not, because that `Task` is mainly serving the purpose of telling user if the backend has acknowledged or rejected the write.

However, the mere fact that `set` returns is a signal that the data is written to local disk. After `set` returns, you can starting next statement assuming your writes are saved in local persistence.

Thanks.
