### ISSUE TITLE
Native symbols crashlyticsUploadSymbols{variant} Crashlytics found no symbols for *.so skipping

### ISSUE THREAD

**Issue by dsuresh-ap** [firebase/firebase-android-sdk#1316]
Same issue as in https://github.com/firebase/firebase-android-sdk/issues/1220

#### Environment

  * Android Studio version: 3.6.1
  * Gradle Version version: 5.4.1
  * Gradle Plugin version: 3.5.0
  * Fabric Plugin - 1.31.2
  * Fabric Crashlytics - 2.1.0
  * Fabric Crashlytics NDK - 2.10.1

Gradle plugin version 3.5.3
Gradle version 5.5

#### Issue

We added the NDK reporting functionality as mentioned in the docs and we do not see the native crashes being deobfuscated. The only two native libraries that we have are 3rd party (Crashlytics and Realm).

#### Crashlytics.log

Log is attached, sensitive information has been removed.

It looks like `cSymGen` is unable to find symboles for the `.so`s.

```
2020-03-05 11:11:23.406 [DEBUG] (Execution worker for ':' Thread 4) com.crashlytics  - Crashlytics found no symbols for /productionDebug/out/lib/armeabi-v7a/libcrashlytics.so, skipping.
2020-03-05 11:11:23.406 [DEBUG] (Execution worker for ':' Thread 4) com.crashlytics  - Generating cSYM for /productionDebug/out/lib/armeabi-v7a/librealm-jni.so
2020-03-05 11:11:23.418 [DEBUG] (Execution worker for ':' Thread 4) com.crashlytics  - Using ELF data for cSYM generation.
2020-03-05 11:11:23.418 [DEBUG] (Execution worker for ':' Thread 4) com.crashlytics  - Crashlytics found no symbols for /productionDebug/out/lib/armeabi-v7a/librealm-jni.so, skipping.
```

#### Relevant Code:

```
crashlytics {
    enableNdk = true
    androidNdkOut = "build/intermediates/merged_native_libs"
    androidNdkLibsOut = "build/intermediates/stripped_native_libs"
}
```

We had to configure the `androidNdkOut` and `androidNdkLibsOut` as shown above otherwise it would not sync using the default settings.

Another thing to note is that the Realm and Crashlytics dependencies are in their own library in the project. However the build directories for those libraries do not have any data.

We can't upgrade to the new Firebase beta yet because it is in beta and also requires AndroidX. Is there anyway to make it work with the Fabric plugin?
[crashlytics.log](https://github.com/firebase/firebase-android-sdk/files/4294196/crashlytics.log)

**Comment by personshelldon** [comment]
As I know, debug symbols must be generated and uploaded only for libs that were built in Your app. Crashlytics and Realm do not provide debug symbols as they added as libs and may not provide needed data. For test, write own JNI lib in Your project and then retest this.

**Comment by dsuresh-ap** [comment]
@personshelldon I assumed that was the case. So there is no way to de-obfuscate crashes in 3rd party library native code?

**Comment by personshelldon** [comment]
@dsuresh-ap, as I know - yes, because release libraries and packages do not provide `so` libs with debug information, only final `so` lib with stripped debug symbols. If You want to do this You need to find sources for needed libs and build them directly in Your project, in that case Android Studio will generate debug `so` libs for upload and release libs with stripped debug information for Your apk.

For such cases as You described I use another solution - when error occurred, there is always obfuscated stack trace in Firebase Crashlytics. By stack address that printed in stack trace You can find point in lib where the error occurred by analyzing lib in IDA Pro or Ghidra application (disassembling native library). When problem found You need, again, sources of that lib to fix the problem, but You are using them as dependency. Vicious circle=)

**Comment by dsuresh-ap** [comment]
@personshelldon That makes sense. I opened an issue in Realm project as they suggest in their docs to include the Crashlytics NDK setup. If there is no effect of this I am wondering why they would suggest it.

**Comment by ashwinraghav** [comment]
Thanks for helping @personshelldon 
While I am not entirely certain about third party native libs, Crashlytics certainly does recognize third party libs that your app contains. I'll wait for someone from the crash team to help answer this a bit better

**Comment by rgipd** [comment]
@ashwinraghav Just for telling a little more about #1642, I'm not using nothing about Fabric.io, just Firebase Crashlytics. Also it's for my own library/NDK code, no 3rd party. I made the NDK source code for this project with kotlin. There are any test or log I can make for help?

Thanks.

**Comment by mrwillis21** [comment]
Hi folks! Apologies for the radio silence on this one.

@dsuresh-ap and @personshelldon We can symbolicate any libraries (3rd party or otherwise) for which you are able to upload symbols from your app. My understanding is that Realm does (or at least did at one time) make available their unstripped libraries for symbol upload with Crashlytics. The process would be to include those unstripped libraries in your project and upload symbols for them alongside any other app binaries you're compiling.

@rgipd were you seeing unsymbolicated crash reports for your app build? If so, is this still an issue for you?

**Comment by dsuresh-ap** [comment]
I followed the suggestion from https://github.com/realm/realm-java/issues/6773 to include the unstripped libs and point Crashlytics to them for symbols during build.

**Comment by hardysim** [comment]
I just found a hint in the release notes for Android Studio 4.1 about "Symbolication for native crash reports". Just add the following line to the app's `build.gradle` (having the NDK installed) and it will generate debug symbols into the app bundle. When using this, the PlayStore not longer shows the warning.

`android.buildTypes.release.ndk.debugSymbolLevel = 'SYMBOL_TABLE'`

References:
- https://android-developers.googleblog.com/2020/10/android-studio-41.html
- https://support.google.com/googleplay/android-developer/answer/9848633

---

Is this enough and crayhlytics will use the now embedded information in the app bundle? Or do I need to add more configuration (like https://firebase.google.com/docs/crashlytics/ndk-reports)?

**Comment by hardysim** [comment]
> I followed the suggestion from [realm/realm-java#6773](https://github.com/realm/realm-java/issues/6773) to include the unstripped libs and point Crashlytics to them for symbols during build.

@dsuresh-ap can you provide the exact code you used? [I'm having trouble using the current crashlytics versions](https://github.com/realm/realm-java/issues/6773#issuecomment-708216897).

**Comment by mrwillis21** [comment]
Hi everyone - are you still seeing issues with this? If so, can you try Crashlytics NDK 17.3.1 and Crashlytics Gradle plugin 2.4.1?

**Comment by dsuresh-ap** [comment]
@mrwillis21 We are not seeing this issue anymore. The problem was the Realm lib doesn't include unstripped libs so we had to manually add them and point to them. This issue can be closed.

**Comment by mrwillis21** [comment]
Glad to hear it, thanks @dsuresh-ap !
