### ISSUE TITLE
Single Sign On (SSO) for more than two apps

### ISSUE THREAD

**Issue by Qamar4P** [firebase/firebase-android-sdk#1452]
Hi @firebase team, We have two Android apps (signed with same signature) that uses same Firebase. So we want to share the token b/w these two apps so that login in one app auto logged in another app. Any clean solution will be appreciated. Also requested here https://github.com/firebase/firebase-js-sdk/issues/2291 Thanks

**Comment by ashwinraghav** [comment]
Thanks, that's an interesting problem.
How would you know that it is the same user that is logging into your "other" app as well ?
While you may want to not have the user log-in more than once, it may not be the best idea to share tokens. Apps in the same Firebase project will be bound to the same user id. So you are going to be able to identify them across all your apps.

Related, If you are using Firebase Auth's phone auth,  it does have the notion of [instant verification](https://firebase.google.com/docs/auth/android/phone-auth) that is a seamless automagically-logged-in experience if you have a verified phone number on the device.

Another way that comes to mind is to use chrome tabs to open your trusted domain, and log your user in through the web and redirect tokens to your app's custom scheme. Since chrome tabs cookies are preserved like browser sessions, you may be able to have your user be automagically logged in when they open it from your "other" app, and you can redirect tokens to this other app's scheme.

**Comment by Qamar4P** [comment]
@ashwinraghav you got the idea. User must be same. Think about main app with companion app. 
For now I shared creds, It;s working but saving creds isn't good idea. I used loginWithEmail. Anyway thanks
