### ISSUE TITLE
Firebase Messaging/InstanceID not working on emulator

### ISSUE THREAD

**Issue by doom777** [firebase/firebase-android-sdk#1482]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.2
  * Firebase Component: Messaging
  * Component version: 20.1.1-2.1.5

#### Steps to reproduce:

Firebase Instance ID not not created, and firebase messages not sent on an emulator

see: https://stackoverflow.com/a/60565682/356083

**Comment by andirayo** [comment]
To improve security Firebase Android SDK [updates on February 27](https://firebase.google.com/support/release-notes/android#2020-02-27) (M65) and afterwards introduced a new infrastructure service, the Firebase Installations SDK which comes with a dependency on the [Firebase Installations API](https://console.cloud.google.com/apis/library/firebaseinstallations.googleapis.com). \
Firebase Installations requires valid Firebase options API key, project ID, and application ID in order to successfully communicate with Firebase servers.

Errors during communication with the Firebase Installations API indicate invalid Firebase options.
To mitigate the issue
* make sure that your application is using the latest `google-services.json` file from your Firebase console:
  [Firebase options: Instructions and background](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/REQUIRED_FIREBASE_OPTIONS_ANDROID.md)
* if you use API restrictions, make sure that the API key used by your application is white-listed for the Firebase Installations API:
  [API restrictions: Instructions and background](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/API_KEY_RESTRICTIONS.md)

**Comment by andirayo** [comment]
We haven't heard back from you, thus I'm closing this issue. Please feel free to reopen it.
