### ISSUE TITLE
Automatic screen_view conflicts custom setCurrentScreen usage

### ISSUE THREAD

**Issue by piotrkst** [firebase/firebase-android-sdk#1487]
### Environment

  * Android Studio version: 3.6.2
  * Firebase Component: Analytics
  * Component version: 17.3.0

### Problem

Automatic logging screen_view within activities causes conflict, when my activity is a container displaying fragments. When my first fragment comes in and tries to set it's presence using 'setCurrentScreen' method, it fails while logcat reports:
"Screen exposed for less than 1000 ms. Event not sent."

Along with many predecessors that reported their issues here which were ignored for the past 3 years? They wanted to have option to disable automatic logging (which by the way was possible on iOS):
https://github.com/firebase/quickstart-android/issues/370

#### Steps to reproduce:

Run setCurrentScreen in Fragment that is rendered within Activity.

**Comment by vkryachko** [comment]
@g-charbel fyi

**Comment by Lucodivo** [comment]
+1 for disabling automatic logging.

In order to protect the user's privacy as much as I can, I want to not track anything I don't need to. 

My particular problem is that I explicitly ask users whether they accept me using their data for analytics. And I would like to respect their decision with the exception being that I would record the event of whether they opt-in/out of being tracked, regardless of the option selected. This is to help me gain insight into what percentage of my users are represented by the analytics being captured.

**Comment by allenktv** [comment]
Thanks @piotrkst, we are actively working on this feature and will have something to report in the near future!

**Comment by allenktv** [comment]
Hi all, updating this thread to let you know that this feature was [released](https://firebase.google.com/support/release-notes/android#2020-08-14). Thank you!
