### ISSUE TITLE
This is related to firestore read request. Firestore implemented in android application. Using firestore with persistence disabled.(offline cache not working) are still firestore syncing working with firestore server? what frequecny of syncing ? any way to disable syncing ?

### ISSUE THREAD

**Issue by rajnesh-culturealley** [firebase/firebase-android-sdk#1500]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by rajnesh-culturealley** [comment]
This is related to firestore read request.
Firestore implemented in android application. Using firestore with persistence disabled.(offline cache not working)
are still firestore syncing working with firestore server?
what frequecny of syncing ?
any way to disable syncing ?

**Comment by rajnesh-culturealley** [comment]
This is related to firestore read request.
Firestore implemented in android application. Using firestore with persistence disabled.(offline cache not working)
are still firestore syncing working with firestore server?
what frequecny of syncing ?
any way to disable syncing ?

**Comment by schmidt-sebastian** [comment]
@rajnesh-culturealley Firestore needs to read data from the backend whenever you use `get()` or an `addOnSnapshotListener()`. In general, we try to read only the minimum number of documents needed to satisfy your API calls, but note that this does work better with persistence enabled (since this allows us to resume Queries from prior snapshots).

While we do not provide first-level metrics for the read behavior in the SDK, you can look at the data that is exchanged between the SDK and the backend if you [enable logging](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#setLoggingEnabled(boolean)).
