### ISSUE TITLE
Firebase Crashlytics uses Dagger 2 while my project uses Dagger 1

### ISSUE THREAD

**Issue by kaciula** [firebase/firebase-android-sdk#1643]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.6.3
  * Firebase Component: Firebase Crashlytics
  * Component version: 17.0.1

### [REQUIRED] Step 3: Describe the problem

Adding the dependency for the new Firebase Crashlytics makes my project not build anymore because I am using Dagger1 everywhere in my code and it seems Crashlytics uses Dagger 2.

Seeing that there are big projects still using Dagger 1 and migrating to Dagger 2 is impossible for the foreseeable future, I am hoping there is a way for the Firebase SDK to work also with Dagger 1 projects.

Please provide some guidance on this issue. Either have the firebase sdks relocate Dagger 2 packages or provide a solution for clients of the SDK to have both Dagger 1 and Dagger 2 in their projects.

Thanks.

**Comment by ashwinraghav** [comment]
Thanks for the report. I recognize the challenge of running into this while migrating from Fabric. Unfortunately, dagger 2 is the standard across a variety of Firebase products that are ubiquitous across Android apps - In App Messaging, Crashlytics, Firebase Messaging. 

It is a challenge deciding what versions of dependencies Firebase SDKs can have. On the one hand we have to think of what version most of our customers use, while also considering how we can continue supporting customers who want the latest and greatest. At times, this forces us to not use any libraries in our products and write things ground up.

We decided to roll forward with Dagger2 a while back, since Dagger1 has been [deprecated](https://github.com/square/dagger#deprecated--please-upgrade-to-dagger-2) for a while, and the [performance benefits](https://github.com/google/dagger#dagger) it offers to us and Firebase customers makes this worthwhile.

# Work around
I've not tried this myself. But I can imagine how this would work if you wanted to incrementally migrate off of Dagger 1 to Dagger 2 while continuing to use Firebase dependencies.

1. Consider using the excellent `com.github.johnrengelman.shadow` shadow plugin to repackage dagger to (say) `firebase.dagger`.

2. By default, the plugin also migrates any imports in third party dependencies, which would automatically replace any references to dagger in crashlytics.

I realise that is not code. But, that's the best I got given our official position.

| References|
| :----- |
|[Dagger 1 and 2 together](https://proandroiddev.com/dagger-1-and-dagger-2-together-917f082b3dd9)|
|[Migrating to dagger 2incrementally](https://fernandocejas.com/2016/08/03/android-dagger-1-and-2-living-together)|
|[Shadow Plugin](https://imperceptiblethoughts.com/shadow/)|
|[Sample project](https://github.com/android10/two-daggers)|
