### ISSUE TITLE
FirebaseAuth user email storage

### ISSUE THREAD

**Issue by next-josemarcosrubio** [firebase/firebase-android-sdk#1681]
### Describe your environment

  * Android Studio version: 3.6.1
  * Firebase Component: Auth
  * Component version: 19.3.1

### Describe the problem

Using FirebaseAuth component, in order to perform signInWithEmail link operation, we have been reported a security issue due to the email management itself. Email seems to be stored with no encryption provided, and it may be found under 'com.google.firebase.auth.api.Store.{code}.xml'.

**Comment by malcolmdeck** [comment]
Hey there, Malcolm from Firebase here! There's some ambiguity in your post, so I'm going to address a few things in separate paragraphs here to try to cover my bases.

Firstly, the Firebase Auth library does not store the email you provide to that sign-in provider while the operation is in-progress. That is the only relevant security whole that could exist before a sign-in occurs on that provider as far as I can tell.

As for the named SharedPreferences file, com.google.firebase.auth.api.Store.{code}.xml, that is, indeed, where we persist user state. When the application goes into the background or is closed, the currently logged-in user needs to be stored somewhere, and SharedPreferences is a safe place to do so - it has private filesystem permissions, meaning that only that application (or a process with root permissions) can read it. As such, encryption isn't necessary. In general, Firebase only makes security guarantees about unrooted, non-userdebug devices; the security properties of rooted or userdebug devices are significantly degraded in ways that we cannot properly account for. 

Still, the question remains, why don't we encrypt things in storage? The answer is pretty simple: it provides no additional security (other than security-by-obscurity) and has both a performance and complexity penalty. For example, a root user can also access the Android Keystore as the target application, meaning that they can still read the SharedPreferences, they just have to read and use the appropriate key first. 

If I've misunderstood your problem or you have additional questions or concerns, feel free to re-open this issue. For now, I'm closing it as resolved since I think (and I hope) I've addressed your concerns.
