### ISSUE TITLE
firebase_crashlytics_collection_enabled = false, not working

### ISSUE THREAD

**Issue by gummibjorn** [firebase/firebase-android-sdk#1763]
### Describe your environment

  * Android Studio version: 4.0
  * Firebase Component: firebase-crashlytics
  * Component version: 17.1.1

### Describe the problem

Crash reports are sent to firebase even though I use the following meta-data tag in my Manifest:

``
        <meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="false" />
``

I do not use FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true)

**Comment by ashwinraghav** [comment]
Thanks for the report.
I've not been able to repro. The related piece of code is linked below. Let us know if you see something that stands out
https://github.com/firebase/firebase-android-sdk/blob/dac28c4733aad8a29cd9afb4cc9c1912196e7fa5/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java#L410

Otherwise, you may receive better help in our [support channels](https://firebase.google.com/support)

**Comment by gummibjorn** [comment]
Thanks for your response. I figured it out. I've been using ``FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true)`` in previous launches of my app. And since this setting persist across launches, crash reports were sent to firebase despite the meta-data tag set to ``false``.

This behaviour is documented.
![image](https://user-images.githubusercontent.com/11292339/86891673-85ab2200-c0ff-11ea-85ec-35fb1f3ad81e.png)
