### ISSUE TITLE
If I want to initialized these libraries by in some special time or not on ContentProvider's onCreate，what should I do？

### ISSUE THREAD

**Issue by ljzyljc** [firebase/firebase-android-sdk#1837]
hello，I read the source of firebase-android-sdk，the Initializers pass the ContentProvider‘s onCreate，the method is before application oncreate，I depend a lot of firebase libraries，So many libraries are initialized in contentProvider onCreate，I think will affect the startup speed of the APP，is it right？

If I want to initialized these libraries by in some special time or not on ContentProvider's onCreate，what should I do？

**Comment by ashwinraghav** [comment]
Some libraries are easier than some others. What are the libraries you are trying to instantiate?

**Comment by ljzyljc** [comment]
crashlytics,crashlytics-ndk,message,dynamic-links,analytics,storage,database,etc @ashwinraghav

**Comment by ashwinraghav** [comment]
Thanks for clarifying. Unfortunately for analytics, crashlytics[-ndk] these become super hard, since we don't have the APIs that are going to help you. The most useful conversation about this is captured in https://github.com/firebase/firebase-android-sdk/issues/66 and we have some long term work in progress to help.
Please follow along in that bug.
