### ISSUE TITLE
Firestore offline sync problem

### ISSUE THREAD

**Issue by ServeMe** [firebase/firebase-android-sdk#184]
* Android Studio version: 3.1.3
  * Firebase Component: Firestore
  * Component version: 17.1.4

the app does not sync caching when the app is offline
I write a full article here to workaround the problem
https://medium.com/@alaadiaa/does-firebase-firestore-a-real-rtdb-on-android-f7dd280ca01f
if I missed something let me know
I love to get any note or best solution

**Comment by mikelehen** [comment]
Thanks for the feedback, but it's difficult to figure out what your question is based on the blog post.  I can tell you that:

1. Firestore does not do any background syncing when your app is not running. This is intentional.  For background notifications, you'd want to use Firebase Cloud Messaging.
2. Firestore initializes itself lazily.  In particular you need to call `.collection()` or `.document()` in order for it to initialize and start syncing data.  So to make sure that changes previously made while offline are promptly synced to the backend, you may want to make sure that your app always at least makes a call to `.collection()` or `.document()` so Firestore is initialized and will start syncing data.
3. Your approach of using `.hasPendingWrites()` to see if there are pending writes is a good idea, but you shouldn't need to schedule a recurring job.  Just use a snapshot listener (i.e. `.addSnapshotListener()`.  That's exactly what they're for.  If you pass `MetadataChanges.INCLUDE` then you'll get a new snapshot whenever the metadata changes, so you can just check `.getMetadata().hasPendingWrites()` in your listener.
4. Similarly, you can use a listener to monitor `.isFromCache()` rather than using a recurring job.

I hope this helps.

**Comment by ServeMe** [comment]
@mikelehen thank you for your respond
I have two cases
case 1 I am the one who is modify the document but on offline mode usually when you have offline you must need to have a sync mechanism and as a RTDB you must sync ASAP if you do not want to do that you must mention that clearly on your official document  because people will expect you to do that.
case 2 I am not the one who is do the modification but I am interest on that document so the app send me notification to tell me that but I do not open the app when I was online I open it when I become offline which also a problem because I will see an old data and again because people think of firestore as a RTDB they expect that does not happened and firebase need to mention that clearly.

BTY I do not use addSnapshotListener because simply services in new android versions have a lot of limitations and I do not use recurring job I use a job with requirements only
