### ISSUE TITLE
[FEATURE] Crashlytics through Google Play Services

### ISSUE THREAD

**Issue by jpmcosta** [firebase/firebase-android-sdk#1895]
## What feature would you like to see?

(Note: I'm not entirely sure if this should be posted here, please close the issue if it doesn't.)

I was wondering if it would be possible to have a separate Crashlytics library that only worked with Google Play Services. The goal would be to remove the need for `android.permission.INTERNET` permission.

I'm developing a notification history application and Crashlytics is the only reason my application needs the `android.permission.INTERNET` permission, which raises some privacy concerns among users.

## How would you use it?

It could work as a Gradle configuration to turn on or off the dependency on Google Play Services, or simply by importing a different dependency than `com.google.firebase:firebase-crashlytics`.

**Comment by ashwinraghav** [comment]
Thanks for the feature request.

Fwiw, firebase-crash, the deprecated predecessor to crashlytics, was built on play services and we made the explicit decision to move away from play services for crashlytics. Here's why:

1. Having this be part of play services increases a significant amount of complexity for product development. The release cycles become longer and the development experience is more tedious, bug fixes take longer.

2. Firebase products in general are moving away from the use of play services, since we have a design goal to work on non play devices, made by a variety of Android phone manufacturers, all over the world. While there are other ways to achieve this design goal (like the DevX you suggested), our efforts have been focussed on moving things **out** of play services, to minimize maintenance costs of several products.

There are other reasons too, but I'll spare you the tedium. Your best bet may be to use the play console's crash reporting solution for now, since I don't see us going back into play services.

**Comment by jpmcosta** [comment]
Thank you ver much for such a comprehensive reply.

**Comment by jpmcosta** [comment]
Thank you very much for such a comprehensive reply.
