### ISSUE TITLE
Firebase In-App Messaging doesn't show messages properly after .setMessagesSuppressed(true/false) used

### ISSUE THREAD

**Issue by amatkivskiy** [firebase/firebase-android-sdk#2027]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _Android Studio 4.0.1, Build #AI-193.6911.18.40.6626763, built on June 25, 2020_
  * Firebase Component: _In-App Messaging_
  * Component version: _19.1.1_

#### Steps to reproduce:

In my Android app, I have three activities (sample app can be found here: https://github.com/amatkivskiy/firebase-in-app-message-issue): 

 - *SplashActivity*
 - *StartActivity*
 - *MainActivity*

And I have a requirement to show FIAM messages only on *MainActivity*. So with the help of `FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true/false)`(in `Activity.onCreate()`) I've implemented the flow like this: 

![InAppMessageIssueAppFlow](https://user-images.githubusercontent.com/3864884/94783701-bab0d300-03d5-11eb-8043-c9ac06b1ebc1.png)

Unfortunately with this approach, FIAM messages are not shown at all (on any of the app screens). If I remove any calls to `FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true/false)` then it FIAM messages are shown on every screen (SplashActivity, StartActivity and MainActivity) **which is not what I need for the app**. 

Maybe I am doing something wrong but without this feature, I am not able to use FIAM in my app.
Can someone help me please with this?
#### Relevant Code:

```
FirebaseInAppMessaging.getInstance().setMessagesSuppressed(true/false)
```

**Comment by amatkivskiy** [comment]
Hi @prakhar1989 , any updates on this?

**Comment by eldhosembabu** [comment]
Hi @amatkivskiy ,

This is working as expected actually. Once you call `FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)` its actually enabling the SDK to show messages upon event trigger. So if any trigger occurs afterwards, it will show the inapp message. ie. for example if you put the app to the background and relaunch it etc.

In your case, i understand that you need to show the pending inapp messages when you call `FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)` and for that we can do a workaround to achieve the same as follows :

Edit your Firebase Inapp messaging campaign to add a temporary event say "show_pending" or something you prefer.

![Screen Shot 2020-10-15 at 11 55 34 AM](https://user-images.githubusercontent.com/5833071/96173945-71847700-0edd-11eb-9da3-56aa4fbe8c56.png)

Then when you are enabling the messages, trigger the event that you created above.

Like : 

`
FirebaseInAppMessaging.getInstance().setMessagesSuppressed(false)
FirebaseInAppMessaging.getInstance().triggerEvent("show_pending")
`

Hope this will help you. Let us know otherwise.

**Comment by eldhosembabu** [comment]
Closing this issue expecting the workaround helped.
