### ISSUE TITLE
FirebaseCrashlytics extension not copied when using initWith in build types

### ISSUE THREAD

**Issue by kschults** [firebase/firebase-android-sdk#2056]
### [READ] Step 1: Are you in the right place?

It's possible that this is a bug with AGP, but starting here first

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.0.1
  * Firebase Component: Crashlytics
  * Component version: 17.2.2
  * Android Gradle Plugin: 3.6.2

### [REQUIRED] Step 3: Describe the problem

When using multiple build types, no `uploadCrashlyticsSymbolFile<BuildType>` is generated when build types are delcared using `initWith`

#### Steps to reproduce:

In `MyApp/build.gradle`:

```
buildTypes {
    release {
        firebaseCrashlytics {
            nativeSymbolUploadEnabled true
            <etc>
       }

    alpha {
        initWith release
    }
}
```

If I run `$> ./gradlew :MyApp:uploadCrashlyticsSymbolFileAlpha` I get an error: Task not found
`$> ./gradlew :MyApp:uploadCrashlyticsSymbolFileRelease` succeeds.

I know I can work around this by copying and pasting my `firebaseCraslytics` extension into each build type, but it would be really nice to have it inherit correctly

**Comment by mrichards** [comment]
Thanks for reporting! We know the workaround isn't ideal and will fix this at some point. Internally tracked as feature request: b/179017029

**Comment by kschults** [comment]
Hey @mrichards, do you have any update on this? Thanks!

**Comment by mrichards** [comment]
@kschults It turns out that the implementation of `initWith` selectively copies fields from the buildType, and does not perform a generic cloning operation across all fields + extensions. So there's nothing we can do to support this in the Crashlytics Gradle plugin at this time.

I've contacted the Android Gradle plugin team about this and they are considering modifying the `initWith` implementation to include copying values from registered DSL extensions. I'll update here if/when they have a timeline for making that change.

**Comment by kschults** [comment]
@mrichards Thanks for the update. Is there a publicly visible ticket somewhere to track that work on the plugin side?

**Comment by mrichards** [comment]
@kschults Not at this time, but I'll keep an eye on the internal conversation and post when I know more, including a public ticket if one is made.

**Comment by mrichards** [comment]
Closing this as the required work has not been prioritized by the Android Gradle plugin team. Our internal ticket is still open.
