### ISSUE TITLE
Prevent crashlytics initialization if data collection is not enabled.

### ISSUE THREAD

**Issue by hborders** [firebase/firebase-android-sdk#2082]
## What feature would you like to see?

When Crashlytics data collection is not enabled, Crashlytics should not initialize: Crashlytics should not add uncaught exception handlers and Crashlytics NDK should not register signal handlers for crashes.

## How would you use it?

I want to A/B test multiple crash reporters in my app at runtime. Firebase's component framework always initializes Crashlytics, which always adds uncaught exception handlers and NDK signal handlers. This conflicts with other crash reporters. Crashlytics should support fully manual initialization. I need to investigate other crash reporters because Crashlytics NDK still doesn't report crashes for Android 10 and Android 11 (https://github.com/firebase/firebase-android-sdk/issues/1678).

## Current attempts

I've added `firebase_crashlytics_collection_enabled=false` to my `AndroidManifest.xml`:
```
        <!-- Crashlytics -->
        <meta-data
            android:name="firebase_crashlytics_collection_enabled"
            android:value="false" />
```

and then I manually called `FirebaseApp.initialize` within my `Application` subclass, and even though I never call `FirebaseCrashlytics.setCrashlyticsCollectionEnabled`, I still see Crashlytics registering its uncaught exception handler. I'm not familiar enough with NDK crashes to determine whether Crashlytics NDK behaves similarly, but I saw Crashlytics NDK's initialization, so I assume Crashlytics NDK registers native signal handlers as well.

**Comment by hborders** [comment]
https://github.com/firebase/firebase-android-sdk/issues/1678 is fixed, so this isn't as pressing, but it's still frustrating that I can't do a real A/B test with other crash reporters.

**Comment by mrichards** [comment]
@hborders The Crashlytics SDK operates this way intentionally, to enable the following use case: Apps with very strict privacy policies need explicit consent from users before sending crash reports to Firebase. Rather than prompt all customers to opt in on the initial launch of the app, the app can ask the user for permission to send the crash **after the crash occurs**. This way, only customers who experience a crash are prompted to opt in. To enable this use case, Crashlytics automatically catches (but does not send) crash reports whenever the SDK is present at app launch.

We understand your use case, but it isn't currently on our roadmap to add a feature to dynamically disable Crashlytics in this way. If you really need to circumvent Crashlytics' handling, you could try assigning a new `Thread.UncaughtExceptionHandler` in your app after Crashlytics starts up, before initializing any other crash reporter.

**Comment by hborders** [comment]
But how can I work around NDK crash registration?
