### ISSUE TITLE
Fatal crashes are not sent to console unless setting setCrashlyticsCollectionEnabled(true) 

### ISSUE THREAD

**Issue by alonaviram** [firebase/firebase-android-sdk#2126]
### Describe your environment

  * Android Studio version: 4.1
  * Firebase Component: Crashlytics
  * Component version: 17.2.1

### Describe the problem
migrated from Fabric Crashlytics, don't have any reference when searching for 'Fabric' in the project

Fatal exceptions are not shown on console unless calling `FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true)`

test 1:
adding test crash to `SplashActivity.onCreate()`, trying to run the app twice, app crashes but no crashes are shown on Firebase console.

test 2:
adding test crash to `SplashActivity onCreate()`, and `FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true); on Application.onCreate()`
trying to run the app twice, app crashes & crashes are shown on Firebase console

can't reproduce on a new project. 
will send logs privately if needed

**Comment by gianpaolodn** [comment]
Same issue with version 17.2.2, we were not able to see crashes in dashboard until

FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true)

this option was set in the code. Is not a new app, but old app migrated from fabric.

**Comment by mrwillis21** [comment]
Hi folks - Crashlytics data collection is enabled by default, unless you've specifically disabled it in your `AndroidManifest.xml` (as discussed here: https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#enable-reporting) so I wouldn't expect that you'd need to call that in order to see your crashes. If you can reproduce this, please run `adb shell setprop log.tag.FirebaseCrashlytics DEBUG` and then post the output of `adb logcat -s FirebaseCrashlytics` both for a run where crashes don't show up, and one where they do.

**Comment by charleston10** [comment]
Are you using proguard or dexguard?

**Comment by gianpaolodn** [comment]
I read somewhere it could be a possible cache issue.  That's why we tried and worked.

yes we are using proguard. 

I hope @alonaviram can give you some logs. I can't interrupt my devs right now to produce them.

**Comment by charleston10** [comment]
try this https://github.com/firebase/firebase-android-sdk/issues/1987
