### ISSUE TITLE
Android R8 mergeProjectDex Error

### ISSUE THREAD

**Issue by krcho** [firebase/firebase-android-sdk#2226]
Android Studio version : 4.0.1
Firebase Components 
  ```
  implementation 'com.google.firebase:firebase-analytics:17.5.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.google.firebase:firebase-crashlytics:17.2.1'
    implementation('com.google.firebase:firebase-perf-ktx:19.0.10') {
        // protobuf-lite that firebase-config and Tink depends on.
        exclude group: 'com.google.protobuf'
    }
```
And, BuildScript 
```
buildscript {
    ext.kotlin_version = '1.3.71'
    repositories {
        jcenter()
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.1.0"
        // firebase
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
        classpath 'com.google.firebase:perf-plugin:1.3.4'  // Performance Monitoring plugin
    }
}
```
ProtoBuf versions : 
```
    implementation 'com.google.protobuf:protobuf-javalite:3.11.0'
    protobuf 'com.google.protobuf:protobuf-java:3.11.0'
```
ProtoBuf gradle : 
```
proto
buf {
    // Configure the protoc executable
    protoc {
        // Download from repositories
        artifact = "com.google.protobuf:protoc:3.11.0"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:1.28.0"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { option 'lite' }
            }
            task.plugins {
                grpc {
                    option 'lite'
                }
            }
        }
    }
}
```

Gradle cannot build app correctly.
Error Message : `Type com.google.protobuf.AnyProto is defined multiple times`

without Firebase Performance, It build well.
How to fix it?

**Comment by rlazo** [comment]
Hi @krcho could you post your app's full dependency graph? `firebase-perf` depends on `protobuf-javalite`. My hunch is that you have another dependency that's pulling in `protobuf-lite`, and that's causing the issue.

**Comment by krcho** [comment]
> Hi @krcho could you post your app's full dependency graph? `firebase-perf` depends on `protobuf-javalite`. My hunch is that you have another dependency that's pulling in `protobuf-lite`, and that's causing the issue.

I did check `app dedendency`, 
```
testImplementation 'org.robolectric:robolectric:4.3.1'
testImplementation 'org.robolectric:shadows-multidex:3.8'
```
that two library using protobuf-java. so I delete it. But same result.
`Type com.google.protobuf.Api$1 is defined multiple times` exception

**Comment by krcho** [comment]
```
implementation 'com.google.protobuf:protobuf-javalite:3.11.0'
protobuf 'com.google.protobuf:protobuf-java:3.11.0'
```
I deleted these two dependencies. And Build & Run is well.
then, Should I rely on Firebase's protoBuf version? I cannot use ProtoBuf independently?

**Comment by rlazo** [comment]
Removing these libraries 

```
testImplementation 'org.robolectric:robolectric:4.3.1'
testImplementation 'org.robolectric:shadows-multidex:3.8'
```

didn't affect the build because they are only used when running tests, thus the `test` in `testImplementation`.

If your app itself uses protocol buffers, you can follow the instructions in the README of [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) for Android using protobuf versions above 3.8. It's a good idea to declare the dependency directly instead of relying it coming transitively from Firebase. Most likely you don't need the `protobuf ...` dependency, only the `implementation` one.

Because of how the protobuf library works, all the libraries depending on protobuf need to depend on the same version, otherwise it may fail. See #2158 for an example of how things can go wrong. Right now Firebase depends on 3.11 but we will be migrating to depend on 3.14 soon, to address that issue I mentioned above.

**Comment by krcho** [comment]
remove `protobuf 'com.google.protobuf:protobuf-java:3.11.0'` 
It works well. Thank you!
