### ISSUE TITLE
The message is clicked and redirected to an external browser, and the custom key value cannot get the value

### ISSUE THREAD

**Issue by tibbytang** [firebase/firebase-android-sdk#2489]
I follow the document below：
https://firebase.google.com/docs/in-app-messaging

when I triger a message，When I triggered a message and clicked it, I was redirected to the external browser, and my custom key value did not reach the value.

the sdk version is 
```
 // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:26.6.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
    // Declare the dependencies for the In-App Messaging and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-inappmessaging-display'
```

the google service is 

```
classpath 'com.google.gms:google-services:4.3.4'  // Google Services plugin
```
it is sdk bug?

**Comment by aguatno** [comment]
Hi @tibbytang thanks for reporting. I ran a test, but didn't get the exact behaviour. It would be better for us to troubleshoot this issue if you could provide a [minimum, complete, and verifiable example](https://www.google.com/url?q=https%3A%2F%2Fstackoverflow.com%2Fhelp%2Fmcve&sa=D&sntz=1&usg=AFQjCNFwcq7Sejdz7IFSTp_pnKLUbct2CQ) that I can run locally. The sample code/project should not contain any third-party libraries. Having the sample code/project would help us know where the issue comes from and how it appears. Also, exact and detailed steps to replicate the issue.

 
I'd also suggest you try out our [quickstart](https://github.com/firebase/quickstart-android) for Android. It is a validated implementation of Firebase SDKs, so any issues that persist with this project could indicate that there's a bug in the SDK. You can also use it as a reference and compare with your project.
