### ISSUE TITLE
Always Client is offline! But its not!

### ISSUE THREAD

**Issue by YohanSandun** [firebase/firebase-android-sdk#2630]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.3
  * Firebase Component: Database
  * Component version: 27.1.0

### [REQUIRED] Step 3: Describe the problem

When trying to retrieve data from a database reference, It's always failing with client is offline exception. Not even once I was able to retrieve the data. With my previous app I had the same issue, but when I restart the app I was able to retrieve the data. But now it's always throwing same error. I've tried both 'get()' and 'addValueEventListener()'

#### Steps to reproduce:

When ever try to retrieve data, this occurs,
Log
```
2021-04-29 12:02:52.136 21121-21121/lk.ysk.postagerates D/HwAppInnerBoostImpl: asyncReportData lk.ysk.postagerates,2,1,1,0 interval=95
2021-04-29 12:02:52.388 21121-21121/lk.ysk.postagerates D/HwAppInnerBoostImpl: asyncReportData lk.ysk.postagerates,2,1,2,0 interval=348
2021-04-29 12:02:55.137 21121-21294/lk.ysk.postagerates I/RepoOperation: get for query /groups/A falling back to disk cache after error: Client is offline
```

#### Relevant Code:

```
database = FirebaseDatabase.getInstance();
groupsRef = database.getReference("groups");

groupsRef.child("A").limitToFirst(4).get().addOnCompleteListener(task -> {
    Log.d("AKURUTAG", "onComplete");
}).addOnFailureListener(e -> Log.d("AKURUTAG", "onFailure: " + e.getMessage()));
```

**Comment by aguatno** [comment]
Hi @YohanSandun thanks for reporting. Most of the cases this issue is related with the network or the device, a good way to probe this will be to run the app in a different device and network, that will discard your code or the backend.

If the issue persists, please let me know the Database SDK version you are using. I'll also need you to provide steps on how to recreate the issue, so I know what I'm looking for. Be sure your sample app includes the same versions and reproduces the exact error you are seeing.

Thanks
