### ISSUE TITLE
user properties are not updated quickly

### ISSUE THREAD

**Issue by joshua-ra** [firebase/firebase-android-sdk#2705]
My environment

  * Android Studio version: 4.1.3
  * Firebase Component: Analytics
  * Component version: Latest version

The problem

Client side sequence:
1. update user properties
2. send signin_success event

In firebase:
1. get signin_success event - that time the user properties are not updated
2. update user properties

![Screen Shot 2021-05-28 at 4 45 45 PM](https://user-images.githubusercontent.com/85194020/120379524-e3cf8d80-c2ed-11eb-8bd6-a65beb86a178.png)

So I added delay time(5 sec) for the signin_success event
In this case: working correctly
1. update user properties
2. get signin_success event - that time the user properties are updated

![Screen Shot 2021-05-28 at 12 01 22 PM](https://user-images.githubusercontent.com/85194020/120379498-d87c6200-c2ed-11eb-8c80-59ace707e3f0.png)

It was working correctly but it's not working now days.
The user properties update time takes more than event processing time.

**Comment by aguatno** [comment]
Hi @joshua-ra thanks for reporting. It seems there's a delay in populating the data. Could you file a ticket to [Firebase support](https://firebase.google.com/support)? This way, you can share your project info to the team so that they might help you in troubleshooting your Analytics console further. Thanks.
