### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.FirebaseUser.getUid()' on a null object reference

### ISSUE THREAD

**Issue by derrickrc** [firebase/firebase-android-sdk#2723]
I receive crash reports showing this error on occasion, but I'm not sure how it's possible as it happens in later activities after the user is already logged in. Example code in a later activity that occurs after successful login:

```
        mAuth = FirebaseAuth.getInstance();
        String customerId = mAuth.getCurrentUser().getUid();
```

Should I not be calling `getInstance()` in these cases and instead save `customerId` as a static string to `sharedPreferences` after the initial login? I just don't understand though how the Firebase instance can suddenly go null. After these crashes, the user does not need to log back in either. Thank you.

My gradle:

```
    implementation 'com.google.firebase:firebase-database:19.3.0'
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-firestore:18.2.0'
```

**Comment by aguatno** [comment]
Hi @derrickrc I looked into this issue and it appears to be a code or flow issue, you may check these SO questions regarding this error message ([1](https://stackoverflow.com/questions/45389666/getuid-gives-null-pointer-exception), [2](https://stackoverflow.com/questions/56673641/string-userid-firebaseauth-getinstance-getcurrentuser-getuid-getuid-gi) and [3](https://stackoverflow.com/questions/51919150/my-app-get-crashes-because-of-null-pointer-exception-for-firebaseauth-getuid)), you may try the recommended answer to see if that solved the issue.

Now, you may also try our [quickstart](https://github.com/firebase/quickstart-android/tree/master/auth) to discard a problem with the service, the quickstart has already some sign in flows implemented so it is also a good tool to compare your code to see if something is missing. You may also try to replicate the error you are getting in the quickstart.

If the issue persists, please, share with me more details about it, like if this happens with all your users, if you validate that the user is currently logged in, some screenshots will help a lot to get a clearer view on this behavior.

**Comment by derrickrc** [comment]
Thank you Arel for the quick response, I'll check out these resources.

**Comment by aguatno** [comment]
Hi @derrickrc I'll be closing this out. If the issue persists, just leave a comment and I'll re-open this issue. Thanks
