### ISSUE TITLE
Uncaught exception in Firebase Database runloop (20.0.0)

### ISSUE THREAD

**Issue by MasoomR-Bsw** [firebase/firebase-android-sdk#2733]
### Environment

  * Android Studio version: Arctic Fox | 2020.3.1 Beta 3 
  * Firebase Component: Analytics, Database, Auth, Config, Functions, Invites, Dynamic Links, Ads, InApp Messaging, App Indexing, Messaging, Crashlytics

  * Component version: 
    * Analytics - 19.0.0
    * Database - 20.0.0
    * Auth - 21.0.1
    * Config - 21.0.0
    * Functions - 20.0.0
    * Invites - 17.0.0
    * Dynamic Links - 20.0.0
    * Ads - 20.1.0
    * InApp Messaging - 20.0.0
    * App Indexing - 20.0.0
    * Messaging - 21.1.0
    * Crashlytics - 18.0.0 

### Problem

On production, getting lot of  java.lang.RuntimeException crashes logged on crashlytics / console. 
Crash:
Non-fatal Exception: java.lang.RuntimeException
Uncaught exception in Firebase Database runloop (20.0.0).

Also tried with some older versions of Firebase SDKs, but the problem exists.

#### Steps to reproduce:

It's come on production build, so no step available.

#### Relevant Code:
N/A

**Comment by aguatno** [comment]
Hi @MasoomR-Bsw thanks for reporting this. These kinds of issue are nearly always caused by a dependency conflict in your module resolution. You may try our quickstart to discard a problem with the service, the quickstart its a good tool to compare your code/environment to see if something is missing. You may also try to replicate the error you are getting.

If the issue persists, please, share with me a sample runnable app that can reproduce the issue. This will bring us a better understanding of what is happening. Thanks

**Comment by MasoomR-Bsw** [comment]
@aguatno , please look at this crashes, which also a part of this issue.

> Non-fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
>---- at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
>---- at android.os.Handler.handleCallback(Handler.java:751)
>---- at android.os.Handler.dispatchMessage(Handler.java:95)
>---- at android.os.Looper.loop(Looper.java:186)
>---- at android.app.ActivityThread.main(ActivityThread.java:6513)
>---- at java.lang.reflect.Method.invoke(Method.java)
>---- at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
>---- at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)



And this one also (its comes many times):

> Non-fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@94b1ecc rejected from com.google.firebase.database.v.i0.c$a@6267515[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 116]
>        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
>        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
>        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
>        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
>        at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:654)
>        at com.google.firebase.database.core.Context$1.onSuccess(Context.java:290)
>        at com.google.firebase.database.android.AndroidAuthTokenProvider.lambda$getToken$1(AndroidAuthTokenProvider.java:47)
>        at com.google.firebase.database.android.-$$Lambda$AndroidAuthTokenProvider$RrOSb5RJWdeYq_-Ke5cq8RhbGFA.onSuccess(-.java:4)
>        at com.google.android.gms.tasks.zzn.run(zzn.java:4)
>        at android.os.Handler.handleCallback(Handler.java:883)
>        at android.os.Handler.dispatchMessage(Handler.java:100)
>        at android.os.Looper.loop(Looper.java:237)
>        at android.app.ActivityThread.main(ActivityThread.java:7817)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

**Comment by aguatno** [comment]
@MasoomR-Bsw thanks for the info. I have looked into the error you are encountering and it seems it could be related to some issues with queries as reported by other users in this Stack Overflow [post](https://stackoverflow.com/questions/37724801/uncaught-exception-in-firebase-runloop-3-0-0). At the same post you can see several troubleshooting steps to take in order to deal with this error, If this wont let us find the issue, I will need you to share with me an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)  of your Android Studio Project

**Comment by MasoomR-Bsw** [comment]
Thank you so much for your response.

 It's happening with the latest SDKs, and one of my library using the latest SDK,, after forcefully downgrading the version, problem is now solved.

**Comment by aguatno** [comment]
Thanks for updating! Feel free to comment here if the issue resurfaces and we'll try to help.
