### ISSUE TITLE
Please provide a way to increase the request count for firebase auth!

### ISSUE THREAD

**Issue by mscherer82** [firebase/firebase-android-sdk#2753]
How else should we be able to do research for bugs like this one? https://github.com/FirebaseExtended/flutterfire/issues/5055
For this we need an SMS code sent to the device. It cannot be tested with test numbers and test codes.

**Comment by aguatno** [comment]
Hi @mscherer82 thanks for reporting. It seems you have been blocked because of sending too many Auth requests from a single device or IP address for a given [period of time](https://firebase.google.com/docs/auth/limits#account_creation_and_deletion_limits). These repeated requests are considered as a suspicious behavior which temporarily blocks the device or IP address. 

In case there's no OTP sent to the device I suggest filling a [support ticket ](https://firebase.google.com/support) since they have tools to check if there's something wrong with the carrier.

Also, If you're still in development mode, it is recommended to [whitelist the phone numbers](https://firebase.google.com/docs/auth/android/phone-auth#test-with-fictional-phone-numbers) so that you can run consecutive tests with the same phone number without getting throttled.
