### ISSUE TITLE
AdditionalUserInfo isNewUser always returns false for signInWithCustomToken authresult

### ISSUE THREAD

**Issue by tynchtyk-kaldybaev** [firebase/firebase-android-sdk#2853]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.3
  * Firebase Component: Authentication(Database, Firestore, Storage, Functions, etc)
  * Component version: 19.3.2
  
### [REQUIRED] Step 3: Describe the problem
When signing in with custom token, isNewUser function returns always false.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
firebaseAuth.signInWithCustomToken(token).addOnCompleteListener(OnCompleteListener { task ->
                if(task.isSuccessful) {
                    isNewUser = task.result?.additionalUserInfo?.isNewUser  //Always false, even for newly created users
                    emitter.onComplete()
                }
                else {
                    emitter.onError(task.exception)
                }
            })
```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @tynchtyk-kaldybaev This is a strange behavior. I've been trying to reproduce the same behavior locally, but so far I couldn't have the same results using the quickstart. This project has already been tested and could help us find the source of the issue. You can try to use the firebase quickstart to compare the implementations.
 
Also, in order to have a better insight of the issue, I'll require a MCVE that I can run locally. In this way we might reproduce the same behavior locally and we'll have more information. Here is a [link](https://stackoverflow.com/help/minimal-reproducible-example) with more information about how to create a mcve.
