### ISSUE TITLE
After some time, Cloud Firestore sync stops working

### ISSUE THREAD

**Issue by wujek-srujek** [firebase/firebase-android-sdk#2854]
Both on Android and iOS (same Flutter app), the sync works fine when the application starts and keeps working for some time. However, after some time (not sure how much) sync stops working. When the application is force-stopped and restarted, it starts working again immediately.

This application has been working for month and there have been no code changes since May 19, and it started having issues only recently (maybe a week or so?). Has anything changed in your backend, and is an upgrade of all the libraries necessary?

**Comment by wu-hui** [comment]
Hey @wujek-srujek 

Sorry for the late reply. I do not know any change that would lead to this. Given that this happens to both Android and iOS for you, it might be an issue with the flutter plugin. You can report the issue here: https://github.com/FirebaseExtended/flutterfire/issues

It might still be an issue with backend or underlying SDKs, if you believe so, please give us more details on how to reproduce:

* Version of flutter plugin?
* Does this happen with a very basic app, or you need to do something in the app to make it happen? If it is the latter, a mini-repro is much appreciated.

**Comment by wujek-srujek** [comment]
In the meantime I upgraded everything and will monitor if it still occurs. You are right, I should have created the issue for the Flutter version, sorry for this. I will close this one and if the issue persists, I will open a new one there.
