### ISSUE TITLE
GCM:      broadcast intent cancel,can't receive notification

### ISSUE THREAD

**Issue by LcTerry** [firebase/firebase-android-sdk#2917]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: ___4.1__
  * Firebase Component: com.google.firebase:firebase-messaging:21.1.0
  * Component version: 21.1.0

### [REQUIRED] Step 3: Describe the problem
go to Settings  force stop my app or enter recents to kill my app, then can’t receive the notification from the firebase console .

messages can be received quickly when the application is running.

from the logcat for all main log has this print:
08-18 16:38:31.978 16600 16600 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=cn.jiguang.junion.jpushtestdemo (has extras) }

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by zwu52** [comment]
@LcTerry 
Thanks for reporting. 

Unfortunately, when an app is force stopped, it opts our from receiving GCM broadcast. Now GCM will make several attempts to redelivery if the app is registered in GMSCore by checking the state of the app. If retries were all blocked due to force-stop state, the message will be dropped.   

This types of issues are frequently seen on OEM devices where aggressive battery optimizer are implemented.

**Comment by LcTerry** [comment]
I find some code in ams：
when we sendbroadcast ,this api broadcastIntentLocked() in ams has always intent.addFlags(Intent.FLAG_EXCLUDE_STOPPED_PACKAGES) to exclude stopped packages. 

Can gcm broadcast   intent.addFlags(Intent.INCLUDE_STOPPED_PACKAGE) before sendbroadcast to increase delivery rate.

**Comment by zwu52** [comment]
Greg could you chime in on the rational for the decision on not invoking  force stop apps?

**Comment by gsakakihara** [comment]
Force stopping an app (from the Settings menu) is intended as a signal that the user doesn't want the app to start again unless it's explicitly started by the user. Unfortunately, as you have seen, some devices force stop apps under other circumstances that the user may not have expected or wanted to be put into the stopped state. Since there's no way for FCM to know if an app has been stopped by the user directly or in some other way, FCM doesn't include FLAG_INCLUDE_STOPPED_PACKAGES in FCM broadcasts to respect the intent of the stopped state to not start the application. The team is aware of the issue, though, and continues to explore solutions to the problem.
