### ISSUE TITLE
Pending write operation in Firestore

### ISSUE THREAD

**Issue by Hussienfahmy** [firebase/firebase-android-sdk#2985]
## What feature would you like to see?
Disabling pending operations in firebase-android-sdk cloud firestore

to be able to disable that firestore queue the write operations when the device is offline and push them to the server when back online
in my case I want to execute code after success of the write operation, the user request a write operation when offline then close the app so after back online to the app the write operation sent to the server without execute my code after success of the operation.

## How would you use it?
With any way, the importance is that this functionality is exists 
maybe from the code in the library or as a switch in the project setting or in security rules to reject them
Really any way will be helpful

**Comment by nkhandwe** [comment]
Please help me I am new to github and I want to contribute on open source projects

**Comment by Hussienfahmy** [comment]
Sure, how I can help you?

**Comment by thebrianchen** [comment]
@Hussienfahmy If you want to wait for your your offline writes to complete, you can use [waitForPendingWrites](https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FirebaseFirestore#waitForPendingWrites()). In your particular case, if you want to wait for writes made while the user was offline to resolve before executing other logic, you can wait for the `Task` returned by `waitForPendingWrites()` to complete.

I'm going to mark this issue as closed since this feature already exists, but feel free to as any other questions you may have!

**Comment by Hussienfahmy** [comment]
`waitForPendingWrites()` as you mentioned waits for the writes made while user is offline, BUT what am looking for is cancel the writes made while the user offline, How I can do that if this feature exists ?

**Comment by Hussienfahmy** [comment]
@thebrianchen

**Comment by Hussienfahmy** [comment]
I don't think a submitting a new issue I a good action to get a reply 🙁

**Comment by thebrianchen** [comment]
@Hussienfahmy Apologies for the delayed response! Unfortunately, this is not something that the Firestore SDK supports at this time. 

Can you please file an issue with our official feature request list https://issuetracker.google.com/savedsearches/5337669?
