### ISSUE TITLE
Firebase Installations error log in Dynatrace

### ISSUE THREAD

**Issue by luangs7** [firebase/firebase-android-sdk#2997]
### **[READ] Step 1: Are you in the right place?**
Issues filed here should be about bugs in the code in this repository.
If you have a general question, need help debugging, or fall into some
other categories use one of these other channels:

For general technical questions, post a question on StackOverflow
with the firebase tag.
For general Firebase discussion, use the firebase-talk
Google group.
For help troubleshooting your application that does not fall under one
of the above categories, reach out to the personalized
Firebase support channel.

### **[REQUIRED] Step 2: Describe your environment**
Android Studio version: 4.1.1
Firebase Component: Config, Messaging, Crashlytics, Analytics
Component version: com.google.firebase:firebase-bom:26.7.0

### [REQUIRED] Step 3: Describe the problem

We are using Dynatrace to log some problems in our application.
In this case, the snippet below is a log from Dynatrace about some devices
My question is: Is it an implementation error on application's side? Or its nothing that we can do about it?
Just because this logs are tracked and they want some explanation or fixes about it, but we don't know where to start.

```
Time
1.18 s
Response
javax.net.ssl.SSLPeerUnverifiedException: Hostname firebaseinstallations.googleapis.com not verified: certificate: sha1/_hashkey_ DN: CN=aaaaaaaaab.me,OU=Domain Control Validated subjectAltNames: [aaaaaaaaab.me, www.aaaaaaaaab.me]
Provider
google.com
URL
https://firebaseinstallations.googleapis.com/v1/projects/_apppackage_/installations
```

**Comment by aguatno** [comment]
Hi @luangs7 The error logs seem to be a little too broad to tackle. If I could reproduce the problem here, we can have a better look into it

Also try to use our [quickstart](https://github.com/firebase/quickstart-android) app with the latest SDK version to see if you're able to reproduce the issue. If not, then it's likely just an implementation error, and I would recommend that you cross-check your code implementation with the quickstart app to verify if anything is missing in your configuration.
