### ISSUE TITLE
Dynamic links are being replayed on android activity recreation, if cold started via link

### ISSUE THREAD

**Issue by ursusursus** [firebase/firebase-android-sdk#3009]
* Android Studio version: 2020.3.1
  * Firebase Component: Dynamic links
  * Component version: 20.1.1

Dynamic link get replayed on orientation change.

```
class MainActivity : AppCompatActivity {
	override fun onStart() {
        super.onStart()

        Log.d("Default", "# ON START")
        FirebaseDynamicLinks.getInstance().getDynamicLink(intent)
            .addOnSuccessListener { data: PendingDynamicLinkData? ->
                Log.d("Default", "dynamiclink=${data?.link}")
            }
            .addOnFailureListener {
                Log.d("Default", "err=$it")
            }
    }
}
```

The usual basic sample. If I rotate the phone for example, the activity get recreated and the `data.link` is never null, as if it didn't get cleared or something.

**It only manifests when the process was not running before and the link started the process.**
If the process was already running, and the link was clicked, then upon rotation, link is null, as should.

Workaround is to call `intent.removeExtra(FirebaseDynamicLinksImpl.EXTRA_DYNAMIC_LINK_DATA)` but this for sure cannot be intended usage

**Comment by aguatno** [comment]
Hi @ursusursus Thanks for reporting. I actually cannot reproduce this myself. Can you help out with sharing a mini-repro that I can try out?

Thank you.

**Comment by ursusursus** [comment]
Do you have some play services credentials I could use?

**Comment by eldhosembabu** [comment]
I believe this is working as expected.  As long as the passed on intent contains data with respect to an FDL, the FDL SDK will try to resolve it and return.

When the activity is restarted because of an orientation change, i believe the intent which started the activity before will be passed in again and if you call the FDL SDK with that intent, it will resolve the PendingDynamicLinkData for you. From the FDL SDK we are not removing/mutating any data in the passed on intent and is up to the developer to bypass the call to FDL SDK in the case of an orientation change or anything similar which would make the activity to restart.

You could use the [onSaveInstanceState](https://developer.android.com/reference/android/app/Activity#onSaveInstanceState(android.os.Bundle)) to save the info related with activity restarting and retrieve the same in oncreate to determine whether to call the FDL SDK.

**Comment by ursusursus** [comment]
Thats atleast inconsistent design, because if the activity was just paused, then link is clicked, then activify resumed, link resolved as should; now after orientation change the link is not replayed

Which is makes sense with your explanation, but is atleast unexpected (and a propec clearing public api would be nice)

**Comment by eldhosembabu** [comment]
Are you suggesting to have an FDL api for cleaning up the the intent so that 3p developer can make a call and remove the FDL related data in the intent?
