### ISSUE TITLE
Firebase gradle plugin apply order depends on other plugins

### ISSUE THREAD

**Issue by dsvoronin** [firebase/firebase-android-sdk#3022]
### Describe your environment

  * Android Studio version: doesn't matter, reproducible in console
  * AGP version: 7.0.2
  * Firebase Component: Firebase crashlytics gradle plugin
  * Component version: 2.7.1
  * [Google services plugin](https://github.com/google/play-services-plugins) version: 4.3.10

### Describe the problem

Applying `com.google.firebase.crashlytics` plugin depends on some other plugins applying order.

#### What's wrong?

I can't see the source code, but seems like firebase gradle plugin eagerly calls [`PluginContainer`](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginContainer.html) to find already applied `google services` or android plugins.

**This could be confusing for users and makes configuration harder on user side.**

_It could be avoided by using gradle `plugins.withId`/`plugins.withType` API, like @LouisCAD already suggested in https://github.com/firebase/firebase-android-sdk/issues/2721#issuecomment-862574176_

#### Steps to reproduce:

Apply `com.google.firebase.crashlytics` before either android or google services plugin.

Example of errors/warnings:
- `Crashlytics was applied to a project without an Android plugin. Please make sure the Crashlytics plugin is applied after the appropriate Android plugin for your project.'`. But it's applied.
- `Crashlytics could not find Google Services plugin task: processReleaseGoogleServices. Make sure com.google.gms.google-services is applied BEFORE com.google.firebase.crashlytics. If you are not using the Google Services plugin, you must explicitly declare googleServicesResourceRoot inputs for Crashlytics upload tasks.` but it's applied too

Related: 
- https://stackoverflow.com/a/67995305/981330

**Comment by aguatno** [comment]
Hi @dsvoronin thanks for reporting. I agree that this could cause unexpected issues if crashlytics plugin is out of place. With this, we've filed a feature request to explicitly mention in the documentation that the plugin order is important (bug#192673168). We'll also take note of using plugins.withId. Thanks.

**Comment by mrichards** [comment]
Hi @dsvoronin, we recently shipped version 2.8.1 of the Crashlytics Gradle plugin, which defers most of the plugin initialization to an `afterEvaluate` block, which should allow the plugins to be applied in any order. It also allows the Crashlytics plugin to be declared via the `plugins {}` DSL block rather than the `apply: ...` call.

**Comment by dsvoronin** [comment]
Thanks @mrichards for letting me know
But why did you choose `afterEvaluate`? Any particular reason not to go with `plugins.withType/withId<AGP>`?

**Comment by mrichards** [comment]
@dsvoronin I just looked at the change and we needed to do both. (Well, we used `project.pluginManager.withPlugin(...) `, not `withType` or `withId`.) Only a small part is in the `afterEvaluate` block, and I believe it was due to the way that previous versions of the `google-services` plugin registered tasks. We may be able to reduce to only `withPlugin` calls moving forward.

**Comment by dsvoronin** [comment]
I think documentation at https://firebase.google.com/docs/crashlytics/get-started?platform=android should be also updated?
To encourage users to use `plugins` block and imperative `apply` only as a fallback if needed

**Comment by mrichards** [comment]
Yes, we'll be updating the docs for all Firebase Gradle plugins soon!
