### ISSUE TITLE
Image Download Failure in In App Messages

### ISSUE THREAD

**Issue by j1c1m1b1** [firebase/firebase-android-sdk#3041]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 2 Build #AI-203.7717.56.2031.7678000, built on August 26, 2021
  * Firebase Component: In-App Messages
  * Component version: 20.1.0

### [REQUIRED] Step 3: Describe the problem

Whenever I have an In-App Message configured with an image, I get the following error log when trying to display the message:
```
Load failed for https://cataas.com//cat?type=sq with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
Image download failure
```

The In-App Message is never displayed

#### Steps to reproduce:

* Compose a new campaign for In-App Messages
* Add an image URL
* Trigger an event to receive an In-App Message with the function `triggerEvent`

#### Relevant Code:

```kotlin
FirebaseInAppMessaging.getInstance().triggerEvent("example_event")
```

**Comment by j1c1m1b1** [comment]
* Please find the compile-time and runtime dependencies for the build variant of the project [here](https://ufile.io/z88vbpio)
* The relevant error logs have already been shared in the issue, [here](https://ufile.io/lab6vwvk) is the dump filtered by the project package, related to the Fragment that is triggering the IAM.
* More info about the project:

```properties
androidCompileSdkVersion = 30
androidBuildToolsVersion  = 30.0.2
androidMinSdkVersion = 23
androidTargetSdkVersion = 30
```

* I'll try to create a sample project, but since this issue is probably caused by some dependency I'm guessing the sample project will work properly. I will try regardless.

**Comment by argzdev** [comment]
Hi @j1c1m1b1, thanks for the information and apologies for the late reply. Are you still encountering this issue?

I still can't seem to reproduce this issue, I tried testing this with glide dependency, but there's still no conflict. All I can think of is that since this is a dependency issue, it might based only on a specific version. 

May I know which version of Glide are you using?
By the way, were you able to create a sample project of the issue?
Also does this issue always occur or does the occurrence of this issue not consistent?

**Comment by j1c1m1b1** [comment]
Hi @argzdev We recently did an update of all or project dependencies and we haven't tested the issue in a while. I'll re-test and come back to you.

**Comment by argzdev** [comment]
Sure @j1c1m1b1, feel free to respond once you get an update. Thanks!

**Comment by j1c1m1b1** [comment]
Hi @argzdev unfortunately the error keeps happening and it is 100% reproducible. It happens all the time the IAM contains an image.

I haven't been able to create a sample project (because of time constraints).

The Glide version we are using is: `4.12.0`

**Comment by argzdev** [comment]
Hi @j1c1m1b1, thanks for getting back to me with the details. I'll try to investigate this further.

**Comment by argzdev** [comment]
Hi @j1c1m1b1, I still can't reproduce the issue. 

For what it's worth, here are my investigations.
- Firebase messaging succeeded since it was able to retrieve the link (e.g. https://cataas.com//cat?type=sq), so the main issue is pointing to Glide dependency inside Firebase messaging. 
- The log shows that `with size [-2147483648x-2147483648]` pointing out that the image size is `INT_MIN` meaning it was not retrieved properly by Glide. (e.g. download failure, or corrupted image)
- Assuming the image is never corrupted, then the issue `Image download failure` would only be caused by either intermittent internet connection (which shouldn't be the case if you're able to recreate the issue every time) or low memory on device storage. At this point, I can't think of any other more ideas which can cause the download to fail.

For now, I'll just wait for the sample project repro with the issue to investigate this further. Thanks.
