### ISSUE TITLE
orderBy case insensitive if the field is String

### ISSUE THREAD

**Issue by MihailsKuzmins** [firebase/firebase-android-sdk#310]
## What feature would you like to see?
Would it be possible to provide a parameter to order by strings using the case-sensitive and case-insensitive approach if the queried field is of type String ?

## How would you use it?
I would use it in the "orderBy" clauses, e.g.
Function<Query, Query> query = x -> x
    .orderBy("stringAttribute", Query.Direction.DESCENDING, StringComparison.CaseInsensitive);

Function<Query, Query> query = x -> x
    .orderBy("stringAttribute", StringComparison.CaseSensitive);

**Comment by samtstern** [comment]
@MihailsKuzmins thanks for the feature request!  Right now with the way our indexes work, this would be very challenging and is not on our roadmap.  We are investigating full text search solutions for Firestore which would enable case-insensitive searching (and much more), but I don't think our plans there include changing the behavior of `orderBy`.

In any case, this change would be pretty large and is unlikely to come soon.  I would suggest using a second field like `stringAttribute_lower` to store a copy of the field in a case-insensitive way so that you could then query on that field.  You could create a Cloud Function that updates that field any time the `stringAttribute` field is updated.

```js
{
   // ...
   stringAttribute: "My NaMe is SaM",
   stringAttribute_lower: "my name is same"
}
```

Since it would not be possible to solve this issue in the Android SDK and it's not on our roadmap yet, I am going to close this issue.  If you feel passionately about this feature coming to the Firestore backend you can file a feature request in the main issue tracker here:
https://b.corp.google.com/issues/new?component=530136&template=0
