### ISSUE TITLE
[Firestore] Ability to access createTime and updateTime properties

### ISSUE THREAD

**Issue by ebhsgit** [firebase/firebase-android-sdk#3107]
## What feature would you like to see?

Ability to access the document `createTime` and `updateTime` property in `DocumentSnapshot`

## How would you use it?

```
val snapshot: DocumentSnapshot
snapshot.createTime
snapshot.updatetime
```

## Context

It is sometimes useful for the developer to be able to access when a document is created or last updated.

Both `createTime` and `updateTime` properties can currently be accessed in cloud functions via firebase.admin
https://googleapis.dev/nodejs/firestore/latest/DocumentSnapshot.html

Similarly, on client app, they can be access via RPC
https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#document

**Comment by argzdev** [comment]
Hi @ebhsgit, thanks for reporting. Since this is a feature request, we'll just leave this ticket open until sometime this is worked on. I can't provide any specific timeline as to when this will be prioritized, but you may keep an eye out on our [release notes](https://firebase.google.com/support/releases) and [official blog](https://firebase.googleblog.com/) from time to time to check out the latest features.

**Comment by ehsannas** [comment]
Thanks for the suggestion @ebhsgit . Since the mobile clients provide a latency-compensated view of the documents in the database (which makes it possible for users to continue to use Firestore while offline), it is not appropriate to expose these properties. For instance: imagine a document that was created/updated while the client was offline. Depending on the developer's specific use-case, the developer may want to choose to use the timestamp when the document was created (when the user was offline), or they might want to use the timestamp when the document was stored in the backend (when the user came back online).

It _does_ make sense to access these properties on the server SDK (e.g nodejs) and via RPCs as it is always guaranteed to be online and getting the information from the backend.

**Comment by ebhsgit** [comment]
Thanks for the reply @ehsannas 

In my opinion it would be useful to expose the created/updated fields, and clarify that these are ServerTimestamp via documentation. In this way it is in alignment with the other APIs, and will satisfy at least one of the 2 scenarios out of the box.
