### ISSUE TITLE
[Firestore] duplicate entry issue when using google/type proto files 

### ISSUE THREAD

**Issue by chemouna** [firebase/firebase-android-sdk#3109]
Hi, this is more of a question, we're using firestore in our android app, and using protobuf for the app's server-client communication,  google/type proto files are bundled with our backend proto files that we fetch and generate models for, we're also using wire ([https://github.com/square/wire](https://github.com/square/wire)) to generate models (and not protoc). 

the problem i'm running into is that `protolite-well-known-types`  (by including a dependency that bundles google/type) contains the same google/type proto files and as a result when building a release variant i get a duplicated class issue from google/type proto classes. 

this issue is fixed with:

```kotlin
implementation(Deps.Firebase.firestore) {
  exclude(module = "protolite-well-known-types")
}
```

but i want to make sure that won't break firestore usage, we're only using firestore to get real time updates from a collection and do some custom logic using the ids we get from this and nothing else. 

so wanted to know what does firestore use `protolite-well-known-types` for ? and is it fine to exclude this dependency if i'm only using firestore for the use case above.

also if there's a better approach to solve this problem i can try it.

**Comment by argzdev** [comment]
Hi @chemouna, thanks for writing. For an explanation what and why we used protolite-well-known-types, you could check out the README section [here](https://github.com/firebase/firebase-android-sdk/tree/master/protolite-well-known-types), since the explanation here is well detailed. As for whether or not this will break any firestore usage, I'll ask our engineers to confirm, and get back to you once I get a reply.

**Comment by argzdev** [comment]
Hi @chemouna, apologies for the late response. Our engineers said that as long as you can read and write documents then it means that our Proto layer was initialized correctly. Your team should know why they have two versions in their namespace and if those are compatible or generated by different Proto compilers. And in your case, since you were able to read/write documents properly, then I think this should be alright.

**Comment by argzdev** [comment]
Since this has been answered, I'll be closing the ticket now. If you have any other questions, feel free to open a new ticket. Thank you!
