### ISSUE TITLE
[Crashlytics] libcrashlytics-common.so crashed

### ISSUE THREAD

**Issue by tuancoltech** [firebase/firebase-android-sdk#3113]
Hi,
So we have a crash reported in our console which I believe belongs to Crashlytics SDK.
The backtrace is as below:

![Screen Shot 2021-11-09 at 09 14 08](https://user-images.githubusercontent.com/4281969/140849203-76ad18ef-b784-44b2-9b91-ff3e4f115008.png)

We are using `firebase-crashlytics-ndk:18.2.3` with `Crashlytics ANR` enabled.
Android OS: 100% Android 11 so far.

Please take a look.
Thanks.

**Comment by argzdev** [comment]
Hi @tuancoltech, thanks for reporting. I'll try to check and see what I can find.

**Comment by tuancoltech** [comment]
> Hi @tuancoltech, it looks like ANRs are only captured if the Crashlytics Android SDK is version 18.2.4+ and if the users' device is running Android 11+. Could you try using the latest version and see if this fixes the issue?

Hello @argzdev , 

No, ANRs can already be captured from version `18.2.3+`.
Also, from the above backtrace, it's a crash so I don't know how it's related to ANR here?

**Comment by argzdev** [comment]
Hi @tuancoltech, thanks for getting back to me. Do you mean to say your app was able to capture ANRs from version 18.2.3? Since our docs mentions that this is captured on 18.2.4 above, maybe we need to update this if necessary. 

As for the backtrace, since the ANR feature was just recently released, I was assuming the crash was somewhat related to the release. But since this issue is more pointed towards as a backend issue compared to a code related one. Could you file a ticket via our [Firebase support channel](https://firebase.google.com/support) so the backend team can take a look at your project's logs? They'll be able to investigate this deeper and give a better resolution.

With that said, I'll be closing this ticket for now. Feel free to add if you have any other questions. Thanks.
