### ISSUE TITLE
PersistedInstallation file content is not encrypted

### ISSUE THREAD

**Issue by Muruga66** [firebase/firebase-android-sdk#3117]
When we open / rooted our Android app, we found below:

File with name PersistedInstallation.W0RFRkFVTFRd+MTo3MTM2MzQ5xxxxNjphbmRyb2lkOmU4MGFhNjJhN2IxMDc2MXXXZTQyMGQ.json
is found with content:

Is there any breach that can be possible with Is this encrypted information? Will it compromise our firebase account

**Comment by Muruga66** [comment]
Referring to below thread https://github.com/firebase/firebase-android-sdk/issues/1822

Is there any new findings on this ?

**Comment by argzdev** [comment]
Hi @Muruga66, thanks for reporting. As per checking with the internal effort tracked in b/161510321. It was discussed with the security review and analysis, they do not see this a vulnerability as access to these tokens presupposes the device is already compromised. It was also confirmed by the engineers that no data is leaked by exposing the tokens.

**Comment by argzdev** [comment]
Just to add, this ticket was recently double checked and confirmed that there is no additional vulnerability here since the tokens cannot be used to exfiltrate anything that device file system access would not already grant. With that said, I'll close the ticket for now. Feel free to ask if there are additional questions. Thanks!
