### ISSUE TITLE
DataSnapshot - Method for getting List of DataSnapshot

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/firebase-android-sdk#326]
## What feature would you like to see?

Firestore `QuerySnapshot` has a method `getDocuments()` which returns `List<DocumentSnapshot>` i.e. List representation of `DocumentSnapshot`.

Just like that, I would like to suggest that we can implement the same feature in Firebase Real-time Database. There is a `DataSnapshot` which has method `getChildren()` which returns `Iterable` element. 
We can also add a method like `getSnapshots()` which will return `List<DataSnapshot>` which will be very useful rather than `Iteratable`.

## How would you use it?

We can use this feature in many ways.
One of the main need came here in [`FirebaseDataSource`](https://github.com/firebase/FirebaseUI-Android/blob/version-4.4.0-dev/database/src/main/java/com/firebase/ui/database/paging/FirebaseDataSource.java). While working on List of DataSnapshot.
Here we wanted to pass the `List` of DataSnapshot. For that, we required to Iterate it from first to the last child and then added to the List. Also, there we want to skip the first Child of DataSnapshot. Then we skipped first by calling `next()` first and then iterated to last.
If there is a method in `DataSnapshot` which returns `List<DataSnapshot>` then such operations becomes easy to handle.

Can we do this?

**Comment by samtstern** [comment]
@mikelehen do you know the reason why the method returns an `Iterable` in the first place rather than a `List` or some other collection type.

**Comment by mikelehen** [comment]
@samtstern It's more efficient for us to return an Iterable (which can just iterate over our internal data structure) rather than a List<> that we have to materialize in memory.

@PatilShreyas This is a totally reasonable suggestion (thanks!) but unfortunately we're focusing our engineering efforts on the Firestore SDK and so we're not adding new APIs for the Realtime Database SDK. Sorry I don't have a better answer, but I'm afraid you'll need to stick with your workaround of iterating over the children and making your own List<>.  Sorry for the inconvenience!

**Comment by PatilShreyas** [comment]
Okay!
Thanks for the response!
