### ISSUE TITLE
An ANR issue occurred after upgrading Firebase to BoM 29.0.3.

### ISSUE THREAD

**Issue by shomin1983** [firebase/firebase-android-sdk#3288]
[REQUIRED] Step 2: Describe your environment
Android Studio version: Arctic Fox | 2020.3.1 patch 1
Firebase Component: Firebase BoM
com.google.firebase:firebase-analytics
com.google.firebase:firebase-perf
com.google.firebase:firebase-appindexing
com.google.firebase:firebase-dynamic-links
com.google.firebase:firebase-crashlytics
com.google.firebase:firebase-crashlytics-ndk
Component version: 29.0.3
[REQUIRED] Step 3: Describe the problem
The ANR:
executing service [My package name]/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService
com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService

And there's no "Stack trace" info for this ANR.
The attached images are all the info we have.

Steps to reproduce:
We cannot reproduce.

Actually, we doubted about WorkManager in the beginning. So we tried to change the version of
"androidx.work:work-runtime" from 2.5.0 to 2.7.0, but still got the same ANR in the Play Console.

Relevant Code:

```
Old firebase versions:
    firebaseCoreVersion = '18.0.3'
    firebasePerfVersion = '19.0.9'
    firebaseConfigVersion = '19.2.0'
    firebaseAdsVersion = '18.2.0'
    firebaseAppindexingVersion = '19.1.0'
    firebaseMessagingVersion = '20.3.0'
    firebaseDynamicLinkVersion = '19.1.0'

Current firebase: BoM 29.0.3
```
![1](https://user-images.githubusercontent.com/35989928/148190668-b8fbc8c2-caf6-4bcc-9825-95abfd00ff71.jpg)
![2](https://user-images.githubusercontent.com/35989928/148190680-93f7bc76-4f25-4b5c-8fe5-c223fbc45aa6.jpg)

**Comment by argzdev** [comment]
Hi @shomin1983, thanks for reporting. We'll investigate this and see what we can find.

**Comment by argzdev** [comment]
Hi @shomin1983, I noticed that the old versions of your products is around Firebase BoM version (25.11.0) except for `firebaseCoreVersion`, I compared it using our Firebase release notes [here](https://firebase.google.com/support/release-notes/android#compare-bom-versions). 

Since multiple products are involved, what we could try is narrowing down the scope where the ANR was first encountered. This may be a long shot, but I have two ideas in mind:

- You could try increasing the BoM version from your previous stable version (around 25.11.0) up until where it starts experiencing ANR, then we can note which BoM version started experiencing the ANR. 
- Or you could try using the old version of each product with no BoM, and use the latest version for a specific product on every release to see if which product on the latest version experiences the ANR. For me, this seems like a better approach since it will allow you to do damage control at the same time know which product is producing the ANR issue instead of the former approach that only shows you which BoM version the issue lies.
