### ISSUE TITLE
Device Properties reporting to Firebase

### ISSUE THREAD

**Issue by roberto-sartori** [firebase/firebase-android-sdk#3334]
Hi,

We are working on a project that includes an Android application and Android 10 on a custom hardware.
The application is developed using Android Studio and it includes Firebase.

We don't have issues tracking the devices from the Firebase Dashboard, however we have some problems with certain attributes, in particular:
- Device Model appears as (not set)
- Screen Resolution appears as (not set)
- Device Category appears as mobile, when it should be tablet.

To debug the issue, we followed the instructions to enable debug on Firebase (https://firebase.google.com/docs/analytics/debugview) and from the local adb log we can see that the ‘device_model’, for example, is correctly reported as ‘Device Model’ ('Device Model' is the correct device model in this example) by Firebase. On the Web Dashboard however, the device model is not reported at all ('not set').

So:
- Can you provide information on how Firebase fetch this information from the device (e.g. Android API? Android properties?)?
- Locally some data are correct (e.d. device_model) but they are not visible on the Dashboard. Do you have any idea on this?

Thank you, and let me know if you need more information.

**Comment by roberto-sartori** [comment]
Hi all, any news on this?

Thanks!

**Comment by argzdev** [comment]
Hi @roberto-sartori, sorry for the delayed response. It looks like your issue is most likely on the backend side, that being said, could you file a report including your question to our [Firebase support](https://firebase.google.com/support)? This is so that our Analytics specialist will be able to help and assist you better since they have visibility on your project details. That being said, I'll be closing this issue now. Thanks!
