### ISSUE TITLE
App crashes on start when using Firebase In-App Messaging on Android 11

### ISSUE THREAD

**Issue by shumidub** [firebase/firebase-android-sdk#3409]
Issue is still reproducing with com.google.firebase:firebase-inappmessaging-display:20.1.1 - https://github.com/firebase/firebase-android-sdk/issues/2642

**Comment by argzdev** [comment]
Hi @shumidub, thanks for reporting. It looks like this issue might not be due to gRPC, since it has been updated to the version `1.41.0` and the issue is still experienced.

I'm unable to repro this issue due to this issue being device specific. 
Let's keep this ticket open for now in case our engineers might have an idea what the issue is. Feel free to add any questions or extra information. Thanks!

**Comment by argzdev** [comment]
Hi @shumidub, just bumping this issue. Are you still able to encounter this issue on the latest version `20.1.2`? I do have a few follow up questions if you don't mind.
1. Is the issue reproducible on other devices? Or is it device specific?
2. Are you able to reproduce this issue consistently? If yes, could provide a minimal repro of the issue?

Thanks!
