### ISSUE TITLE
Failed to retrieve data from cache in offline mode - Flutter 

### ISSUE THREAD

**Issue by swarupa-v** [firebase/firebase-android-sdk#3577]
In my application, when application is offline I insert data which I assume it goes in cache. As soon as it is inserted I do a fetch call to retrieve data but latest data inserted is not retrieved. This happens only in Android. Any help or suggestion would be appreciated.

Following packages used: cloud_firestore: ^3.1.9
firebase_analytics: ^9.1.2
firebase_crashlytics: ^2.5.3
firebase_performance: ^0.8.0+7
Flutter vesrion:
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

The issue is when there is no internet connectivity and I insert data in cache and after few seconds I try to retrieve that same inserted data from cache i dont get any values.

**Comment by argzdev** [comment]
Hi @swarupa-v, thanks for reporting. It looks like this issue is similar to #3528. 

Our engineers have created and merged a fix for this, but I can't promise any timeline to when this will be released. In the meantime, a workaround would be to downgrade com.google.firebase:firebase-bom to 29.0.3 (this would be version 24.0.0 in com.google.firebase:firebase-firestore) or lower in Android. For Flutter, you could check what the equivalent version of  this in flutterfire -  cloud_firestore.

That being said, I'll close this now. Thanks!
