### ISSUE TITLE
Any updates on issue 3239?

### ISSUE THREAD

**Issue by casolorz** [firebase/firebase-android-sdk#3593]
Any updates on issue [3239](https://github.com/firebase/firebase-android-sdk/issues/3239)? I can't comment there. 

I have the exact same ANR on `com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService`

I also have no stack trace. 

I'm using firebase-config 19.0.2
Crashlytics 18.9.2
Analytics 20.0.0

Thanks.

**Comment by argzdev** [comment]
Thanks for reporting, @casolorz. I noticed you're using an older version of  `com.google.firebase:firebase-config` and `com.google.firebase:firebase-analytics`. Could you try using the latest version and see if that fixes the issue? Also may I ask what stable version were you previously before you experienced this issue?

**Comment by casolorz** [comment]
I'll make a release with the latest version to see if it helps. I don't know when it started happening, the Play Store Console only goes back 60 days and it appears to be have been there 60 days ago.

**Comment by argzdev** [comment]
Thanks @casolorz. Unfortunately, issues like these go stale due to the nature of it being difficult to reproduce, hence difficult to investigate. So we try to narrow down the gap where the issue began happening, maybe that'll give us an idea where to begin looking.

Anyway, let's keep this issue open for now in case some of our engineers have an idea of the issue, or when you or other developers have updates regarding this.

**Comment by casolorz** [comment]
Unfortunately there is no stack trace on the Play Store console associated with his ANR. I did make a release with the latest of every firebase library and that did not resolve the issue.

Are you able to share what the scheduled job does? Maybe that would shed some light as to what the app might be doing at the time.

**Comment by argzdev** [comment]
Hi @casolorz, thanks for the response. Upon investigation, it looks like there are some similar issues #3066 & #2566. In both scenarios the issue was not related to Firebase, but rather UI changes were being executed on the background thread which causes ANR. Could you check if this is the same case as yours? 

Given that we don't have much detail how the ANR is experienced or what steps to repro the issue, I'm unsure what/which scheduled job caused this issue.

**Comment by casolorz** [comment]
Sorry, I was on vacation and just got back. 

Updating to the latest versions did not help. I still have the issue. 

It could very well be the other actions from other parts of the code are causing this ANR. This is why I was asking what the job does to see if I could figure out what the code might be doing at that time.
