### ISSUE TITLE
Error on registration: FIS_AUTH_ERROR

### ISSUE THREAD

**Issue by MatthewCodes** [firebase/firebase-android-sdk#3630]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

This is about a bug

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 4.1.1
  * Firebase Component: messaging, push_notification, firebase-iid. .firebase:firebase-auth, inappmessaging, inappmessaging-display
  * Component version: bom 29.3.0

### [REQUIRED] Step 3: Describe the problem

When I run my application directly from android studio there is no problem. However, when I upload my aab file to the google play console and users download it they get the following error: FIS_AUTH_ERROR (error on registration) 

Things I've tried that haven't worked:
Changing the API key from Android to Web (web has no restrictions) 
Using implementation platform('com.google.firebase:firebase-bom:29.3.0') to avoid old firebase packages

Has anyone also encountered this issue where all the firebase services work properly in the IDE but when you download it from the store nothing works?

**Comment by argzdev** [comment]
Hi @MatthewCodes, thanks for reporting. Any error logs you can share with us? 

Not sure, but this is the first I've heard of Firebase services not working when uploaded from the store. Have you uploaded your SHA1 based on your release keystore certificate? Also have you after that, have you downloaded and updated your `google-services.json`?

**Comment by MatthewCodes** [comment]
@argzdev My google-services.json is the latest version from the play-store. I'm not sure if I uploaded my SHA1 how can I double check this?

**Comment by argzdev** [comment]
Hi @MatthewCodes, could try the solution provided in [Stack Overflow](https://stackoverflow.com/questions/15727912/sha-1-fingerprint-of-keystore-certificate) to generate a SHA-1 and see if that works?

Just to clarify, do you mean your `google-services.json` is from your Firebase console? As for the logs, I was confused since you've mentioned there was an `FIS_AUTH_ERROR`, I thought you had a way of retrieving the logs. May I know where were you able to see the error?

**Comment by MatthewCodes** [comment]
Thank you for your quick response @argzdev so I ran `keytool -list -v -keystore {keystore_name} -alias {alias_name}` and I see that the SHA1 and SHA256 fingerprints are different from what I am seeing on Firebase. Is this the issue? And yes, google-services.json is from Firebase (my apologies). Regarding the logs there are no errors in android studio but users have been sending in screenshots of this FIS_AUTH_ERROR popup.

**Comment by argzdev** [comment]
Yes, most likely what you've added is the SHA fingerprints from your debug app in the Firebase console. You should add the SHA fingerprints from your release app as well. Once you've added the SHA fingerprints, you need to download the `google-services.json` again and add this to your app. Make sure to clean and rebuild your app too.

**Comment by MatthewCodes** [comment]
Thanks for your response I'll update the SHA1 and SHA256 in Firebase then upload the new google-services followed by uploading the new aab file to the play store and wait to see if the issue is fixed.

**Comment by MatthewCodes** [comment]
@argzdev New version of the google-services.json has been uploaded, and the SHA1 and SHA256 have been updated. Still getting the same error when downloading from the play store.

**Comment by argzdev** [comment]
Thanks for trying the solution, @MatthewCodes. I'm unable to reproduce this issue on my side, it looks like this is more of a configuration issue rather than an SDK issue. Given that this may require you to share details about your project and other PII (Personally identifiable information), it's best that you continue your report to our [Firebase support](https://firebase.google.com/support). They'll be able to assist you better with your issue. That being said, I'll close this issue now. Thanks!
