### ISSUE TITLE
ANRs in Android

### ISSUE THREAD

**Issue by deepak786** [firebase/firebase-android-sdk#3661]
We have some ANRs in the Flutter Android app. So I posted an issue on the Flutter repo and after investigating from there, it seems that the issue is with the FirebaseMessaging from the native side.
And they suggested putting it here for more debugging.

Referenced issues: 
https://github.com/flutter/flutter/issues/101886
https://github.com/firebase/flutterfire/issues/8467

You can check the ANRs here https://github.com/flutter/flutter/issues/101886#issuecomment-1099097616

**Comment by argzdev** [comment]
Hi @deepak786, thanks for reporting. May I ask what Firebase products and version of the SDK are you using in Flutter? Thanks

**Comment by deepak786** [comment]
@argzdev I'm using the below Firebase products 
```
  firebase_core: 1.13.1
  firebase_auth: 3.3.11
  firebase_analytics: 9.1.2
  firebase_crashlytics: 2.5.3 #web support pending
  firebase_database: 9.0.8
  firebase_storage: 10.2.9
  firebase_dynamic_links: 4.1.1 #web support pending
  firebase_messaging: 11.2.11
  firebase_in_app_messaging: 0.6.0+9 #web support pending
  firebase_remote_config: 2.0.2
  cloud_firestore: 3.1.10
  cloud_functions: 3.2.10
```

**Comment by argzdev** [comment]
Hi @deepak786, I can see from your data that there are a lot of ANR events right after updating your app to version 3.4.1. Maybe you can investigate what changes you've made to your app, this might help you pin point the issue.

**Comment by deepak786** [comment]
@argzdev There are other issues regarding the ANRs as well but that was also closed without being solved
https://github.com/firebase/firebase-android-sdk/issues/3052
https://github.com/firebase/firebase-android-sdk/issues/3059
https://github.com/firebase/quickstart-unity/issues/1257

I believe the ANRs are similar.

So this must be analyzed.

**Comment by argzdev** [comment]
Hi @deepak786, thanks for linking the other issues as well. I tried investigating the ANR logs you've provided, but there's no clear sign that the ANR (based on the logs) were due to the `FirebaseMessaging` or `FirebaseInstanceIdReceiver` component.

Quoting darshankawar:
> Looking at the logs you shared, it doesn't seem to be caused by messaging plugin, but due to native Android code and probably due to FirebaseInstanceIdReceiver component.

If you check the ANR logs, it shows the Firebase products being used, but there's no SUSPENDED, MONITOR, or "waiting to lock" within those logs. I understand you want this to be investigated, but given that there's no reliable stacktrace, or minimal repro of this issue, it is difficult to "guess" where the issue lies.

If you can provide more evidence that the ANR issue is indeed due to a specific Firebase product, then I can probably justify an engineer’s time to dig into it with that much evidence. 

If you see something similar to `ANR Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 | com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) }`, please let us know.

**Comment by deepak786** [comment]
@argzdev the title of the above ANRs https://github.com/flutter/flutter/issues/101886#issuecomment-1099097616 says
`Input dispatching timed out (ActivityRecord{f096c18 u0 com.app/.MainActivity t3340} does not have a focused window)`

Will this help?

I also see this ANR `Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 | com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) }`

But there is no stack trace info on the Play Developer console.
![Screen Shot 2022-04-22 at 11 51 04 PM](https://user-images.githubusercontent.com/14223997/164772512-81e96a4e-6b78-4742-97c6-1dc75f98adeb.png)
![Screen Shot 2022-04-22 at 11 51 14 PM](https://user-images.githubusercontent.com/14223997/164772522-cc28f736-2d9d-40b5-9154-f458d68e76a7.png)

**Comment by deepak786** [comment]
@argzdev the title of the above ANRs https://github.com/flutter/flutter/issues/101886#issuecomment-1099097616 says
`Input dispatching timed out (ActivityRecord{f096c18} does not have a focused window)`

Will this help?

I also see this ANR `Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000010 | com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) }`

But there is no stack trace info on the Play Developer console.
![Screen Shot 2022-04-22 at 11 51 04 PM](https://user-images.githubusercontent.com/14223997/164774656-1d677dfc-4736-4c25-b284-03399c56e4ae.png)
![Screen Shot 2022-04-22 at 11 51 14 PM](https://user-images.githubusercontent.com/14223997/164774679-9734449e-754d-4998-abf1-4a408749b4d8.png)

**Comment by argzdev** [comment]
Hi @deepak786, just to confirm does this issue also have the same amount of occurrence as the previous ANR? Thanks

**Comment by argzdev** [comment]
FWIW, since we cannot verify that the issue is due to `FirebaseMessaging`, what I can advise is for you to try out the solutions provided in this [blog](https://medium.com/bumble-tech/how-we-achieved-a-6x-reduction-of-anrs-part-2-fixing-anrs-24fedf9a973f), this was shared by another developer which I think will help with your issue. Thanks

**Comment by deepak786** [comment]
@argzdev could you please verify if it is the same issue that is already reported
https://issuetracker.google.com/issues/230950647

**Comment by argzdev** [comment]
@deepak786, it does look like the same issue. With the similarity of Android 11.0 devices experiencing the same ANR.

**Comment by deepak786** [comment]
https://github.com/firebase/firebase-android-sdk/issues/3661#issuecomment-1105285178

90% OS is Android 11.
