### ISSUE TITLE
Application gets re-started from a background service (JobInfoSchedulerService) after app is closed 

### ISSUE THREAD

**Issue by sin-ka** [firebase/firebase-android-sdk#3685]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: AS Bumblebee 2021.1.1 Patch 2
  * Firebase Component: Analytics, Crashlytics, Performance, Dynamic Links, FCM, Core, Remote Config, 
  * Component version: implementation platform('com.google.firebase:firebase-bom:29.3.1')

#### Steps to reproduce:

Close app (remove from tasks), wait some seconds, new app process is started resutling in that the app is executed in the background. 

This issue did not happen when I completely removed all Firebase SDK dependencies. So it looks like there is a connection between the SDK and the app wake up in the background after the app has been closed completely. I also did a quick investigation to check which component is responsible for this behavior. It looks like the Service `com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService` is always started when the app is closed that results in a new app process which holds the app in the background.

`2022-04-28 10:51:09.043 1621-1781/? I/ActivityManager: Start proc 31802:com.app/u0a342 for service {com.app/com.google.android.datatransport.runtime.scheduling.jobscheduling.JobInfoSchedulerService}
`

Does one or more of the SDK components using this service?

**Comment by vkryachko** [comment]
This is intended behavior: we use [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) for batch event uploads which may restart the app.

**Comment by sin-ka** [comment]
@vkryachko thanks for the update on this topic. Is the service stopped after the batch event upload is done? It seems that the app is kept within the background.

**Comment by vkryachko** [comment]
Hi @sin-ka 2 things:
1. As for the service: it's not started/stopped by JobScheduler, but rather it's [bound](https://developer.android.com/guide/components/bound-services), it's up to job scheduler to bind to it and unbind from it, which I assume varies by android version and even oem. It should not matter much however, since the service would not consume any resources until jobscheduler calls into it via onStartJob/onStopJob.
2. Stopping/unbinding from a service does not automatically kill the app's process, the process can stick around, but `JobInfoSchedulerService` will not consume any resources and in the common case the host app should not be consuming any resources either(depending on the app).
