### ISSUE TITLE
FirebaseUser.getUid() sometimes returns the email instead of uid

### ISSUE THREAD

**Issue by maclne** [firebase/firebase-android-sdk#3800]
**Step 1: Are you in the right place?**

Yes

**Step 2: Describe your environment**

  * Android Studio version: Android Studio Bumblebee 2021.1.1 Patch 2
  * Firebase Component: Auth / Database
  * Component version: firebase-bom:30.0.0

**Step 3: Describe the problem**

**#### Steps to reproduce:**

On very rare occasions, FirebaseAuth.getInstance().getCurrentUser().gedUid() returns the email instead of the uid. It's the exact issue described here: https://github.com/firebase/firebase-android-sdk/issues/298

- The user's email where I am seeing it is **not** a gmail email
- user is running Android 6.0.1
- it occurs with this user consistently, causing a crash

**#### Relevant Code:**

FirebaseAuth.getInstance().getCurrentUser().getUid();

Or in case this is a part of the issue, I'm storing FirebaseAuth.getInstance in a global variable:
this.mAuth.getCurrentUser().getUid();

**Comment by argzdev** [comment]
Thanks for reporting, @maclne. It doesn't look like much have been progress have been done in the previous investigation. Could you reach out to our [Firebase support](https://firebase.google.com/support)? I think they'll be able to assist you better since you'll be able to share project details and configurations with them. That being said, I'll close this issue for now. Thanks!

**Comment by maclne** [comment]
I'm not sure how Firebase support will be able to help with a bug like this, but I will try contacting them. Perhaps it could be worth keeping this issue open in case there is anyone else experiencing the same issue and could provide more input. After all, the issue from https://github.com/firebase/firebase-android-sdk/issues/298 is still unresolved as far as I can tell.

**Comment by argzdev** [comment]
I'm thinking that the issue might be related to a backend one. However, since it might require sharing PII(Personal Identifiable Information), it's best to discuss this via our Firebase support channel. 

Another similar issue is #2434. Please do continue your report there as well, and adding a thumbs up on the post will help our engineers prioritize fixing the issue based on severity. Thanks!

**Comment by maclne** [comment]
That makes sense to me! Thanks for the quick responses!
