### ISSUE TITLE
403 forbidden after update

### ISSUE THREAD

**Issue by SudoDios** [firebase/firebase-android-sdk#3972]
HI.
I created a new project in console.firebase and added the google-services.json file to the project.
But I have this error:
`Firebase-Installations: Error when communicating with the Firebase Installations server API.‍
403 forbidden.`
`Your client does not have permission to get URL <code>/v1/projects/my-project-id/installations</code> from this server. `
But this problem did not exist in my previous projects!!

**Comment by SudoDios** [comment]
There is someone to help ?
Because I have little time.
🙏

**Comment by argzdev** [comment]
Hi @SudoDios, thanks for reporting. Could you try cleaning and rebuilding your app? If that doesn't work, could you try this [link](https://stackoverflow.com/questions/61453640/android-error-when-communicating-with-the-firebase-installations-server-api) from Stack Overflow, and see if that helps? Thanks!

**Comment by SudoDios** [comment]
Yes, I did this.  
And I also saw this link, but my error is probably due to sanctions.  
But it wasn't until a month ago!

**Comment by argzdev** [comment]
Oh, if this is about sanctions, I think it's best if you reach out to [Firebase Support](https://firebase.google.com/support/troubleshooter/contact). They'll be able to assist you better since they have visibility on your project details. Thanks!

I'll close this issue for now. Feel free to reopen if you think this is an SDK issue.
