### ISSUE TITLE
Firebase logcat logging on release build

### ISSUE THREAD

**Issue by birfincankafein** [firebase/firebase-android-sdk#403]
### Environment

  * **Android Studio version**:
> Android Studio 3.3
> Build #AI-182.5107.16.33.5199772, built on December 25, 2018
> JRE: 1.8.0_152-release-1248-b01 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.13.6

  * **Firebase Component**:
_FirebasePerformance_, _FirebaseRemoteConfig_

  * **Component versions**:
> **com.google.firebase:firebase-core**: 16.0.8
> **com.google.firebase:firebase-messaging**: 17.4.0
> **com.google.firebase:firebase-config**: 16.3.0
> **com.google.firebase:firebase-perf**: 16.2.3

### The problem

In my release build, I still can see the logs related to my configs, performance session ids, etc. It should not be logged to the console.

#### Relevant Code:

```
2019-05-03 14:35:37.064 6546-6546/? D/FirebasePerformance: Creating a new Non Verbose Session: XXXXX
2019-05-03 14:35:37.099 6546-6546/? D/FirebasePerformance: onResume(): XXXXX: 638220 microseconds
2019-05-03 14:35:38.168 6546-6569/? I/FirebaseRemoteConfig: Fetch succeeded!
2019-05-03 14:35:42.355 6546-6546/? W/FirebaseRemoteConfig: No value of type 'Boolean' exists for parameter key 'XXXXX'.
2019-05-03 14:35:42.359 6546-6546/? I/FirebasePerformance: Session ID - XXXXX
```

**Comment by ramanpreetSinghKhinda** [comment]
Thnaks birfincankafein@ for reaching out. 

`1. D/FirebasePerformance: Creating a new Non Verbose Session: XXXXX`

Session ID is an anonymous information which is solely for the debugging purposes, see:
https://firebase.google.com/docs/perf-mon/auto_duration-traces-metrics_ios-android#more-detail-trace-samples.

`2. D/FirebasePerformance: onResume(): XXXXX: 638220 microseconds`

We print the time it took for an activity to become visible, which is also for debugging purposes.

------

For the rest of the logs, assigning to RC to take a look

**Comment by clp93** [comment]
`I/FirebaseRemoteConfig: Fetch succeeded!` Most Remote Config developers are generally interested in whether their Fetches are successful or not. As such, I'd consider this WAI. Firebase Performance uses Remote Config under the hood, so you'll get the Remote Config SDK info logs as part of the package.

`W/FirebaseRemoteConfig: No value of type 'Boolean' exists for parameter key 'XXXXX'.` is a warning that appears because of how Firebase Performance uses the Remote Config SDK. I'm going to assign this back to @ramanpreetSinghKhinda  to see if his team can modify the way they call Remote Config to reduce those non-user relevant warnings.

**Comment by zijianjoy** [comment]
The fix has been submitted for stopping Firebase Performance logging by default. (To enable debug logging, follow document here https://firebase.google.com/docs/perf-mon/get-started-android#debug_your_integration) 

Expect it to be available in upcoming Firebase Performance release (around mid January, 2020).

**Comment by zijianjoy** [comment]
New Performance Monitoring version is released: https://firebase.google.com/support/release-notes/android#performance_v19-0-5.
