### ISSUE TITLE
Remote Config not fectching value due to: Firebase Installations failed to get installation auth token for fetch.

### ISSUE THREAD

**Issue by chintan369** [firebase/firebase-android-sdk#4036]
### Step 1: Describe your environment

  * Android Studio version: Chipmunk 2021.2.1 Patch 2
  * Firebase Component: Remote Config (Database, Firestore, Storage, Functions, etc)
  * Component version: BOM version 30.3.1

### Step 2: Describe the problem

I have added the remote config dependency in my project and tried to fetch the values but am unable to fetch the values as it throws an error **Firebase Installations failed to get installation auth token for fetch.** I looked for different solutions but was unable to resolve them.

I have added these dependencies and versions to my project

#### Steps to reproduce:

Implement the latest/defined version of dependencies in the project and try to fetch values from the remote config.

#### Relevant Code:

```gradle
classpath "com.google.gms:google-services:4.3.13"

dependencies {
    implementation platform('com.google.firebase:firebase-bom:30.3.1')
    implementation 'com.google.firebase:firebase-core'
    implementation 'com.google.firebase:firebase-config'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
}
```

```kotlin
val remoteConfig = FirebaseRemoteConfig.getInstance().also {
            val defaultMap = HashMap<String, Any>()
            defaultMap[Global.SYNC_INDICATION_THRESHOLD_ONLINE] = 10
            defaultMap[Global.SYNC_INDICATION_THRESHOLD_OFFLINE] = 15
            it.setDefaultsAsync(defaultMap)
        }

remoteConfig.fetch(0)
            .addOnSuccessListener {
                Log.i("Fetch Remote Config on Home", "Success")
                remoteConfig.activate()
            }.addOnFailureListener {
                Log.e("Fetch Remote Config on Home", "Failure due to: ${it.message}")
            }

```

**Comment by argzdev** [comment]
Hi @chintan369, I tried to use the same setup as yours, but I'm not experiencing any issues. You could try using our [quickstart samples](https://github.com/firebase/quickstart-android) to see what you might be doing differently.

By the way, you can remove the dependency for `com.google.firebase:firebase-core` since this is already included in `firebase-analytics`. 

In the [release notes](https://firebase.google.com/support/release-notes/android#latest_sdk_versions): 
> "The Firebase Android library firebase-core is no longer needed. This SDK included the Firebase SDK for Google Analytics."

If you're still experiencing problems after using the quickstart sample, could you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so I can investigate this further?
