### ISSUE TITLE
Enable FCM when Firebase project is dinamically initialised

### ISSUE THREAD

**Issue by axionnneeeel** [firebase/firebase-android-sdk#4068]
I am initializing Firebase dynamically with FirebaseApp.initializeApp(Builder) with all the project attributes set(including gcmSenderId), so I have no google services JSON in the project root as I'm choosing the firebase project at login. Everything works fine(auth sdk, firestore sdk, storage sdk etc.) apart from FCM. I'm getting the token successfully through onNewToken() method and then trying to send a test push to the token. I'm not getting the test push.

I've tried to set "firebase_messaging_auto_init_enabled" and "firebase_analytics_collection_enabled" to false and then after initializeApp to call FirebaseMessaging.getInstance().setAutoInitEnabled(true); but still doesn't work.

I can see in the logs that "Missing google_app_id. Firebase Analytics disabled. See ..." error is thrown so this may be the reason it's not working, but can't figure out why as google services json is missing intentionally and everything is fine after dynamically setting up Firebase.

**Comment by argzdev** [comment]
Just to give some insights, the error you're receiving `Missing google_app_id. Firebase Analytics disabled` is due to #66 - Firebase Analytics does not work when using FirebaseOptions. That said, this should not affect your FCM setup.

Thanks for the code snippet, I tried creating a clean minimal project with your setup, however, I'm still able to receive the push notification. It's possible that there are incorrect details you've provided in your `FirebaseOptions`.

Could you try the troubleshooting steps in our [documentation](https://firebase.google.com/support/privacy/init-options#troubleshoot_android_apps)? Let me know if it helps. Thanks!

**Comment by axionnneeeel** [comment]
I tried the other way to test push notifs from the same menu like "Cloud Messaging -> Send your first message -> Add notification title and text -> Next -> Set as target my app -> Next -> Next -> Review -> Publish" and it's working that way. Any idea on why the "Send test message" way didn't work?

**Comment by argzdev** [comment]
Hi @axionnneeeel, if it works with a regular campaign, then there's no issue with your dynamic setup. However, it's possible that you're sending the test message to a different FCM registration token. You could also try testing on a physical device. I noticed that there are times where an emulator receives the notification late or not at all. 

If this still doesn't work, maybe you could take a look at our [quickstart samples](https://github.com/firebase/quickstart-android), you can also use it as a reference and compare the setup with your project.
