### ISSUE TITLE
Recapatcha appears when I use verifyPhoneNumber

### ISSUE THREAD

**Issue by ABHI165** [firebase/firebase-android-sdk#4162]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____  Firebase Authentication
  * Component version: _____

### [REQUIRED] Step 3: Describe the problem
I am using Firebase Phone Authentication in my android project, but whenever I try to enable SafetyNet api via App Check, it just shows an error saying that “You must be an owner of this project to accept Terms of Service”  though I am using the same account in which I have created this project. I have also tried with different email with owner as permission but that also didn't work. And due to this  the otp sent to the users is not getting verified automatically, users have to go through the recaptcha process which open in browser .  I have already tried searching for "Android Verification API" in google cloud but there is no such api available there. 

#### Steps to reproduce:

What happened? How can we make the problem occur?
`Problem retrieving SafetyNet Token: 7: `

**Comment by argzdev** [comment]
Thanks for reporting, @ABHI165. It looks like there might be an issue on your project configuration rather than the SDK. That said, could you file an issue on our [Firebase support](https://firebase.google.com/support/troubleshooter/contact)? They'll be able to assist you better since they have visibility on your project, and you can share your configuration setup with them.

I'll close this issue for now. Feel free to ask for this to be reopened if you have further information and you think there's a problem with the SDK. Thanks!
