### ISSUE TITLE
Getting 429 on uploading Crashlytics mapping/symbol files.

### ISSUE THREAD

**Issue by shubhamgarg1** [firebase/firebase-android-sdk#4208]
Hi,

I am part of the Acrobat Android team and we have started getting a lot of 429 errors while uploading the mapping/symbols file on Crashlytics.

Execution failed for task ':app:uploadCrashlyticsSymbolFileRelease'.
> java.io.IOException: Unknown error while sending file, check network [***.gz; response: 429 HTTP/1.1 429 Too Many Requests]

This is happening on almost all of our builds on our CI servers. Has some limit been introduced on the number of requests a client can make in a day/hour?

**Comment by argzdev** [comment]
Thanks for filing, @shubhamgarg1. If this has been working before and no configuration has been changed, then I'm assuming this might be an issue on the backend rather than the SDK. That said, could you open a ticket to our [Firebase support](https://firebase.google.com/support)? They'll be able to assist you better, since they have visibility on your project details. Thanks!

I'll close this issue for now. If you feel this is a mistake, we can always reopen this.
