### ISSUE TITLE
Truncated stacktrace in the dashboard

### ISSUE THREAD

**Issue by DjordjeMancic97** [firebase/firebase-android-sdk#4228]
### [READ] Step 1: Are you in the right place?
Not sure, this issue is related to Firebase Crashlytics dashboard

### [REQUIRED] Step 2: Describe your environment

  Flutter app using firebase_crashlytics plugin 2.9.0, issue was also appearing in versions before

### [REQUIRED] Step 3: Describe the problem

App is built with flutter obfuscate command and recently when clicking on stacktrace 'TXT' view its not appearing correctly which makes it hard - impossible to deobfuscate. Attachments below display how it was appearing (it still does appear correctly sometimes) but a lot of stacktraces are displaying completely differently when clicking on 'TXT' tab. TXT tab was really useful because it formats the stacktrace and allows me to deobfuscate it easily but now I cannot do this.

Can someone tell me why is this happening, does it depend on the issue or something?

Stacktrace default view:
<img width="778" alt="Screenshot 2022-10-20 at 15 28 34" src="https://user-images.githubusercontent.com/58264548/196969906-fbe17583-75a3-4816-bc18-d8d47538b4a3.png">

Stacktrace TXT view BAD:
<img width="1138" alt="Screenshot 2022-10-20 at 15 28 46" src="https://user-images.githubusercontent.com/58264548/196969938-a71ad1bb-8dfc-4333-a74e-d87b3df400ae.png">

Stacktrace TXT view GOOD
<img width="1128" alt="Screenshot 2022-10-20 at 15 30 20" src="https://user-images.githubusercontent.com/58264548/196970043-444f2cb1-9f23-4c08-b7ae-bfe9d0998562.png">

**Comment by argzdev** [comment]
Hi @DjordjeMancic97, thanks for reporting. Could you reach out to our [Firebase support](https://firebase.google.com/support) regarding this? Since some project configuration might be needed, and we don't have access to those details on the SDK side. Our [Firebase support](https://firebase.google.com/support) will be able to assist you better since they have visibility on your project details. 

I'll close this issue for now. Feel free to ask for this to be reopened if you think this is an issue on the SDK side. Thanks!
