### ISSUE TITLE
firebase-auth is returning invalid phone number for "+61460017707"

### ISSUE THREAD

**Issue by LateralKevin** [firebase/firebase-android-sdk#425]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.3.2
  * Firebase Component: firebase-auth
  * Component version: 17.0.0

### [REQUIRED] Step 3: Describe the problem

Firebase Auth is incorrectly returning "Invalid Phone" for a valid number  "+61460017707" 

#### Steps to reproduce:

     PhoneAuthProvider.getInstance().verifyPhoneNumber(
                 "+61460017707"),        // Phone number to verify
                60,                 // Timeout duration
                TimeUnit.SECONDS,   // Unit of timeout
                (Activity) mContext,               // Activity (for callback binding)
                mCallbacks);        // OnVerificationStateChangedCallbacks
    
The callback will return

com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code].

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

   PhoneAuthProvider.getInstance().verifyPhoneNumber(
                 "+61460017707"),        // Phone number to verify
                60,                 // Timeout duration
                TimeUnit.SECONDS,   // Unit of timeout
                (Activity) mContext,               // Activity (for callback binding)
                mCallbacks);        // OnVerificationStateChangedCallbacks

**Comment by aguatno** [comment]
Hi @LateralKevin sorry for the delay. I'd like to know if you're still having this issue. I've tried running our Firebase quickstart and I was able to send OTP code using Firebase Auth SDK v19.1.0:

![rsz_73321652_2583689458320250_943511947364532224_n](https://user-images.githubusercontent.com/56451054/67510558-c07f3e00-f6c7-11e9-800b-dfc4757dbe59.png)

However, if the issue persists, could you try using our [Android Auth quickstart](https://github.com/firebase/quickstart-android) and see if the issue is reproducible?

Thanks!
