### ISSUE TITLE
So many OutOfMemoryError on Android 10

### ISSUE THREAD

**Issue by 0xera** [firebase/firebase-android-sdk#4388]
* Android Studio version: No matter
  * Firebase Component: Config, Analytics, Crashlytics, Performance
  * Component version: 29.3.0, 30.4.1

I have a lot of OOM after updating the SDK from version 29.3.0 to 30.4.1. The number of OOM increased 5 times on devices running Android 10, and decreased on Android 12 and 11. After downgrading the version, I observe that OOM decreases on Android 10, and Android 11, 12 began to grow again. I'm afraid to upgrade to the new version. Crashes are recorded in AppGallery:

```
java.lang.OutOfMemoryError error: pthread_create error (1040 KB stack): Try again
in java.lang.Thread.nativeCreate(native method)

```
<img width="867" alt="Снимок экрана 2022-12-01 в 18 06 47" src="https://user-images.githubusercontent.com/56160164/205122441-c0ec9405-4f6c-4ee3-8633-760b7b456f7a.png">

The error occurs in Firebase Analytics, Performance and Config

**Comment by argzdev** [comment]
HI @0xera, thanks for reporting. It might be difficult to pin point which Firebase product is causing the OOM. In your case, I recommend using the underlying version of each Firebase product you're using within BoM for now instead of using `com.google.firebase:firebase-bom` as a whole. You may see the specified version of each product in our [release notes](https://firebase.google.com/support/release-notes/android#compare-bom-versions) according to BoM version. Then update your versions individually, and see which product at which version is causing the OOM. I know this is a lot of work on your side, but I think this is the only way to pin point which product and which version is causing the issue. 

I'll mark this as `needs-info` for now. Don't worry if the issue closes due to stale, we can always reopen this once we have new information. Thanks!

**Comment by 0xera** [comment]
HI. @argzdev, do you have some OOM trackers in your libraries? I see a lot of issues about it

**Comment by argzdev** [comment]
There were OOM issues in the past, but those are from Firebase Auth, and Firebase Messaging. However, you're not using those libraries so I don't think that's causing you issues. 

You could try using the [memory-profiler](https://developer.android.com/studio/profile/memory-profiler) tool of Android Studio. It might give you a hint what's consuming a lot of memory.

Also do you have any code snippet related to Analytics, Performance, Crashlytics, or Remote Config? Any chance you could share them with us? Or if you could provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) of the issue, then that'll help us a lot investigating this. Thanks!

**Comment by argzdev** [comment]
Looking at your stacktrace, it shows that the issue might be due to `com.google.firebase.perf.metrics.Trace.stop`. I see an issue that might be similar to your case #4146. Could you try using the latest version `20.3.0` for Firebase Performance and see if that helps with your issue? Thanks

**Comment by 0xera** [comment]
can I update only one library with specific version and use bom for other libraries?

**Comment by argzdev** [comment]
Yes, you can do something like this:
```
    implementation platform('com.google.firebase:firebase-bom:30.4.1')
    implementation 'com.google.firebase:firebase-analytics'
    // Specify the version
    implementation 'com.google.firebase:firebase-perf:20.3.0'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-inappmessaging-display'
    implementation 'com.google.firebase:firebase-inappmessaging'
```

Let me know if it works, thanks!
