### ISSUE TITLE
how to protect the google api key in google-service.json

### ISSUE THREAD

**Issue by hackneal** [firebase/firebase-android-sdk#4425]
As described in https://github.com/firebase/firebase-android-sdk/issues/1583, the API key are hard-coded in the google-service.json. And it can be obtained easily by just decompiling the apk file.

Is there any way to protect these keys in google-service.json?

**Comment by thatfiredev** [comment]
@hackneal the API key is considered public and doesn't need to be secured, as described in [our docs](https://firebase.google.com/docs/projects/learn-more#config-files-objects). You just have to make sure to secure your database/storage service with Security Rules.
Additionally, you might want to add [Firebase App Check](https://firebase.google.com/docs/app-check) to protect your backend from abuse.

**Comment by argzdev** [comment]
@hackneal, probably another alternative is you could use `FirebaseOptions` so you won't have to use a `google-service.json`, however please note that this not work for Firebase Analytics.

Sample code snippet:
```
FirebaseOptions options = new FirebaseOptions.Builder()
    .setApplicationId(getString(R.string.firebaseApplicationId))
    .setApiKey(getString(R.string.firebaseApiKey))
    .setDatabaseUrl(getString(R.string.firebaseDatabaseUrl))
    .build();
FirebaseApp.initializeApp(this /* Context */, options);
```

**Comment by thatfiredev** [comment]
See the paragraph right after the bulletpoints (and after the red warning). It states:

> The content of the Firebase config file or object is considered public, including the app's platform-specific ID (Apple bundle ID or Android package name) and the Firebase project-specific values, like the API Key, project ID, Realtime Database URL, and Cloud Storage bucket name.

We also have a documentation page dedicated to [API Keys](https://firebase.google.com/docs/projects/api-keys).

---

> **hackneal:** Could the key be utilized to call the API service?

Not sure what you mean by "API service", but if you're talking about the REST API, then no. API Keys can't be used to call our REST APIs - their authentication requires either a *Google OAuth2 access token* or a *Firebase ID token* (see [docs](https://firebase.google.com/docs/database/rest/auth)).
But note that a Firebase ID token can be generated from a client app with the correct API Key. That's why it's important to set up Security Rules and App Check. We have an ongoing series of videos about app security on our Youtube channel, it's called [Better Safe Than Sorry](https://www.youtube.com/playlist?list=PLl-K7zZEsYLn8MLdXIx8LlzAXceQPu9cx), I would recommend checking it out. :)
