### ISSUE TITLE
firebaseApp.get(FirebaseMessaging.class) returns null

### ISSUE THREAD

**Issue by apoddubnaya** [firebase/firebase-android-sdk#4450]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2021.3.1 Patch 1
  * Firebase Component: FirebaseMessaging (Database, Firestore, Storage, Functions, etc)
  * Component version: 23.1.0

#### Steps to reproduce:

What happened? How can we make the problem occur?

Trying to provide not null FirebaseMessage instance using Dagger but get NullPointerException.
`java.lang.NullPointerException: firebaseApp.get(FirebaseMessaging::class.java) must not be null`

Merged Manifest already has all metadata ComponentRegistrars including `FirebaseMessagingRegistrar` and `FirebaseInstallationsRegistrar`

The issues is occurred only for release builds and only for some users.

We do not have steps to reproduce yet.

**Can be important**

This crash is **not** shown in Firebase Console but it is shown in Google Play Console
We have several FirebaseMessaging instances from different Firebase projects

#### Relevant Code:

```
    @Qualifier
    @Retention(AnnotationRetention.BINARY)
    annotation class FcmAppKey(val value: String)

    @Provides
    @Singleton
    @FcmAppKey("Project_1")
    fun provideFirebaseMessagingProject1(@ApplicationContext context: Context): FirebaseMessaging {
        val firebaseApp = FirebaseApp.initializeApp(
            context,
            FirebaseOptions.Builder()
                .setApplicationId(PROJECT_1_APP_ID)
                .setApiKey(PROJECT_1_API_KEY)
                .setProjectId(PROJECT_1_PROJECT_ID)
                .build(),
            "firebase_project_name_1"
        )
        return firebaseApp.get(FirebaseMessaging::class.java)
    }
    
    @Provides
    @Singleton
    @FcmAppKey("Project_2")
    fun provideFirebaseMessagingProject2(@ApplicationContext context: Context): FirebaseMessaging {
        val firebaseApp = FirebaseApp.initializeApp(
            context,
            FirebaseOptions.Builder()
                .setApplicationId(PROJECT_2_APP_ID)
                .setApiKey(PROJECT_2_API_KEY)
                .setProjectId(PROJECT_2_PROJECT_ID)
                .build(),
            "firebase_project_name_2"
        )
        return firebaseApp.get(FirebaseMessaging::class.java)
    }
```

**Comment by argzdev** [comment]
Hi @apoddubnaya. This is a very interesting use case, thanks for sharing these details with us. However, currently FirebaseMessaging does not support senderId or secondary app initialization, so I believe it is expected not to work properly in some cases.

There is a similar request to support this use case or create a migration guide for this #4316. Please do leave a thumbs up react emoji on the main post of #4316, it'll greatly help our engineers prioritize adding it to the roadmap based on severity and demand. That said, since this is a similar request. I'll be closing this for now and marking this as a duplicate. Feel free to ask this to be reopened if you think this is a mistake. Thanks!

**Comment by mkubiczek** [comment]
@argzdev But is this really the case? Is this kind of bug impossible in single FirebaseApp instance setup. We did already have some issues with Firebase components not being discovered (at that time seems to be related to dynamic feature modules) reported here https://issuetracker.google.com/issues/218088929. Since the messaging component is registered in Manifest it should always be found by the component discovery mechanism and I would expect the FirebaseApp.get(FirebaseMessagingService::class) to never return null.

**Comment by argzdev** [comment]
Thanks for the extra details, @mkubiczek. You do raise some reasonable points, which makes me not entirely sure if your issue is due to FirebaseMessaging not supporting secondary initialization or some issues with the component discovery mechanism. Although, you're correct, assuming that the messaging component is already registered, the `FirebaseApp.get(FirebaseMessagingService::class)` should not return null values.

I'll reopen this for now and consult with our engineers to see if they have ideas regarding this.
