### ISSUE TITLE
Google Play Policy Data safety policy change Email Address

### ISSUE THREAD

**Issue by dasilkworth** [firebase/firebase-android-sdk#4478]
Manifest section is:
    // Firebase Crashlytics
    implementation 'com.google.firebase:firebase-crashlytics-buildtools:2.9.2'
    implementation platform('com.google.firebase:firebase-bom:31.1.1')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

After a minor update, upgrading to 'com.google.firebase:firebase-bom:31.1.1' from 30.0.0, and submitting an update to google play, my app is now violating the Google Play Policy:
Issue found: Invalid Data safety form
We found an issue in the following area(s):
SPLIT_BUNDLE 40: Policy Declaration - Data Safety Section: Personal Info Data Type - Email Address

It is not clear, after reading [the Firebase SDK](https://firebase.google.com/docs/android/play-data-disclosure) including this:
"Collects a user's email address (as provided by the developer) if the app uses any of the following:
email password authentication
email link authentication
a federated identity as an authentication method and the federated provider's response contains the email address"

My app does not directly ask for or use user email addresses in any way, and does not use any form of user authentication other than what Google Play does to install, and provide inapp and subscription purchases with Billing.
Is this policy violation change caused by Firebase, and if so, exactly how should I fill out the data safety form?

Is the Google Play review process objecting to the use of my own (not the user's) email address to send me crashlytics notifications?

**Comment by argzdev** [comment]
Hi @dasilkworth, thanks for reporting. We do not collect any email addresses from Firebase Crashlytics and Google Analytics. 

[Firebase Crashlytics](https://firebase.google.com/docs/android/play-data-disclosure#crashlytics) only collects the following:
- Stack traces
- Relevant application state
- Relevant [device metadata](https://firebase.google.com/support/privacy#crash-stored-info)
- Crashlytics installation UUID

[Google Analytics](https://firebase.google.com/docs/android/play-data-disclosure#analytics) on the other hand collects:
- App-instance ID
- Advertising ID
- Masked IP address
- In-app purchases and subscriptions
- App lifecycle events
- User-ID
- Account identifiers

As for the [documentations](https://firebase.google.com/docs/android/play-data-disclosure), you've mentioned.
> It is not clear, after reading [the Firebase SDK](https://firebase.google.com/docs/android/play-data-disclosure) including this:
"Collects a user's email address (as provided by the developer) if the app uses any of the following:
email password authentication
email link authentication
a federated identity as an authentication method and the federated provider's response contains the email address"

This is only being collected if you are using Firebase Authentication, and since you aren't using this library, you might have to check if you're collecting email addresses somewhere in your app. If you are using Firebase Authentication, then updating your Policy Data safety policy should resolve this issue. That said, this doesn't seem like an issue on the SDK side. I'll close this now. If you think this is a mistake, feel free to ask this to be reopened. Thanks!

**Comment by dasilkworth** [comment]
Thank you very much for your attention and the clarifications.  Since my app does not use email addresses, I am still at a loss to explain the policy violation.  It must be some other framework dependency like Billing or even an error in the Google Play detection process.

Regards, Duane

⁣Sent from BlueMail ​

**Comment by argzdev** [comment]
Yes, I believe you're correct it might be another library dependency that is using email addresses. You might have to check on those. I'm not sure but it might be worth trying to reach out to [Google Play console help](https://support.google.com/googleplay/android-developer/gethelp). I think they'll be able to tell you which library(s) in your app is in violation of the policy.
