### ISSUE TITLE
Firebase Remote Config is not getting updated for some users or devices

### ISSUE THREAD

**Issue by imidhuntv** [firebase/firebase-android-sdk#4736]
Environment

  * Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
  * Firebase Component: Firebase Remote Config
  * Component version: 21.1.0

Problem

We have an app which is used by more than 100 million users and we are using firebase remote config for changing the App config in that. Recently we have found that for some users (~5000 users) their firebase config is not getting updated.

On a closer look, we found that they are having really old config values (2 years old) . Their Apps are getting updated but their firebase values are not getting updated.

Further investigation revealed that their firebase config fetch() call and firebase config activate() call are successful on each launch. But when we try to get the value of a key it is returning the old value. 

This issue is seen in (Xiaomi | vivo |OPPO |samsung | realme)  devices with OS versions (29 | 30 | 28 | 31 | 27).

How is this possible only for 0.005% of users? What can be done here? Any help would be appreciated.

#### Steps to reproduce:

We don't have physical access to any of these devices. We used Kibana logs to understand this issue. In our test devices we are not able to replicate this bug.

**Comment by argzdev** [comment]
Hi @imidhuntv, thanks for reaching out to us. I have a hunch that it might be due to the small % of your users not having GMScore. Devices need to have GMSCore v3 or better for it to use Firebase Remote Config properly.

That said, it might be difficult to pin point the culprit of your issue without a minimal reproducible example. Any chance you could share code snippets related to Firebase Remote Config? It might give us a clue to what's causing the issue.

**Comment by manumathew17** [comment]
same problem with Chinese manufacturers
@imidhuntv  have you got any solution?
