### ISSUE TITLE
Unlinking google account let the email to the user

### ISSUE THREAD

**Issue by tristan-garaud** [firebase/firebase-android-sdk#4880]
Hi,
I noticed that when I am unlinking my google account when a fresh signed-in is requiered, it is still working but partially.
The provider is well removed but the email is still attached to the user.
I just tested it with the linking process and the linking is also working but I have an error.
I can check on the firebase console that my user is well unlink, but I can still see that the email is associated.
![image](https://user-images.githubusercontent.com/61656494/231210552-1cd05cbe-087f-402c-9756-fcbcec79f8d3.png)

I should get an error saying that I need a frsh sign in no ?

It seems I only have this problem with google provider.

EDIT:
based from this answer there is nothing to do:
https://stackoverflow.com/questions/55036015/firebase-unlink-doesnt-completely-unlink-the-facebook-provider?rq=1
Trying to update the email to empty is not working neither.
If anyone as any idea, thanks.

Thanks

**Comment by argzdev** [comment]
Hi @tristan-garaud, thanks for reporting. I tried testing 3 scenarios:

Scenario 1:
- Login with password provider
- Unlink account
- Password provider changes to Anonymous provider in Firebase Console

Scenario 2:
- Login with Google Sign In provider
- Unlink account
- Google provider changes to empty provider in Firebase Console
- Relogging in will still match the UID of the Google provider

Scenario 3:
- Login with Phone provider
- Unlink account
- Relogging in will not match the UID of the previous Phone provider

There seems to be an inconsistency of behavior (scenario 2 vs 1, 3). I expected the behavior of Scenario 2 (Google Sign In) should match the behavior of the other scenarios (1 & 2). That said, I'll notify our engineers and see what we can do here.

**Comment by argzdev** [comment]
Hi @tristan-garaud, after verifying with our engineers, it seems that this is working as intended. According to our engineers, we regard email as the primary identifier and email password sign in as the first factor provider so that's why the behavior is different.

> I noticed that when I am unlinking my google account when a fresh signed-in is requiered, it is still working but partially.
The provider is well removed but the email is still attached to the user.
I just tested it with the linking process and the linking is also working but I have an error.
I can check on the firebase console that my user is well unlink, but I can still see that the email is associated.

Can you clarify with me the issue you've encountered:
1. Use google sign in
2. Unlink google sign in, email is still attached
3. Link the google sign in with another email
4. error is shown

**Comment by argzdev** [comment]
Hi, since we've verified this is working as intended, and this has been stale for the follow up questions for sometime now. I'll go ahead and close this issue. Feel free to come back here once there's further information. Thanks!
