### ISSUE TITLE
Firebase dynamic link click and app install from Play Store not showing "open" button

### ISSUE THREAD

**Issue by chhota89** [firebase/firebase-android-sdk#4918]
When clicking a Firebase dynamic link and installing the app from the Play Store, the "open" button does not appear on the app's Play Store listing after installation. Only the "uninstall" button is visible.

**Steps to reproduce**

1 Create a Firebase dynamic link that deep-links to a specific content within the app.
2 Share the link and click it on a device that does not have the app installed.
3 Install the app from the Play Store using the dynamic link.
4 After installation, observe that the "open" button is not visible on the app's Play Store listing.

**Expected behavior**
After installing the app from a Firebase dynamic link, the app's Play Store listing should show both the "open" and "uninstall" buttons.

**Screenshots**
![processed-6d79ce77-19cd-4411-98d6-ab55fd18f411_PcRZYPET](https://user-images.githubusercontent.com/15259136/233347321-0a61f039-c09f-486d-b3b8-b79898ed8bbd.jpeg)

**Environment**
Device: MI 11 X
OS version: Android 11
Firebase Dynamic link sdk: 21.0.1. 
Tested on multiple devices

**Additional context**
This issue only occurs when installing the app from the Play Store after clicking a Firebase dynamic link. If the app is installed directly from the Play Store, both the "open" and "uninstall" buttons are visible.

**Comment by argzdev** [comment]
Hi @chhota89, thanks for reporting. Could you file an issue to our [Firebase support](https://firebase.google.com/support/troubleshooter/contact)? They'll be able to assist you better since they have visibility on the backend side of things. I'll close this issue now. Feel free to ask this to be reopened if you think this is a mistake, or there is an issue on the SDK side. Thanks!
