### ISSUE TITLE
Smarter queue-up of pending updates when network is disabled.

### ISSUE THREAD

**Issue by reeshabhkumarranjan** [firebase/firebase-android-sdk#507]
## What feature would you like to see?
Smarter pending updates when I call `db.disableNetwork();` 
When `db.disableNetwork();` is called, the updates made to a single document are queued up. Instead, in order to reduce the number of writes, only the last value should be included in pending updates, if multiple updates are made to the same document.

## How would you use it?
I am using Firestore in my app. Now my app has a lot of writes. Like, think of counter thingy. User can increment the counter from 1 all the way up to 3. Currently, each increment is a separate write. So I thought of minimising writes by disabling the network for Firestore (`db.disableNetwork()`) and enabling it at a particular time in the day. However, it just queues up the updates. Like if the counter goes from 1 to 2 to 3, it doesn't store only one update of 3, instead, it queues up, even though the update is to the same document. So when network is enabled (`db.enableNetwork()`), it first updates to 2 then 3 (I checked this using the web console of Firestore, just when I enabled network).

**Comment by wilhuff** [comment]
Hi! This feature was in our very first designs for the SDK.

Unfortunately, one thing we found that was problematic with this was interactions with rules. Specifically, consider a state machine where documents are allowed to go only from state `A` to `B` to `C`. Now imagine a document on the server containing `A` and you have a client with two valid writes queued up, one containing `B` and the next containing `C`. When we send these writes serially this succeeds, but if we coalesce the writes the server only sees a transition from `A` to `C` which it won't allow.

Even worse, the opposite problem is also possible: writes that should have failed may succeed because they skip a state that would have caused a denial.

Aside from the counter example you gave, how else do you think your application would be affected by this interaction with rules?

**Comment by reeshabhkumarranjan** [comment]
Hey Gil! Thanks for the response! I now understand the reason why it queues up. The state machine example was really helpful for me to understand it.
Well apart from the counter example, my app won't be affected much. Now, in order to optimise the writes, I am adding Room database to my application. So I will use Firebase to synchronise the user data at a single time in the day, and the local database will be handled by Room.
