### ISSUE TITLE
When I upgraded Firebase to version 32.1.1, I could not see the version count on the Firebase dashboard.

### ISSUE THREAD

**Issue by wellcao** [firebase/firebase-android-sdk#5146]
A few days ago, I upgraded Firebase to version 32.1.1. Now, there are tens of thousands of users on this version, but I still cannot see this version in the Firebase dashboard. Additionally, the Crash panel is prompting me to upgrade the Analytics SDK and Crashlytics SDK versions. Moreover, I cannot see any log reports in the DebugView panel. Please tell me what's going on.
![SchS144pez](https://github.com/firebase/firebase-android-sdk/assets/22925196/ef533eb0-2ef2-44c9-9efd-1ff2f5fbb9d9)

**Comment by argzdev** [comment]
Hi @wellcao, thanks for reaching out. Our [Firebase support team](https://firebase.google.com/support/troubleshooter/contact) is more suitable to help you with your issue since they'll have visibility on your project configuration. You may share your project details with them and they'll be happy to assist you further. Thanks!
