### ISSUE TITLE
[question] Firebase AppCheck and cloud function Api for Widget

### ISSUE THREAD

**Issue by abinhho** [firebase/firebase-android-sdk#5156]
## What feature would you like to see?

I am using cloud function as an Api and can call by http GET from Android Widget. So my question is
- When widget refresh, is AppCheck trigger?
- If yes, how can I stop it.
- If no, how can I enable AppCheck when Widget refresh?

I did only follow this docs to implement AppCheck into my android app.

https://firebase.google.com/docs/app-check/android/play-integrity-provider

## How would you use it?

- Can use AppCheck when widget refreshes 
- Can skip AppCheck when widget refreshes.

**Comment by argzdev** [comment]
Hi @abinhho, thanks for reaching out. 

> When widget refresh, is AppCheck trigger?

Since AppCheck enforcement is enabled on your [Cloud Function side](https://firebase.google.com/docs/app-check/cloud-functions#enforcement). Your AppCheck will only be triggered every time the cloud function calls the API. e.g. HTTP GET call from the Android Widget. This does not rely on the UI refresh cycle of your widget.

> If no, how can I enable AppCheck when Widget refresh?

You could do this by simply calling your API every time your widget refreshes. 
```
const functions = require("firebase-functions/v1");

exports.yourV1CallableFunction = functions
  .runWith({
      enforceAppCheck: true, // Reject requests with missing or invalid App Check tokens.
  })
  .https.onCall((data, context) => {
        // context.app contains data from App Check, including the app ID.
        // Your function logic follows.
        ...
  });
```

You may refer to our [documentations](https://firebase.google.com/docs/app-check/cloud-functions) for more details.

If you're looking into protecting a callable function from replay attacks, you can consume the App Check token after verifying it. Once the token is consumed, it cannot be used again. Using our [Relay protection](https://firebase.google.com/docs/app-check/cloud-functions#replay-protection). Please do note that as of writing, the replay protection beta supports only the Cloud Functions SDK for Node.js.

Let me know if this helps. Thanks!

**Comment by abinhho** [comment]
@argzdev Thank you for your replying. I understood. It’s really helpful to me.

**Comment by argzdev** [comment]
Glad to help, @abinhho. Since your question has been answered, I'll go ahead and close this now. Thanks!
