### ISSUE TITLE
onMessageReceived is not called ,when i test notification 

### ISSUE THREAD

**Issue by guptamonu4** [firebase/firebase-android-sdk#5157]
I was facing this error, Caused by: java.lang.NullPointerException: Firebase Messaging component is not present

When i add 
<service android:name="com.google.firebase.components.ComponentDiscoveryService" android:directBootAware="true" android:exported="false" >

 <meta-data android:name="com.google.firebase.components:com.google.firebase.messaging.FirebaseMessagingRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />

 <meta-data android:name="com.google.firebase.components:com.google.firebase.installations.FirebaseInstallationsRegistrar" android:value="com.google.firebase.components.ComponentRegistrar" />
 </service>
 
 these line in manifest files. 
 "Firebase Messaging component is not present " is solved, But Notification is not come .
 
 I am using 
 implementation platform('com.google.firebase:firebase-bom:32.1.1')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'

    classpath 'com.android.tools.build:gradle:8.0.1'
        classpath 'com.google.gms:google-services:4.3.15'

**Comment by argzdev** [comment]
Hi @guptamonu4, thanks for reaching out. In order for me to help you better, could you share a minimal reproducible example of your issue? Thanks!

**Comment by guptamonu4** [comment]
Hi. I am getting following error in logcat:
GCM                     com.google.android.gms.persistent    W  broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.brainpulse.ultimatebattle (has extras) }
2023-07-20 12:00:29.448 17347-17347 GCM                     com.google.android.gms.persistent    W  Unregister application com.brainpulse.ultimatebattle:0

I'm attaching manifest, project gradle, and app gradle.

[build.gradle(app).txt](https://github.com/firebase/firebase-android-sdk/files/12105392/build.gradle.app.txt)
[build.gragle(Project).txt](https://github.com/firebase/firebase-android-sdk/files/12105393/build.gragle.Project.txt)
[manifest.txt](https://github.com/firebase/firebase-android-sdk/files/12105412/manifest.txt)

Please check and update.
Regards

**Comment by argzdev** [comment]
Looking at the details you've provided, I don't see any indication that the issue is due to Firebase. If you're having problems implementing Firebase Cloud Messaging, you may refer to our [quickstart guide](https://github.com/firebase/quickstart-android). However, if you think this is an issue with Firebase, for us to properly address your issue kindly create a new thread with the details from our template. And if possible, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your issue. This will help us conduct an initial investigation.
