### ISSUE TITLE
type: feature request

### ISSUE THREAD

**Issue by Crankscase** [firebase/firebase-android-sdk#5174]
## What feature would you like to see?

Describe the feature you would like to add, ideally proposing a specific API.

## How would you use it?

Tell us how you'd use this feature in your app.

**Comment by Crankscase** [comment]
Gusto ko maging maayos ang aking performance sa android13 ko at maalis na Ang bug pati rin battery drain

**Comment by argzdev** [comment]
Hi @Crankscase, thanks for reaching out. I'll be using Google Translate to understand your issue. Since we use english as our medium of communication, internationally.

> I want my performance to be good on my android13 and get rid of the bug as well as battery drain

Could you provide some details of your issue? Specifics such as is there any stacktrace, or steps for us to reproduce the issue you're experiencing. What firebase product and version are you using?

Let me know so we can help you further! Thanks!
