### ISSUE TITLE
OutOfMemoryError on Android 10

### ISSUE THREAD

**Issue by RngNoah** [firebase/firebase-android-sdk#5226]
We found OutOfMemoryError on Android 10

Firebase components and their versions
com.google.firebase:firebase-messaging:23.1.1
com.google.firebase:firebase-bom:31.1.1
com.google.firebase:firebase-analytics-ktx:21.2.0
com.google.firebase:firebase-common-ktx:20.2.0
com.google.firebase:firebase-components:17.0.1

below is the stack trace.

`Fatal Exception: java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Try again
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start (Thread.java:883)
java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1382)
java.util.concurrent.Executors$DelegatedExecutorService.execute (Executors.java:630)
com.google.firebase.messaging.EnhancedIntentService.processIntent (EnhancedIntentService.java:75)
com.google.firebase.messaging.EnhancedIntentService.onStartCommand (EnhancedIntentService.java:105)
android.app.ActivityThread.handleServiceArgs (ActivityThread.java:4115)
android.app.ActivityThread.access$1900 (ActivityThread.java:226)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1916)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7386)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)`

**Comment by argzdev** [comment]
Hi @RngNoah, thanks for reaching out. In order for us to properly address your issue, could you help provide us more details such as is there any steps to reproduce this behavior? Also is this a consistently reproducible issue? If so, are there any code snippets or minimal reproducible example that you could share with us?

**Comment by RngNoah** [comment]
Hi @argzdev this happens when the app starts the ForegroundService and calls FirebaseCrashlytics.getInstance().log()

**Comment by argzdev** [comment]
Hi @RngNoah, I've tested `FirebaseCrashlytics.getInstance().log()` in a Foreground service. It doesn't appear to show any sign of memory leak that would lead to an OutOfMemory error using LeakCanary. That said, could you provide a more descriptive detail of what steps are needed to reproduce this behavior, code snippets, or minimal reproducible example, in order for us to investigate this further.

**Comment by RngNoah** [comment]
Hi @argzdev I don't have any more info, this error only happens on Android 10.

**Comment by argzdev** [comment]
Upon investigation, the Firebase messaging nor Crashlytics SDK doesn't seem to appear to retain any memory leaks with LeakCanary. The stacktrace could be only indicating where it finally reached an OOM overflow before crashing the app. I'd advise you to use a tool like Android Studio's Profiler You can also use a tool like LeakCanary to detect memory leaks in your application. One thing to check is that, are you processing any heavy work in your Firebase Messaging service component? If so, it would be best to schedule these jobs with a work manager.

That said, without further details steps to reproduce the behavior, codesnippets, or minimal reproducible example, there's no way for us to investigate this further or validate that the OOM is due to a Firebase product.
