### ISSUE TITLE
startActivityForSignInWithProvider crash on windows subsystem for android

### ISSUE THREAD

**Issue by xanscale** [firebase/firebase-android-sdk#5355]
### Describe your environment

  * Android Studio version: giraffe
  * Firebase Component: Authentication
  * Component version: 22.1.1

### Describe the problem
startActivityForSignInWithProvider crash on windows subsystem for android
in standard android device all works fine

just launch startActivityForSignInWithProvider to open external browser (outside WSA) and receive this, without waiting user action
```
14:58:55.220  W  com.google.firebase.auth.FirebaseAuthWebException: The web operation was canceled by the user.
14:58:55.220  W  	at com.google.android.gms.internal.firebase-auth-api.zzaas.zza(com.google.firebase:firebase-auth@@22.1.1:11)
14:58:55.220  W  	at com.google.firebase.auth.internal.zzav.onReceive(com.google.firebase:firebase-auth@@22.1.1:24)
14:58:55.220  W  	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
14:58:55.220  W  	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
14:58:55.220  W  	at android.os.Handler.dispatchMessage(Handler.java:106)
14:58:55.220  W  	at android.os.Looper.loopOnce(Looper.java:201)
14:58:55.220  W  	at android.os.Looper.loop(Looper.java:288)
14:58:55.220  W  	at android.app.ActivityThread.main(ActivityThread.java:7918)
14:58:55.220  W  	at java.lang.reflect.Method.invoke(Native Method)
14:58:55.220  W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
14:58:55.220  W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
14:58:55.261  W  Expecting binder but got null!
```

#### Relevant Code:
`Firebase.auth.startActivityForSignInWithProvider(this, OAuthProvider.newBuilder("microsoft.com").build())`

also opened on WSA https://github.com/microsoft/WSA/issues/432

**Comment by argzdev** [comment]
Thanks for reaching out, @xanscale. This doesn't seem like a straightforward issue, and it might have something to do with launching it with WSA. The deobfuscated stacktrace only shows that the error happens if the webview/browser that is opened for login, gets closed for any reason. Nothing particular of which would allow us to investigate this further. However, what I'm curious about is why does WSA close the browser intent. Firebase is only launching this browser intent on a webview. That said, I believe this is something WSA can check on their side since there's nothing else we can do on the SDK side to investigate this further. Let me know if you'd like this to be reopened if WSA have reason to believe that this should be fixed on our side. Thanks!

**Comment by xanscale** [comment]
@argzdev Thanks so much for the feedback. is there any possibility to add a flag to the sdk to not use CustomTab but a webview? or another workaround?

**Comment by argzdev** [comment]
> is there any possibility to add a flag to the sdk to not use CustomTab but a webview? or another workaround?

Sorry, currently there's no control to change the way it starts any of the GenericIdp like Twitter/X, Apple, Microsoft, Yahoo. 

> actually is not possible to use firebase auth in any way in WSA

This is interesting. So anonymous, email/password, phone, or google-sign in does not work?

**Comment by xanscale** [comment]
sorry, i our app we only use login with external providers. i supposed that google will not works, like all others device without GMS, but i supposed that all GenericIdp works :(

just for information official MSAL library works on WSA https://github.com/AzureAD/microsoft-authentication-library-for-android

**Comment by argzdev** [comment]
> PS I think that if Microsoft doesn't know exactly what you do and why you return this exception, I don't think it can do anything

The odd thing here is the exception in the stacktrace. The `The web operation was canceled by the user.` means that the error is specific to when a web context was canceled prematurely by the user. The custom tab was manually closed by the user. I'm not sure how it's possible for the WSA to trigger this given that it is a manual intervention exception.

> just for information official MSAL library works on WSA https://github.com/AzureAD/microsoft-authentication-library-for-android

The MSAL library works because it is an SDK that was built suitable for WSA. We're not using any of the MSAL library, we're only opening the GenericIdps via `CustomTabsIntent` or ACTION_VIEW (e.g. `Intent(Intent.ACTION_VIEW)`). We could consider adding MSAL library depending on the demand. However, please know that this will be considered as a feature request. And we won't have a timeline when it will be added on our radar.

> PS I think that if Microsoft doesn't know exactly what you do and why you return this exception, I don't think it can do anything

This would be difficult for us, given that the error code shows that it is a "manual" intervention exception. I don't see how we can investigate this further.

**Comment by xanscale** [comment]
due to closed source of library we don't know exactly what it means "web context was canceled prematurely by the user"

another thing: actually customtab is mandatory? what appen on device without a compatible browser?

PS actually WSA using customtab open a tab inside default browser and not inside WSA context (i suppose)

PS2 if you already supporto non compatible device with customtab just considera WSA as non compatible

**Comment by xanscale** [comment]
first time i read about WSA's WebView, seams there is some logic based on url to use webview instead of external browser.

seams to be sufficient to format url based on that, but I do not found any specific info

**Comment by kevinkieselbach** [comment]
I'm an engineer on the WSA team, and we're happy to update our browser redirection logic if appropriate. For context, WSA doesn't include a full Android browser since we redirect http/https intents to the Windows default browser instead (a desktop browser running natively is generally preferrable to a mobile browser running in a VM). However, authentication scenarios run into many compatibility issues redirecting between OSes, so WSA opens authentication URLs in a stub Android browser (a WebView) as an exception to the usual policy of redirecting to the Windows default browser. We rely on heuristics, such as URLs with a query parameter value that is also a URL (likely a redirect URL), to identify authentication URLs. The heuristics work well across a wide range of apps, but heuristics aren't perfect.

Based on the symptoms described, it sounds like this authentication URL is being redirected to the Windows default browser instead of opening in WSA's stub Android browser. The operation was "canceled" because the Android activity finishes after redirecting to Windows and authentication libraries typically expect the activity to remain alive until authentication is complete. This means the authentication URL wasn't correctly classified by WSA's heuristics. Can you please share the authentication URL passed to the browser in this scenario? If there's a distinctive query parameter, we can update our heuristics to check for that.

**Comment by argzdev** [comment]
HI @kevinkieselbach, thank you for the explaining how WSA's heuristics work. That said, our authentication URL passed to the browser is something like this "https://<domain/__/auth/handler?providerId=<value>&authType=<value>&apn=<value>". Would this open the URL inside the Android Webview?

**Comment by kevinkieselbach** [comment]
Our heuristics currently check for query parameters whose value is a URL (likely a redirect URL) or whose name is "redirect_uri", "code_challenge", or "RelayState".  The first two are standard OAuth query parameters and the third is a standard SAML SSO query parameter.  Most authentication URLs contain a redirect URL, but we added the "code_challenge" and "RelayState" heuristics for cases that didn't contain a redirect URL.

I'm assuming the "providerId", "authType" and "apn" values are not URLs, which explains why the URL isn't recognized as an authentication URL.  I think "authType" is reasonable to add to our heuristic since the false positive rate should be low.  I couldn't find documentation on these query parameters.  Are they part of a stable protocol?

**Comment by prameshj** [comment]
It would be great if we can use the "/__/auth/handler" in the URL PATH as the heuristic. 

The login flow works like this:

App -> browser opens https://<hostname>/__/auth/handler?authType=..... -> redirects to provider specific login page like "accounts.google.com/... redirectUri..." ->  returns to app.

The "__/auth/handler" parameters are not standard OAuth/SAML params, but once we redirect to the provider's login page, they will be protocol-specific url params. WSA would need to open that initial URL though.

**Comment by kevinkieselbach** [comment]
We could check if the URL path matches "/__/auth/handler".  What's the advantage of checking the path versus the "authType" query parameter?  Is the path less likely to change in a future version of Firebase?

**Comment by prameshj** [comment]
> We could check if the URL path matches "/__/auth/handler". What's the advantage of checking the path versus the "authType" query parameter? Is the path less likely to change in a future version of Firebase?

It is more for a lower chance of false positives.. since authType is probably used as a param in other non-Firebase flows, but the "/__/auth/handler" could be more specific. We don't have plans to change either the path or remove the "authType" param in the near future.

**Comment by xanscale** [comment]
@kevinkieselbach we need to wait next release of WSA or heuristics are cloud based?

**Comment by argzdev** [comment]
Thanks for the speedy updates, @kevinkieselbach. We'll close this issue now.
