### ISSUE TITLE
NO FIREBASE DO ANDROID - ANDROID SDK ESTÁ COM ESSA OBSERVAÇÃO.

Mas aqui   https://github.com/firebase/firebase-android-sdk/blob/master/firebase-config/firebase-config.gradle está tudo normal . 

A segurança tá falhando novamente com bug e invasores?

### ISSUE THREAD

**Issue by ASSIAPLI** [firebase/firebase-android-sdk#5425]
## What feature would you like to see?

Describe the feature you would like to add, ideally proposing a specific API.

## How would you use it?

Tell us how you'd use this feature in your app.

**Comment by argzdev** [comment]
Hi @ASSIAPLI, thanks for reaching out. I'm using google translate to understand your message:
> IN THE ANDROID FIREBASE - ANDROID SDK HAS THIS NOTE. But here https://github.com/firebase/firebase-android-sdk/blob/master/firebase-config/firebase-config.gradle everything is normal. Security is failing again with bugs and attackers

In order for us to help you, could you file a new issue thread with the complete details regarding the specific security bug and issue that you're referring to so that we may assist you properly. These information will be helpful for us to conduct an initial investigation. Thanks!
