### ISSUE TITLE
Dynamic link not work when app is not installed

### ISSUE THREAD

**Issue by Timeszoro** [firebase/firebase-android-sdk#547]
###  Environment

  * Android Studio version: __3.4.1___
  * Firebase Component: __Dynamic Link___
  * Component version: ___17.0.0__
  * com.google.firebase:firebase-dynamic-links:17.0.0

### Problem
I just implemented dynamic link these days, and encounter a problem.

When i tap the dynamic link and it will lead me to the google play, and after i installed the app, a "continue" button will show, and when i tap the "continue" button , it will lead me to the deferred  link page as i expected. until now, everything works very fine,
![a](https://user-images.githubusercontent.com/4311560/59862333-2a53a800-93b5-11e9-8e04-8629f7143f43.jpg)

but if i open the app directly instead of tapping the "continue" button, it will not lead me to the page i expected. is this a bug or by design behavior, why not send "com.android.vending.INSTALL_REFERRER"  broadcast, so we can jump to the expected page even if i open the app first time through tap app icon instead of tap "continue" button in google play.

**Comment by apoorvans** [comment]
Same problem.

**Comment by vkryachko** [comment]
I believe this is not something FDL has control over, you should create a feature request Play Services/AOSP

**Comment by apoorvans** [comment]
> I believe this is not something FDL has control over, you should create a feature request Play Services/AOSP

Thanks for the input @vkryachko. This doesn't seem to be a corner case. Would you be able share some data on how many app installs are followed by a Continue tap vs tapping on the app icon? We were considering using this for app referral tracking but seems like it won't work in a significant number of cases.

**Comment by vkryachko** [comment]
hey @apoorvans , apparently there is a play services [installreferrer](https://developer.android.com/google/play/installreferrer/library.html) library. Would that work for you?

**Comment by apoorvans** [comment]
> hey @apoorvans , apparently there is a play services [installreferrer](https://developer.android.com/google/play/installreferrer/library.html) library. Would that work for you?

Thanks for the reference @vkryachko . We checked it out, it seems to save referral information in play services that can be queried after app install.
The problem is in the step before that - we were hoping to use FDL to point the user to play store (pre-install) and then pass the deep link info to the app after install. Which is what happens if we make the user install using a market url ~ market://blablah. Play services publishes utm referral info that the app can process (take to a deep link) after install.
But in case of FDL, it seems like unless the continue button is tapped, the information is not passed to play services or to app.
We are considering workarounds like branch.io hoping they solve the problem or make our own tracker that uses a market url.

**Comment by meyyappanv** [comment]
Hi @vkryachko, as mentioned by @apoorvans this is definitely not a corner case. It is very true that 

> Unless the continue button is tapped, the information is not passed to play services or to app.

Could you please re-open this issue?
Also if you think `something FDL has control over` are you aware of the bug tracker link for the same? If yes, could you please share the same here for the benefit of the people who come here searching a solution for this issue.
Thanks in advance.

**Comment by meyyappanv** [comment]
@samtstern @ashwinraghav ping !!! Could you please help here?

**Comment by nes123** [comment]
+1

Just to add that from our analytics, 70% of our users do not press on the "continue".
