### ISSUE TITLE
CloudMessagingReceiver.zza PendingResult.finish() on a null object reference

### ISSUE THREAD

**Issue by jiduqingqian** [firebase/firebase-android-sdk#5553]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Giraffe | 2022.3.1 Patch 3
  * Firebase Component: CloudMessage
  * Component version: 
  ```
com.google.firebase:firebase-bom:31.1.1
  com.google.firebase:firebase-messaging:23.0.0
com.google.firebase:firebase-iid:21.1.0
com.google.firebase:firebase-core:18.0.0
```

### [REQUIRED] Step 3: Describe the problem
We have a significant number of crash reports in crashlytics with this obfuscated stack trace:
```
Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.BroadcastReceiver$PendingResult.finish()' on a null object reference
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:6)
       at com.google.android.gms.cloudmessaging.zze.run(com.google.android.gms:play-services-cloud-messaging@@17.0.0:10)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
       at java.lang.Thread.run(Thread.java:1012)
```
<img width="575" alt="image" src="https://github.com/firebase/firebase-android-sdk/assets/9583596/9c8806d6-fef9-4223-a7c6-0440809a1edd">

This is currently by far our largest open crash cluster
I'm happy to provide any additional data that might help here.

#### Steps to reproduce:

We don't have a local repro for this issue, but it's certainly affecting people in the wild.

#### Relevant Code:
The error stack does not point to our relevant code

**Comment by LeDaVinci** [comment]
any update?

**Comment by argzdev** [comment]
Hi @jiduqingqian, it looks like the version you're using for `com.google.firebase:firebase-messaging:23.0.0` is relatively old (October 29, 2021). Could you try using the latest version `23.3.1` and see if this fixes the issue? We usually advise this to issues that may have been fixed in the past. 

If this does not help, could you provide a full stacktrace of this issue? Also could you share any code snippets that are related to Firebase Cloud Messaging? This will help us investigate this further.

Thanks!
