### ISSUE TITLE
Crashlytics plugin causes mergeReleaseResources to never be up to date

### ISSUE THREAD

**Issue by matejdro** [firebase/firebase-android-sdk#5574]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 RC 3
  * Firebase Component: Crashlytics gradle plugin
  * Component version: 2.9.9

#### Steps to reproduce:

1. Download and extract [Project.zip](https://github.com/firebase/firebase-android-sdk/files/13474815/Archive.zip)
2. Run `./gradlew mergeReleaseResources`
3. Run `./gradlew mergeReleaseResources` again. Note that the task is not up to date even though it was just ran a second ago.
4. Comment out `id("com.google.firebase.crashlytics")` line from `app/build.gradle.kts`
5. Perform steps 2-3 again.
6. Note that task is up to date now. Crashlytics plugin was causing it to rerun every time.

**Comment by argzdev** [comment]
Hey @matejdro, thanks for reaching out. Let me consult with our engineers and get some feedback.

**Comment by mrober** [comment]
@matejdro we have a prerelease of the next major version of the Crashlytics Gradle plugin, you can find it in https://github.com/firebase/firebase-android-sdk/issues/5733. One of the improvements is better behaving Gradle tasks.

I tested running the `mergeReleaseResources` task repeatedly and get "4 actionable tasks: 4 up-to-date" even if obfuscation is enabled. Closing this issue for now since the prerelease resolves this. Please let me know if this doesn't resolve the problem for you on the other issue.
