### ISSUE TITLE
App Distribution Plugin - serviceCredentialsFile in build.gradle.kts is global, build.gradle works well

### ISSUE THREAD

**Issue by JohnZh** [firebase/firebase-android-sdk#5651]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Giraffe 2022.3.1 Patch 1
  * Firebase Component: App Distribution Gradle Plugin
  * Component version: 4.0.1
  * Gradle version: 8.0.2

### [REQUIRED] Step 3: Describe the problem

Same problem as this one: #5291
(https://github.com/firebase/firebase-android-sdk/issues/5291)

#### Steps to reproduce:

My application is configured to multiple flavors, and push APK to the firebase app distribution based on the flavors

Here is some code from my app-level build.gradle.kts
```
create("demo") {
      dimension = "version"
      applicationId = "jp.co.kakuyasu.app.dev"
      firebaseAppDistribution {
          artifactType = "APK"
          groups = "testers"
          releaseNotesFile = "ci/release-log.txt"
          serviceCredentialsFile = "${project.rootDir}/ci/demo-credential-file.json"
      }
  }
  create("demo2") {
      dimension = "version"
      applicationId = "jp.co.kakuyasu.app.stg"
      firebaseAppDistribution {
          artifactType = "APK"
          groups = "testers"
          releaseNotesFile = "ci/release-log.txt"
          serviceCredentialsFile = "${project.rootDir}/ci/demo2-firebase-credential-file.json"
      }
  }
```

When I upload my first build(Demo), it just use my second serviceCredentialsFile(demo2-firebase-credential-file.json)
```
> Task :app:appDistributionUploadDemoDebug
Using APK path in the outputs directory: /Users/john/Desktop/kakuyasu-android/app/build/outputs/apk/demo/debug/app-demo-debug.apk.
Uploading APK to Firebase App Distribution...
Using service credentials file specified by the serviceCredentialsFile property in your app's build.gradle file: /Users/john/Desktop/kakuyasu-android/ci/demo2-firebase-credential-file.json
Uploading the APK.

> Task :app:appDistributionUploadDemoDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:appDistributionUploadDemoDebug'.
> App Distribution halted because it had a problem uploading the APK: [403] The caller does not have permission
```

After I reviewed the same issue: https://github.com/firebase/firebase-android-sdk/issues/5291
I convert my build.gradle.kts to build.gradle(groovy version). And it works. 

Demo flavor uses the demo-credential-file.json, and demo2 flavor uses demo2-firebase-credential-file.json.

**Comment by lehcar09** [comment]
Hi @JohnZh, thank you for reaching out and reporting the issue. I tried reproducing the issue and I was able to reproduce the behavior where the build product flavors always uses the last configured “serviceCredentialsFile” parameter. I’ll notify our engineers and see what we can do here. 

With regards to the “[403] The does not have permission” error you encountered, this could be due to either [Google account](https://firebase.google.com/docs/app-distribution/android/distribute-gradle#authenticate_using_your_google_account) or [service account](https://firebase.google.com/docs/app-distribution/android/distribute-gradle#authenticate_using_a_service_account)'s PERMISSION_DENIED when using gradle. This may happen when an incorrect account is used to sign in. With that, you can double check the configuration of the method you’re using to [authenticate with App Distribution](https://firebase.google.com/docs/app-distribution/android/distribute-gradle#step_2_authenticate_with_firebase):
* For Service Accounts, verify if the role has Firebase App Distribution Admin.
* For Google Accounts, verify if the role has Project Editor or Owner.

If the 403 issue persists, it would be best to reach out to the Firebase Support channel [here](https://firebase.google.com/support/troubleshooter/contact).

**Comment by lehcar09** [comment]
Hi @JohnZh, per checking with our engineers, this issue is caused by the [non-availability of type-safe model accessors](https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:accessor_applicability). To fix the issue in configuring the [App Distribution properties](https://firebase.google.com/docs/app-distribution/android/distribute-gradle) with multiple build variants (build types and product flavors), you need to add
```
import com.google.firebase.appdistribution.gradle.firebaseAppDistribution 
```
to your build.gradle.kts build script. Or, alternatively, use `configure<com.google.firebase.appdistribution.gradle.AppDistributionExtension> {…}` instead of firebaseAppDistribution {…} in the same file.

Apologies for missing this, this was documented in the App Distribution Gradle plugin version 3.1.0 [release notes](https://firebase.google.com/support/release-notes/android#appdistro_gradle_plugin_v3-1-0) and in our [documentation](https://firebase.google.com/docs/app-distribution/android/distribute-gradle#step_3_configure_your_distribution_properties), but it's very easy to miss - and unfortunately stuff almost works without the import and only breaks for things like multiple build flavors.
