### ISSUE TITLE
Generated google-services.json is incomplete oauth_client object is missing on new added app #2536

### ISSUE THREAD

**Issue by navalega0109** [firebase/firebase-android-sdk#5658]
Facing same issue as mentioned in earlier bug [2536](https://github.com/firebase/firebase-android-sdk/issues/2536)

**Comment by lehcar09** [comment]
Hi @navalega0109, thank you for reaching out. The #2536 issue and what you’re encountering is possibly due to any of the following reasons:
* Phone authentication is not enabled
* Android Device Check API is not enabled
* SHA-1 and 256 are not configured or have an issue.

I suggest re-checking the configuration from this [documentation](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification). I would be best to reach out to the [Firebase support channel](https://firebase.google.com/support/) to check on the details and troubleshoot the issue further.
