### ISSUE TITLE
Firebase analytics first_open and session_start events not sent when consent granted using consent mode

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firebase/firebase-android-sdk#5697]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 2023.1.1
  * Firebase Component: Analytics
  * Component version: 21.5.0

### [REQUIRED] Step 3: Describe the problem

We are using consent mode v2 to disable analytics_storage, ad_storage, ad_user_data and ad_personalization_signals as specified in https://developers.google.com/tag-platform/security/guides/app-consent?platform=android.

When the app is opened for the first time we show a dialog asking if they wish to be tracked and once users grant the consent, we enable analytics_storage, ad_storage, ad_user_data, and ad_personalization_signals through Firebase analytics.

When users grants consent, we expect certain auto-log events like first_open to be sent;  However, those events are not sent. We only get events logged that are triggered after the user grants consent.

The dialog is shown as soon as the app starts so there is not much delay between first_open being triggered and users granting consent. We expect events like first_open to be sent as soon as consent is granted as those are important events for us to determine installs, lifetime value, cohort analysis etc., and allow Firebase analytics dashboard to work correctly (to report retention, lifetime value, installs etc.).

Ideally, we expect analytics to work normally when users grant consent; by using consent mode we don't have analytics working correctly even when users grant the consent on app start.

#### Steps to reproduce:

1. Follow instructions in https://developers.google.com/tag-platform/security/guides/app-consent?platform=android to disable analytics_storage, ad_storage, ad_user_data, and ad_personalization_signals through manifest
2. When app starts show a dialog to ask users consent and when tracking is allowed set FirebaseAnalytics.ConsentStatus.GRANTED for analytics_storage, ad_storage, ad_user_data, and ad_personalization_signals
3. Enable debug view for the app as specified in https://firebase.google.com/docs/analytics/debugview#android
4. Run the app and notice in DebugView console in analytics that first_open and other auto events are not received after user grants consent

#### Relevant Code:
Android Manifest:
```
<meta-data android:name="google_analytics_default_allow_analytics_storage" android:value="false" />
<meta-data android:name="google_analytics_default_allow_ad_storage" android:value="false" />
<meta-data android:name="google_analytics_default_allow_ad_user_data" android:value="false" />
<meta-data android:name="google_analytics_default_allow_ad_personalization_signals" android:value="false" />
```

Set consent status function; set limitTracking to false when user grants consent:
```
private fun setLimitedTracking(limitTracking: Boolean){
    firebaseAnalytics.setConsent {
            val consentStatus = if(limitTracking) FirebaseAnalytics.ConsentStatus.DENIED else FirebaseAnalytics.ConsentStatus.GRANTED
            analyticsStorage = consentStatus
            adStorage = consentStatus
            adUserData = consentStatus
            adPersonalization = consentStatus
        }
}
```

**Comment by lehcar09** [comment]
Hi @faizanabidnaqvi, thank you for reaching out. I was able to experience the behavior you reported. Per checking with our engineers this is working as intended. The first_open and session_start events are collected before the user grants the consent. The consent is not applied retroactively. These events are collected, however, they would not have some fields like DSID and app instance ID that subsequent events would have, due to consent being denied. The debugview console might simply not display those events, perhaps because consent is denied or perhaps because they don't have the identifiers that debugview could use to associate them with the test device.

It would be best to reach out to the [Google Analytics team](https://support.google.com/analytics/?hl=en#topic=10737980) as they'll be able to assist you further since they have visibility on the backend side, and you'll be able to share project details. Thanks!
