### ISSUE TITLE
FirebaseMessaging : Topic sync or token retrieval failed on hard failure exceptions.

### ISSUE THREAD

**Issue by shakunm1** [firebase/firebase-android-sdk#5713]
We have found that Firebase Token is not generated at device after analyzing the logs internally in the team even though FirebaseApp Installation was successful. We saw an error as below:

**`     FirebaseMessaging   <package-name> E  Topic sync or token retrieval failed on hard failure exceptions: java.util.concurrent.ExecutionException: java.io.IOException: TOO_MANY_REGISTRATIONS. Won't retry the operation.`**

 We have dig in to the Firebase SDK code and we were able to reach till below code:
 
```
    @Override
    @SuppressLint("WakelockTimeout") // WakeLock will always be released
    public void run() {
      if (ServiceStarter.getInstance().hasWakeLockPermission(getContext())) {
        syncWakeLock.acquire();
      }
      try {
        // this should have already been set to true, do it again for safety.
        firebaseMessaging.setSyncScheduledOrRunning(true);
        if (!firebaseMessaging.isGmsCorePresent()) {
          firebaseMessaging.setSyncScheduledOrRunning(false);
          return;
        }
        if (ServiceStarter.getInstance().hasAccessNetworkStatePermission(getContext())) {
          if (!isDeviceConnected()) {
            ConnectivityChangeReceiver receiver = new ConnectivityChangeReceiver(this);
            receiver.registerReceiver();
            return; // return and wait for connectivity
          }
        }
        if (maybeRefreshToken()) {
          firebaseMessaging.setSyncScheduledOrRunning(false);
        } else {
          firebaseMessaging.syncWithDelaySecondsInternal(nextDelaySeconds);
        }
      } catch (IOException e) {
        Log.e(
            TAG,
            "Topic sync or token retrieval failed on hard failure exceptions: "
                + e.getMessage()
                + ". Won't retry the operation.");
        firebaseMessaging.setSyncScheduledOrRunning(false);
      } finally {
        if (ServiceStarter.getInstance().hasWakeLockPermission(getContext())) {
          syncWakeLock.release();
        }
      }
    }

```

We would like to get a few clarifications from the Firebase support team with respect to above code:
1. What is hard-failure? How will the developer be able to identify what is hard-failure?
2. So, in the block of code where the error is thrown. What might have caused the IOException? We would like to know the probable reasons?

Kindly let us know if you want to refer to our approach towards handling Firebase Messaging in our app. But this has become crucial and we are left with no confirmed reasons for this issue after N number of findings in the internet about it. I hope you understand the concern that only the Firebase team can help us here.

**Comment by lehcar09** [comment]
Hi @shakunm1, thank you for reaching out. TOO_MANY_REGISTRATION issue usually occurs in cases:

1. When a client has a multitude of apps registered with FCM, this would trigger the TOO_MANY_REGISTRATIONS error. The problem here is, the only mitigation is for the user to delete some of the other client apps from the device to make room for the new one.
2. Otherwise, the device is likely "cloned" from another one, so that multiple devices have the same identifiers. In this case, the best thing is factory-reset.

Unfortunately, there's nothing we can do on the SDK side since we don't have any visibility on the backend. It'll be best for you to reach out to our [Firebase support](https://firebase.google.com/support/troubleshooter/contact) for better assistance. You'll be able to share your project details and configuration which will allow them to support you better. Thanks!

**Comment by shakunm1** [comment]
@lehcar09 In our case, each app is having different Project ID. So, I doubt that whether we can classify it under multitude behavior. 
It is very difficult to convince end-customer to delete apps from his phone because we will not be aware of the requirement to have them installed on the phone. I strongly urge that there should be a way to handle it. Kindly help. Thanks.
