### ISSUE TITLE
A/B tests problem when dynamically enabling analytics collection

### ISSUE THREAD

**Issue by karlslattorp** [firebase/firebase-android-sdk#5745]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Hedgehog | 2023.1.1 Patch 2
  * Firebase Component: A/B Testing
  * Component version: 32.2.3 (Bill of Materials)

### [REQUIRED] Step 3: Describe the problem

A/B tests, of type Remote Config, are not showing the correct experiment results when dynamically enabling analytics collection.
The devices are not reporting data to it.

#### Steps to reproduce:

1. Have a setup with an app and a Firebase project which is working with A/B tests of type Remote config.

2. Instead of having analytics data collection on by default, follow the instructions on 
[https://firebase.google.com/docs/analytics/configure-data-collection?platform=android](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android)
regarding on how to temporarily disable collection by setting

`<meta-data android:name="firebase_analytics_collection_enabled" android:value="false" />`

in the AndroidManifest.xml, followed by in code enabling analytics collection by calling 

`setAnalyticsCollectionEnabled(true)`

when analytics collection should be started

3. When setAnalyticsCollectionEnabled(true) has been called, the device starts to send analytics data, but it does not report to the experiment.

#### Relevant Code:

Full logs attached:
WORKING_when_having_data_collection_enabled_as_default.txt
and
NOT_WORKING_when_not_having_data_collection_enabled_by_default.txt
and also, a screenshot for the targeting setup in firebase is attached

The interesting parts of the logs are:
From 
WORKING_when_having_data_collection_enabled_as_default.txt:

`V/FA-SVC  User property triggered: se.mycompanyname.client.android.debug, experiment_id(_exp_25), 1`

Followed by that the bundles that is sent with the analytics events include:

```
V/FA-SVC      user_property {
V/FA-SVC        set_timestamp_millis: 1709292387906
V/FA-SVC        name: experiment_id(_exp_25)
V/FA-SVC        string_value: 1
V/FA-SVC      }
```

There is no such printouts in the log
NOT_WORKING_when_not_having_data_collection_enabled_by_default.txt

So FA-SVC does not set the device to be part of the experiment when setAnalyticsCollectionEnabled(true) was called, even though it can be seen in the logs that the activation event was sent 

<img width="577" alt="a_b_test_setup" src="https://github.com/firebase/firebase-android-sdk/assets/110818648/9082cf3f-dc45-44c2-96ce-f281a5a38b45">

[WORKING_when_having_data_collection_enabled_as_default.txt](https://github.com/firebase/firebase-android-sdk/files/14460562/WORKING_when_having_data_collection_enabled_as_default.txt)

[NOT_WORKING_when_not_having_data_collection_enabled_by_default.txt](https://github.com/firebase/firebase-android-sdk/files/14460563/NOT_WORKING_when_not_having_data_collection_enabled_by_default.txt)

**Comment by lehcar09** [comment]
Hey @karlslattorp, per checking with our engineers this is WAI.

For context, the Remote Config automatically fetches and activates the parameter. When the RC activates, it also triggers Google Analytics setConditionalUserProperty that indicates the ABT experiment in the fetched RC parameter. If the Google Analytics collection is disabled, when the Remote Config fetches and activates the experiment is not reported and you’ll see a log “Conditional property not set since app measurement is disabled”.

Enabling the Google Analytics, doesn’t include setting the conditional user property because RC is the one that triggers the user property. 

If the app fetches and activates your again (i.e. any Remote Config parameter changes) and Google Analytics is enabled the ABT experiment in that Remote Config parameter will be reported.

That said, I’ll go ahead and close the issue now. Let me know if I misunderstood anything or we need to re-open the issue for further investigation. Thanks!
