### ISSUE TITLE
[FIAM] - Frequently getting `Successfully fetched 0 messages from backend`

### ISSUE THREAD

**Issue by niteshnarayan** [firebase/firebase-android-sdk#5786]
### [REQUIRED] Step 2: Describe your environment

Android Studio version: Android Studio Jellyfish | 2023.3.1 Canary 13
Build #AI-233.14475.28.2331.11543046, built on March 7, 2024

Emulator : Android 13 TE1A.220922.010
Device: Huawei Mate 20 Pro Android 12
Device: Samsung S23 Android 14

  * Firebase Component: 
    implementation 'com.google.firebase:firebase-analytics-ktx:21.5.1'
    implementation 'com.google.firebase:firebase-inappmessaging-display-ktx:20.4.0'
    implementation 'com.google.firebase:firebase-messaging-ktx:23.4.1'

### [REQUIRED] Step 3: Describe the problem

Hi, I have integrated FIAM as per the official documentation and would like In-App messages to be displayed on analytics events, but for some reason on app reinstall and also in general getting 0 messages from the backend. Occasionally the messages(I have multiple live campaigns and the correct number is displayed) show up and make it difficult to test. Any idea if I am missing something here? Logs below:

- I  Starting InAppMessaging runtime with Installation ID eR2FUe7xTNKoKGTYNH6HL4
- I  went foreground
- I  Binding to activity: x.appidoo.com.application.MainActivity
- I  Setting display event component
- I  Forcing fetch from service rather than cache. Test Device: false | App Fresh Install: true
- I  Fetching campaigns from service.
- I  Setting display event component
- I  Successfully fetched 0 messages from backend

I have single Activity in which i have the SDK init:

```
  override fun onResume() {
        super.onResume()
        FirebaseApp.initializeApp(this)
        FirebaseInAppMessaging.getInstance().setMessageDisplayComponent(
            MessageDisplayComponent(baseContext)
        )
    }

```

**Comment by lehcar09** [comment]
Hi @niteshnarayan , thank you for reaching out. I tried reproducing the issue, but I was unsuccessful. I was able to receive the message without an issue. Is there any chance you could provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue? If you're unable to provide one, can you try our [quickstart app](https://github.com/firebase/quickstart-android/tree/master/inappmessaging) and see if you can reproduce the issue?

Aside from that, I recommend migrating dependency from the main module instead of the KTX modules. KTX modules are now deprecated. As early as April 2024, we'll no longer release KTX modules, and we'll also remove the KTX libraries from the Firebase Android BoM at that time. You can check this [documentation](https://firebase.google.com/docs/android/kotlin-migration) for more details.

**Comment by niteshnarayan** [comment]
Hi @lehcar09 thanks a lot for the reply. Unfortuantely i dont do anything extra apart from whatever already mentioned, so cant provide any MCVE. I will try to follow quick start guide and see if still having the issue. Thanks for the migration info!

**Comment by lehcar09** [comment]
HI @niteshnarayan, I'll set the 'needs-info' tag for now. Let us know if the issue is resolved on your side. Please do keep in mind that our SDK support team do not have access to the backend or your project details. For us to verify if this is an SDK issue, we require steps to reproduce this behavior or a minimal reproducible example for us to conduct investigation on your issue.
