### ISSUE TITLE
Caused by java.lang.IllegalArgumentException Receiver not registered: com.google.firebase.iid.zzay@a54f79c

### ISSUE THREAD

**Issue by nesger** [firebase/firebase-android-sdk#586]
use library:
```
releaseImplementation 'com.google.firebase:firebase-messaging:17.6.0'
```
Fabric crash log:
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.google.firebase.iid.zzay@2014dc28

Caused by java.lang.IllegalArgumentException: Receiver not registered: com.google.firebase.iid.zzay@2014dc28
```

**Comment by aguatno** [comment]
Hi @nesger sorry for my late response here. It looks like crash log didn't persist in the latest version. I was wondering if you're still having this issue? If so, could you provide the following so that I can investigate the issue further:

- Minimal repro of your code that I can run locally
- Firebase SDK version you're using
- Any other relevant information
