### ISSUE TITLE
Weak Hash Algorithm Used

### ISSUE THREAD

**Issue by Yusei0205** [firebase/firebase-android-sdk#6016]
Our app has identified usage of weak crypto algorithms like SHA1 in Firebase SDK in the security code scanning result performed by the penetration testing team, which can be vulnerable to various types of collision attacks, which can compromise the security of hashed data. 

Recommendation from the report:
Remove the weak hashes SHA-1 hashing algorithm. Technical Standards Reference
https://github.com/MobSF/owasp-mstg/blob/master/Document/0x04g-Testing-Cryptography.md#identifying-insecure-andor-deprecated-cryptographic-algorithms-mstg-crypto-4

We have check that the usage of SHA1 is coming from the following path: com.google.firebase.installations.local.IidStore
Based on the comment on the source code knowing that it is used for backward compatibility purpose however the security team has concern on this and there is no proper documentation stating that there are no security concerns regarding the use of weak SHA1.

Is there any version without the weak crypto algorithm and any workaround to remove or exclude it from the library? Also what is the min android version that do not require the SHA1 crypto algorithm for backward compatibility purpose?

**Comment by lehcar09** [comment]
Hi @Yusei0205, thank you for reaching out. For context, the [Firebase Installations service](https://firebase.google.com/docs/projects/manage-installations#kotlin+ktx_1) (FIS) is an infrastructure service for Firebase services, providing a targeting identifier (FIDs), client-authentication scheme (FIS auth tokens), and a centralized deletion flow that allows Firebase services to be GDPR and wipeout compliant.

FIS replaced [Instance ID service (IID)](https://firebase.google.com/support/privacy/manage-iids). FIS honors existing Instance IDs in order to not break Firebase Targeting. FIS makes sure that every Firebase Installation is targetable with exactly one Firebase identifier (Instance ID or FID).

In order to make sure that all Firebase services use the same identifier, all Firebase services have to effectively switch from IID to the new identity provider (FIS) at the same time. The [Instance ID SDK v.20.1.0](https://firebase.google.com/support/release-notes/android#iid_v20-1-0) was updated to depend on the FIS SDK for identifier creation.

As mentioned in the [comment](https://github.com/firebase/firebase-android-sdk/blob/7a313c35145f584152335a33f6a0a481ecfd11a4/firebase-installations/src/main/java/com/google/firebase/installations/local/IidStore.java#L179-L183):

>    // FirebaseInstallations SDK uses the SHA1 hash for backwards compatibility with the legacy InstanceID SDK.
>    // The SHA1 hash is used to access Instance IDs stored on the device and not for any security relevant process. 
>    // **This is a one-time step that allows migration of old client identifiers.**
>    // Cryptographic security is not needed here so potential hash collisions are not a problem.

That said, if you were using Instance ID SDK v.20.1.0 and above, the step will not execute.

**Comment by lehcar09** [comment]
I'll go ahead and close this thread now. Let me know if there's any misunderstanding and/ or we need to re-open the issue for further investigation. Thanks!
