### ISSUE TITLE
 UnsatisfiedLinkError: dlopen failed & has unexpected e_machine: 183 (EM_AARCH64)

### ISSUE THREAD

**Issue by weitsunglin** [firebase/firebase-android-sdk#6053]
current ndk version in build.gradle: implementation 'com.google.firebase:firebase-crashlytics-ndk:18.3.2'

and I encountered this problem

java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.XXX.XXX-hjSBpZmYsvZt2WdjPXJA3Q==/lib/arm64/libcrashlytics-handler.so" has unexpected e_machine: 183 (EM_AARCH64)

thanks!!

**Comment by lehcar09** [comment]
Hi @weitsunglin, thank you for reaching out. In order for us to help you, could you file a new issue thread with the complete details regarding the specific bug and issue that you're referring to so that we may assist you properly. These information will be helpful for us to conduct an initial investigation. Thanks!

**Comment by weitsunglin** [comment]
Tip: Our build.gradle is set to /lib/arm64-v84, but the system is using /lib/arm64 to read the package, which is very strange!!!
