### ISSUE TITLE
firebase-crashlytics-ktx:version 19.0.2 mutes firebase-messaging-ktx.

### ISSUE THREAD

**Issue by H0neyHunter** [firebase/firebase-android-sdk#6085]
The version of firebase-crashlytics-ktx:19.0.2 affects firebase-messaging-ktx:24.0.0 and all versions of firebase-messaging. And notifications are muted too.

### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: _____
  * Firebase Component: _____ (Database, Firestore, Storage, Functions, etc)
  * Component version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by lehcar09** [comment]
Hi @H0neyHunter, thank you for reaching out. I tried reproducing the issue, however, I did not encounter an issue in using `-ktx` modules. Below is the dependency I used.

app/build.gradle.kts
```
    implementation("com.google.firebase:firebase-crashlytics-ktx:19.0.2")
    implementation("com.google.firebase:firebase-messaging-ktx:24.0.0")
```

Could you elaborate on the issue you're experiencing? If by any chance, can you share an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to help us investigate the issue?

In addition to that, we recommend using the main modules instead of the KTX modules (when using [Firebase BoM v32.5.0+](https://firebase.google.com/support/release-notes/android#bom_v32-5-0). The Kotlin extensions (KTX) APIs have been added to their respective main modules. For example, all the APIs from firebase-perf-ktx have been added to firebase-perf under the com.google.firebase.perf package.

As part of this change, the Kotlin extensions (KTX) APIs in every KTX module are now deprecated. As early as April 2024, we'll no longer release KTX modules, and we'll also remove the KTX libraries from the Firebase Android BoM at that time. You can check this [documentation](https://firebase.google.com/docs/android/kotlin-migration) for more details.
