### ISSUE TITLE
Hi, thanks for reporting!

### ISSUE THREAD

**Issue by Heyitsquoracom** [firebase/firebase-android-sdk#6115]
Hi, thanks for reporting!
The best practices in https://cloud.google.com/identity-platform/docs/web/redirect-best-practices need to be applied only for web applications that use the `signInWithRedirect` web SDK API. Hence, no action is needed for mobile apps.

If there are other reasons why you need this feature, could you please describe your use case and why you need this? Thanks!

_Originally posted by @NhienLam in https://github.com/firebase/firebase-android-sdk/issues/4805#issuecomment-1485706028_

**Comment by lehcar09** [comment]
Hi @Heyitsquoracom, in order for us to help you, could you file a new issue thread with the complete details regarding the specific security bug and issue that you're referring to so that we may assist you properly. These information will be helpful for us to conduct an initial investigation. Thanks!
