### ISSUE TITLE
Weak Cryptographic key used in firebase SDK.

### ISSUE THREAD

**Issue by DIYApps** [firebase/firebase-android-sdk#6455]
* Android Studio version:  Android Studio Koala | 2024.1.1 Patch 2
  * Firebase Component:  Firestore, Messaging(Database, Firestore, Storage, Functions, etc)
  * Component version: 35.1.2

### [REQUIRED] Step 3: Our app has identified usage of weak crypto algorithms like SHA1  and MD5 in Firebase SDK in the security code scanning result performed by the penetration testing team, which can be vulnerable to various types of collision attacks, which can compromise the security of hashed data. The reference to these algorithms are found in CipherSuite Class(OKHTTPS). 
Is there any version without the weak crypto algorithm and any workaround to remove or exclude it from the library? 

#### Steps to reproduce:

Build Apk with these dependencies and search for the SHA1 and MD5 in APK analyzer. 

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by lehcar09** [comment]
Hi @DIYApps , thank you for reaching out. Firebase Firestore and Messaging does indeed use MD5 and SHA-1. However, this is not in a security context. 

For instance, in Firestore, an MD5 is used as part of an algorithm that keeps Firestore’s local cache in sync with the server. The warning about using an insecure hash algorithm can be safely ignored. We chose MD5 over a cryptographically-secure hashing algorithm because the performance of MD5 was measured to be significantly better and security was not needed for this particular hash. As for FCM, SHA-1 is used as an identifier for deduplication. 

Based on your description

>The reference to these algorithms are found in CipherSuite Class(OKHTTPS).

I suggest reaching out to the [OkHttp team](https://github.com/square/okhttp/pulls) for further clarification.

That said, I’ll close this issue now. Let me know if there’s any misunderstanding so we can re-open the issue. Thanks!
