### ISSUE TITLE
DEADLINE_EXCEEDED throw by callable function

### ISSUE THREAD

**Issue by matteobucci** [firebase/firebase-android-sdk#744]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.5
  * Firebase Component: Functions (Database, Firestore, Storage, Functions, etc)
  * Component version: 19.0.0

### [REQUIRED] Step 3: Describe the problem
I'm getting DEADLINE_EXCEEDED exception when trying to call a function and sending a base64 payload with it.

#### Steps to reproduce:
Just call a function with a large enough payload and the exception will trigger.
Important to notice that the second time that I call it the function works properly. Probably the cold-start time of the function contributes to this problem.

What happened? How can we make the problem occur?
I think that the problem is on the writeTimeout of the OkHttp client. I'm not an expert of that library but it may be possible that the setTimeout function is just about the complete call and not the upload part. Here's the reference
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#writeTimeout-java.time.Duration-

**Comment by bklimt** [comment]
Have you tried using `setTimeout` to increase the timeout on the `HttpsCallableReference`?

https://firebase.google.com/docs/reference/android/com/google/firebase/functions/HttpsCallableReference.html#setTimeout(long,%20java.util.concurrent.TimeUnit)

**Comment by allisonbm92** [comment]
@matteobucci Can you include the full, call trace, so that we can see exactly what is exceeding the deadline? Thanks!

**Comment by Zeliret** [comment]
I have this problem every cold execution. 
I tried `withTimeout(30, TimeUnit.SECONDS)`, but the exception still the same:
`Caused by: java.net.SocketTimeoutException: failed to connect to <uri> (port 443) after 10000ms`

**Comment by ReguloSarmiento** [comment]
I have the same problem as well. It happens the first time the onCall function is invoked. Sometimes It throws this exception even when the function completes successfully.

**Comment by aguatno** [comment]
Hi @matteobucci usually, the error message "Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded." is possibly caused by a write operation hitting the quota per second limit. Here’s our [documentation](https://firebase.google.com/docs/firestore/quotas) for more details.

If this isn’t the case, could you provide the following information in order for us to know what might be causing the issue:

- Detailed or step-by-step instructions to reproduce the issue (screenshot of each step would be great)
- A runnable, [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) of the issue (just make it minimal so I can easily reproduce the issue on my end)
- Full, call trace, so that we can see exactly what is exceeding the deadline

Additionally, here’s a related [Stack Overflow post](https://stackoverflow.com/questions/46655344/firebase-cloud-function-with-firestore-returning-deadline-exceeded) which might help.
