### ISSUE TITLE
Remove hard dependancy on Play Services

### ISSUE THREAD

**Issue by chrisfraser** [firebase/firebase-android-sdk#759]
## What feature would you like to see?

Currently Auth and Crashlytics have a hard dependency on Play Services. I understand that efficiencies are gained by using Play Services, but are there any plans underway to provide a fallback where Play Services is not installed?

## How would you use it?

I currently have 30000+ fully managed, single use devices in the field, half of which do not have screens. The only reason they currently have Play Services is so that I can use Firebase. I am starting a new project that will likely have even more devices, but we cannot install Play Services because the devices are not certified. The devices cannot be Play Protect certified, as the do not pass Android compatibility tests (No Screens). 

I would really like to use Firebase for this project, but cannot if Play Services remains a dependancy.

Is this on the roadmap, or are there any alternatives I could consider?

**Comment by samtstern** [comment]
@chrisfraser I believe Crashlytics works on devices without Play services ... have you tried it?  For auth we have this sample (https://github.com/FirebaseExtended/auth-without-play-services) showing how to use Firebase Auth on devices without Play services.  It's not a transparent fallback, but I hope it can help with your use case since you seem to be managing your own device fleet.

**Comment by aguatno** [comment]
Hi @chrisfraser I'd like to follow up the above recommendation. If you have any feedback, don't hesitate to comment back. Thanks.

**Comment by chrisfraser** [comment]
Hey guys, sorry for the delayed feedback here, but I have not had sufficient time to test this solution properly. I gave the sample a bash but it only works with anonymous auth. I will make time in December to extend it to hit a cloud function custom auth provider. 

I did not test the Crashlytics side of things, but will update my sample tomorrow and provide feedback.

**Comment by chrisfraser** [comment]
Just tested Crashlytics and it works perfectly.

**Comment by samtstern** [comment]
@chrisfraser thanks for checking!  Because we already have these two issues I am going to close this one.  Whenever we open source an SDK we remove any hard Play Services dependency so they are equivalent:
https://github.com/firebase/firebase-android-sdk/issues/125 (Auth)
https://github.com/firebase/firebase-android-sdk/issues/13 (Crashlytics)

**Comment by chrisfraser** [comment]
No problem @samtstern. I will keep track in those issues and feedback there.
