### ISSUE TITLE
Impossible connection only for some IP addresses

### ISSUE THREAD

**Issue by pierroo** [firebase/firebase-android-sdk#894]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs in __the code in this repository__. 
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: 3.4.2
  * Firebase Component: Database, Authentication
  * Component version:  19.1.0

#### Steps to reproduce:

Some users manage to authenticate in the app, but then are completely stuck on infinite loading, which means that the initial query to firebase realtime database never returns any result.

It's like the endpoint of firebase just won't answer (I am unable to reproduce this issue on my side, so I can't catch the error if there is any)

HOWEVER, where it gets interesting is that as soon as they connect through a VPN (or change their IP address, very simply) then everything works fine for them again.

This has been happening for all users in Egypt for the past month; which lead me to believe at first it was the kind of issue we see with Iran or UAE sometimes blocking some google services you guys rely on.

BUT lately it also started happening to some indonesian users, as well as americans.

WHY does changing the IP resolve firebase connection issue for these users, right away?

If there was any problem in my firebase configuration, it wouldn't work for all users, but it works fine for 99% of users.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by aguatno** [comment]
Hi @pierroo sorry for the late in response. This could be an isolated case and we have not received more cases like yours and I do not see an outage. Also, we haven't specifically blocked Egypt, but access to certain services is sometimes blocked by the local government or could be due to other aspects of networking conditions. You can take a look at our current known disruptions in our [Transparency Report](https://www.google.com/transparencyreport/traffic/disruptions/).

In case the issue persists, could you please provide logs that we can take a look at? If you find any patterns or info that we can use to troubleshoot, we're happy to help. Thanks
