### ISSUE TITLE
157238985: Continue button not shown when app is installed via FDL

### ISSUE THREAD

**Issue by meyyappanv** [firebase/firebase-android-sdk#920]
**Environment**

- Android Studio version: 3.5.1
- Firebase Component: Dynamic Link_
com.google.firebase:firebase-dynamic-links:19.0.0

**Problem**
Implemented dynamic link, and encountered following problem:

Upon tapping on the dynamic link I was taken to google play, and after installing the app, "**open**" button was shown while I was expecting a "**continue**" button. Upon tapping on "**open**" button I was taken to the app but not the dynamic linked page in app.

However when I click on the dynamic link again after the app installation, everything works very fine and I was taken to the app and the dynamic linked page.

**Comment by ornolisvt** [comment]
Same issue, Any solution?

**Comment by meyyappanv** [comment]
@rizafran Happy new year !!! Any update on this issue?

**Comment by meyyappanv** [comment]
Thanks @aguatno will wait to hear from you on a fix for this open issue.

**Comment by MartinRajniak** [comment]
Hi @aguatno,
could you share specifics of the bug?

Like is it happening in all cases or only in some?

I am seeing the same things and would like to know whether it is expected.

Thanks

**Comment by argzdev** [comment]
Hi all, apologies for the late response. As of the moment, the known issue is still being investigated. However, this is only happening to some. I cannot justify if this bug is true for all cases, but quite a number of related case were due to incorrect domain set in `android:host` within the manifest file. Specifically on this section of the [documentation](https://firebase.google.com/docs/dynamic-links/android/receive#add-an-intent-filter-for-deep-links).

With that said, I suggest that it's best to reach out [Firebase support](https://firebase.google.com/support) since they have more visibility on the backend side of things.

**Comment by MartinRajniak** [comment]
I can verify that in my case it was indeed the incorrect domain set in `android:host`.

**Comment by argzdev** [comment]
I'm glad you were able to resolve your issue @MartinRajniak. May I ask if this is the same case with yours @meyyappanv and @ornolisvt?

**Comment by meyyappanv** [comment]
Hi @aguatno, I have the right `android:host` set. So I'm afraid it is not the same case.

**Comment by argzdev** [comment]
Hi @meyyappanv alright, thanks for confirming.

**Comment by eldhosembabu** [comment]
Hi @meyyappanv 

Sorry for the late reply.

Could you please make sure you have an intent filter which can handle your domain in your app as mentioned here: https://firebase.google.com/docs/dynamic-links/android/receive#add-an-intent-filter-for-deep-links?

ie. for the link mentioned above : https://rapl.page.link/rTCx the resolved url is https://getrapl.com/fast-track?d%3Ddemo%26t%3D1569823045 and you are supposed to have an intent filter mentioned in the manifest to handle this link; otherwise the playstore app will not be showing the continue button.

For reference, following is the playstore url that we are using to take the users to playstore to install the app: https://play.google.com/store/apps/details?id=in.linkstreet.rapl&pcampaignid=fdl_long&url=https://getrapl.com/fast-track?d%3Ddemo%26t%3D1569823045

Let us know if that helps.

**Comment by meyyappanv** [comment]
> Hi @meyyappanv 
> 
> Sorry for the late reply.
> 
> Could you please make sure you have an intent filter which can handle your domain in your app as mentioned here: https://firebase.google.com/docs/dynamic-links/android/receive#add-an-intent-filter-for-deep-links?
> 
> ie. for the link mentioned above : https://rapl.page.link/rTCx the resolved url is https://getrapl.com/fast-track?d%3Ddemo%26t%3D1569823045 and you are supposed to have an intent filter mentioned in the manifest to handle this link; otherwise the playstore app will not be showing the continue button.
> 
> For reference, following is the playstore url that we are using to take the users to playstore to install the app: https://play.google.com/store/apps/details?id=in.linkstreet.rapl&pcampaignid=fdl_long&url=https://getrapl.com/fast-track?d%3Ddemo%26t%3D1569823045
> 
> Let us know if that helps.

@eldhosembabu , that our firebase dynamic URL. Since you tried from desktop, it took you to web application. The dynamic URL for Android points to the app's location in Play Store. We have the intent filter exactly as you have mentioned to handle the incoming request. The problem is the CONTINUE button itself is not shown after installation.

**Comment by eldhosembabu** [comment]
So are you confirming that we have an intent filter in place to handle "getrapl.com"...something like this?

`<intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data
        android:host="getrapl.com"
        android:scheme="https"/>
</intent-filter>`

**Comment by meyyappanv** [comment]
> So are you confirming that we have an intent filter in place to handle "getrapl.com"...something like this?
> 
> `<intent-filter>
>     <action android:name="android.intent.action.VIEW"/>
>     <category android:name="android.intent.category.DEFAULT"/>
>     <category android:name="android.intent.category.BROWSABLE"/>
>     <data
>         android:host="getrapl.com"
>         android:scheme="https"/>
> </intent-filter>`

Yes

**Comment by meyyappanv** [comment]
> > So are you confirming that we have an intent filter in place to handle "getrapl.com"...something like this?
> > 
> > `<intent-filter>
> >     <action android:name="android.intent.action.VIEW"/>
> >     <category android:name="android.intent.category.DEFAULT"/>
> >     <category android:name="android.intent.category.BROWSABLE"/>
> >     <data
> >         android:host="getrapl.com"
> >         android:scheme="https"/>
> > </intent-filter>`
> 
> Yes

@eldhosembabu knock knock

**Comment by JuanRdBO** [comment]
Hello, also facing problem with this. Is this still being worked on? 
I have this dynamic link: https://wallet.decaf.so/link/pay?key=DZUW85xqmhMG2DZqBW5fzQwCDX96tPq9eetpxPPh7HUp&token=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
in which Firebase opens the Play Store but does not pass the metadata so that after installation it only shows the OPEN button and not the expected CONTINUE. 

The android:host is correct and in every other scenario the dynamic links work as expected, just not when installing the app.

**Comment by meyyappanv** [comment]
> So are you confirming that we have an intent filter in place to handle "getrapl.com"...something like this?
> 
> `<intent-filter>
>     <action android:name="android.intent.action.VIEW"/>
>     <category android:name="android.intent.category.DEFAULT"/>
>     <category android:name="android.intent.category.BROWSABLE"/>
>     <data
>         android:host="getrapl.com"
>         android:scheme="https"/>
> </intent-filter>`

Is there a fix for this?

**Comment by meyyappanv** [comment]
> > So are you confirming that we have an intent filter in place to handle "getrapl.com"...something like this?
> > 
> > `<intent-filter>
> >     <action android:name="android.intent.action.VIEW"/>
> >     <category android:name="android.intent.category.DEFAULT"/>
> >     <category android:name="android.intent.category.BROWSABLE"/>
> >     <data
> >         android:host="getrapl.com"
> >         android:scheme="https"/>
> > </intent-filter>`
> 
> Is there a fix for this?

@eldhosembabu knock knock

**Comment by deekshithx** [comment]
Hi All, Hope the below solutions works.

Your SHA-256 and SHA-1 key in your **firebase> project settings> SHA certificate fingerprints** and **Play console > Release > App Integrity > App signing key certificate** should match.

Just copy the SHA-256 from Play Console and paste it into your Firebase Project.

ps: You **should also add** the SHA-256 and SHA-1 keys [generated](https://stackoverflow.com/questions/62152175/how-to-generate-sha1-sha256-md5-for-default-debug-key-using-keytool-in-mac-wi) locally in your machine into firebase(you can add multiple keys in your FB project)

**Comment by muthuvel2** [comment]
Facing the same issue. Above solutions didn't work

**Comment by muthuvel2** [comment]
Adding autoverify in intent filter fixed the issue. Hope it helps.

<intent-filter android:autoVerify="true">

**Comment by rajeshzmoke** [comment]
Had the same issue, turns out that your deep link url cant have `www` atleast for my config it didnt work and play store didnt   show `Continue` option after installing

once i removed it, play store shows continue and proper url is opened after installing the app 

dynamic link created in firebase console
code for ref

`
short link
https://example.link/xyz

long link
https://example.link/?link=https://example.com/pages/xyz&apn=com.example

so deep link url is 
https://example.com/pages/xyz
`

**Comment by meyyappanv** [comment]
> Adding android:autoVerify="true" in intent filter fixed the issue. Hope it helps.

@muthuvel2 glad to hear that it worked for you. Could you please help throw some light with sample code snippet on the entire intent filter/ activity in the manifest file?

**Comment by ODXDEV** [comment]
@meyyappanv you should have ` <data  android:host="getrapl.com"
                    android:scheme="https" /> <data android:host="" />, not   <data
                    android:scheme="rapl"
                    android:host="sso" />` in your Manifest!

**Comment by eldhosembabu** [comment]
> > > So are you confirming that we have an intent filter in place to handle "getrapl.com"...something like this?
> > > `<intent-filter> <action android:name="android.intent.action.VIEW"/> <category android:name="android.intent.category.DEFAULT"/> <category android:name="android.intent.category.BROWSABLE"/> <data android:host="getrapl.com" android:scheme="https"/> </intent-filter>`
> > 
> > 
> > Is there a fix for this?
> 
> @eldhosembabu knock knock

This seems like an issue with the play store app. We have filed an internal bug for the same with play store app team. We are waiting for their response. Reference: b/210713996

**Comment by MiftahClassifieds** [comment]
Hi,
I have same issue 
What i did for fix:
clearing google app store data
result: instead of showing uninstall, it shows  'open' button instead of continue, and clicking on it, it doesent handle my dynamic link because it lost intent data!
Im very confused because i checked all my dependencies and are correctlly set: host filter ..
one more thing: I had a red error in google console developer --> deep link , but after removing 'www' from intent in manifest
the error gone.
but still waiting for solution , I thank this issue is related with Google App Store since when we clear data for their app the behaviour of thier store buttons changes

**Comment by joceljunior** [comment]
Guys, I'm going through the same problem, do you have any news on this subject?

**Comment by meyyappanv** [comment]
> Guys, I'm going through the same problem, do you have any news on this subject?

Not yet. Waiting to hear from @eldhosembabu

**Comment by argzdev** [comment]
Hi folks, we'd like to inform you that the Firebase Dynamic Links service will be shutdown on August 25, 2025. In the meantime, only critical or security issues will be fixed in the SDK.

More at https://firebase.google.com/support/dynamic-links-faq
