### ISSUE TITLE
An internal error has occurred. [ 7: ] 

### ISSUE THREAD

**Issue by gitton** [firebase/firebase-android-sdk#988]
### [REQUIRED] Step 2: Describe your environment

  * Firebase Component: Authentication/Database 

Android OS version:4, 5, 6, 7 8, 9, 10
Google Play Services version: 3.2.1
Firebase/Play Services SDK version: 11.8.0

### [REQUIRED] Step 3: Describe the problem
Getting following error
Non-fatal Exception: com.google.firebase.c: An internal error has occurred. [ 7: ]
at com.google.android.gms.internal.zzdxm.a + 129(zzdxm.java:129)
at com.google.android.gms.internal.zzdwn.a + 42(zzdwn.java:42)
at com.google.android.gms.internal.zzdxx.a + 11(zzdxx.java:11)
at com.google.android.gms.internal.zzdya.a + 35(zzdya.java:35)
at com.google.android.gms.internal.zzdxo.onTransact + 79(zzdxo.java:79)
at android.os.Binder.execTransact + 739(Binder.java:739)
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Non-fatal Exception: com.google.firebase.c: An internal error has occurred. [ 7: ]
at com.google.android.gms.internal.zzdxm.a + 129(zzdxm.java:129)
at com.google.android.gms.internal.zzdwn.a + 42(zzdwn.java:42)
at com.google.android.gms.internal.zzdxx.a + 11(zzdxx.java:11)
at com.google.android.gms.internal.zzdya.a + 35(zzdya.java:35)
at com.google.android.gms.internal.zzdxo.onTransact + 79(zzdxo.java:79)
at android.os.Binder.execTransact + 739(Binder.java:739)

**Comment by aguatno** [comment]
Thanks for filing this issue @gitton. The error message is similar to [#944](https://github.com/firebase/firebase-android-sdk/issues/944#issuecomment-554486835). Our engineering team continues to investigate the issue internally using this bug#144577889. I'll let you know as soon as I have more information.

**Comment by gitton** [comment]
Thank you for the quick response.

**Comment by aguatno** [comment]
Hi @gitton The issue has been fixed and indentified. The fix compose of better error handling that deals with network exceptions. However, I may not be able provide you with any specifics as to when will the fix be released in production. For now, try to catch the issue manually. Once the fix goes live, you'll not need to update to the new SDK version.

I'll close this when the fix is in prod.

**Comment by danielfaust** [comment]
@aguatno AFAIK the code number 7 refers to `CommonStatusCodes.NETWORK_ERROR` from https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes
Since there also exist other errors which could apply, are you intending to pass us the `CommonStatusCode` which raised the `FirebaseException`? Or how about extending `CommonStatusCodes` like `GoogleSignInStatusCodes` is doing it? Any ETA on when the fix will be available?

**Comment by aguatno** [comment]
Thanks for waiting. I got confirmation that this issue can be considered fixed externally. They just need to be using the newest release of Google Play services. SDK upgrade will not be needed. 

Closing this issue, please let us know if it's still happening and we can re-open it.
