### ISSUE TITLE
 FieldValue.increment not working with Tasks.await when the app is offline

### ISSUE THREAD

**Issue by FilipeLipan** [firebase/firebase-android-sdk#997]
### Environment

  * Android Studio version: 3.5 RC2
  * Firebase Component: Firestore 
  * Component version: 21.2.1

### Problem
when the phone is in air plane mode and tries to increment a value with Tasks.await(foodDocRef.update("quantity", FieldValue.increment(1))) nothing happens, no exception is thrown.
The Tasks.await is inside of a suspend function and it works normally if I remove the Tasks.await a use the callbacks. 
So the Tasks.await(foodDocRef.update("quantity", FieldValue.increment(1)))  don't work offline.

#### Steps to reproduce:

create a suspend function with coroutines
create a document reference
use Tasks.await(foodDocRef.update("quantity", FieldValue.increment(1))) to update a field

put your smartphone in air plane mode and run the code

#### Relevant Code:

```
private val db = FirebaseFirestore.getInstance()

val foodTrucksDbCollection = db.collection("FOODTRUCK")

suspend fun registerPurchase(foodId: String): String {
    val foodDocRef = foodTrucksDbCollection
                    .document(foodId)

    Tasks.await(foodDocRef.update("quantity", FieldValue.increment(1)))

    return ""
}
```

```
class FoodTruckPurchaseViewModel(val firestoreRepository: FirestoreRepository) : ViewModel() {

    fun registerPurchase(foodid: String) {

        viewModelScope.launch(Dispatchers.IO) {
            try {
                val result = firestoreRepository.registerPurchase(foodid)
                Log.d("purchase", result)
            } catch (e: Exception) {
                //handle error
                Log.e("purchase", e.message.toString())
            }
        }
    }
}
```

**Comment by mikelehen** [comment]
@FilipeLipan Thanks for reaching out.  This is actually expected behavior.  `Task` objects returned by `set()`, `update()`, etc. are marked completed when the write has been written to the backend.  If you are offline, then the write will be queued and sent to the backend once you are back online.  At that point, the `Task` will be marked completed and your `Tasks.await()` will finish.

If you want your writes to fail while offline, one option is use the [transaction API](https://firebase.google.com/docs/firestore/manage-data/transactions#transactions) to do them, since it explicitly does not support offline usage and will thus fail promptly.
